#!/usr/bin/env Rscript
# Fixed longer-run t/F thresholds, generated before simulation outcomes.
root <- "tools/scenarios/gls-factor-diagnosis"
protocol <- jsonlite::read_json(file.path(root,"protocol.json"))
values <- list(T464=qt(.975,464),T476=qt(.975,476),F464=qf(.95,2,464),F476=qf(.95,2,476))
jsonlite::write_json(list(R=as.character(getRversion()),seed=protocol$seed,values=values),
 file.path(root,"bounds.json"),auto_unbox=TRUE,pretty=TRUE,digits=17)
lines <- c("package scalafim.fmri.laws", "", "// Generated by tools/scenarios/gls-factor-diagnosis/generate_bounds.R.",
 "private[laws] object GlsFactorBounds:", sprintf("  val DefaultSeed: Int = %d",protocol$seed),
 vapply(names(values),function(n) sprintf("  val %s: Double = %.17g",n,values[[n]]),character(1)))
writeLines(lines,"modules/first-level-laws/shared/src/test/scala/scalafim/fmri/laws/GlsFactorBounds.scala")
