package scalafim.atlas.fixtures

// Generated by tools/r-parity/generate_atlas_composition.R; do not edit.
object AtlasCompositionFixture:
  final case class Case(name: String, first: Vector[Int], second: Vector[Int], ancestry: Vector[Int])
  val cases: Vector[Case] = Vector(
    Case("partial-overlap", Vector(7, 7, 19, 0, 0, 0, 19, 0), Vector(0, 7, 0, 7, 19, 0, 19, 0), Vector(1, 3, 2, 3, 4, 0, 4, 0)),
    Case("disjoint", Vector(7, 0, 19, 0, 0, 0, 19, 0), Vector(0, 7, 0, 7, 19, 0, 0, 0), Vector(1, 3, 2, 3, 4, 0, 2, 0)),
    Case("fully-occluded", Vector(7, 19, 19, 0, 0, 0, 0, 0), Vector(0, 7, 7, 19, 0, 0, 0, 0), Vector(1, 3, 3, 4, 0, 0, 0, 0))
  )
