package scalafim.atlas.fixtures

// Generated by tools/r-parity/generate_atlas_parcel_expansion.R; do not edit.
object ParcelExpansionFixture:
  val labels: Vector[Int] = Vector(0, 19, 7, 42, 7, 42, 19, 0)
  final case class Case(name: String, ids: Vector[Int], values: Vector[Double], partial: Boolean, background: Double, expected: Vector[Double])
  val cases: Vector[Case] = Vector(
    Case("reordered-finite", Vector(42, 7, 19), Vector(3.75, -1.25, 2.5), false, -99, Vector(-99, 2.5, -1.25, 3.75, -1.25, 3.75, 2.5, -99)),
    Case("missing-parcel", Vector(42, 7), Vector(0.29999999999999999, 0.10000000000000001), true, -99, Vector(-99, Double.NaN, 0.10000000000000001, 0.29999999999999999, 0.10000000000000001, 0.29999999999999999, Double.NaN, -99)),
    Case("missing-background", Vector(7, 19, 42), Vector(-4, 0, 9), false, Double.NaN, Vector(Double.NaN, 0, -4, 9, -4, 9, 0, Double.NaN))
  )
