package scalafim.atlas.fixtures

// Generated by tools/r-parity/generate_atlas_parcel_alignment.R; do not edit.
object ParcelAlignmentFixture:
  final case class Case(name: String, target: String, keys: Vector[String], values: Vector[Double], partial: Boolean, outcome: String, targetKeys: Vector[String], expected: Vector[Double])
  val cases: Vector[Case] = Vector(
    Case("volume-to-surface", "surface", Vector("L_p24_ROI", "L_V1_ROI", "R_p24_ROI", "R_V1_ROI"), Vector(360.0, 181.0, 180.0, 1.0), false, "pass", Vector("L_V1_ROI", "L_p24_ROI", "R_V1_ROI", "R_p24_ROI"), Vector(181.0, 360.0, 1.0, 180.0)),
    Case("surface-to-volume", "volume", Vector("R_V1_ROI", "L_V1_ROI", "R_p24_ROI", "L_p24_ROI"), Vector(181.0, 1.0, 360.0, 180.0), false, "pass", Vector("R_V1_ROI", "R_p24_ROI", "L_V1_ROI", "L_p24_ROI"), Vector(181.0, 360.0, 1.0, 180.0)),
    Case("partial", "surface", Vector("R_V1_ROI", "L_V1_ROI"), Vector(11.0, 33.0), true, "pass", Vector("L_V1_ROI", "L_p24_ROI", "R_V1_ROI", "R_p24_ROI"), Vector(33.0, Double.NaN, 11.0, Double.NaN)),
    Case("duplicate", "surface", Vector("R_V1_ROI", "R_p24_ROI", "L_V1_ROI", "L_p24_ROI", "R_V1_ROI"), Vector(1.0, 180.0, 181.0, 360.0, 999.0), false, "neuroatlas_error_duplicate_parcel_key", Vector("L_V1_ROI", "L_p24_ROI", "R_V1_ROI", "R_p24_ROI"), Vector()),
    Case("unknown", "surface", Vector("R_V1_ROI", "R_p24_ROI", "L_V1_ROI", "L_p24_ROI", "L_unknown_ROI"), Vector(1.0, 180.0, 181.0, 360.0, 999.0), false, "neuroatlas_error_unknown_parcel_key", Vector("L_V1_ROI", "L_p24_ROI", "R_V1_ROI", "R_p24_ROI"), Vector()),
    Case("missing", "surface", Vector("R_p24_ROI", "L_V1_ROI", "L_p24_ROI"), Vector(180.0, 181.0, 360.0), false, "neuroatlas_error_missing_parcel_key", Vector("L_V1_ROI", "L_p24_ROI", "R_V1_ROI", "R_p24_ROI"), Vector())
  )
