#!/usr/bin/env Rscript
# Only distribution thresholds are generated here; no fitter outcomes are read.
root <- file.path("tools", "scenarios", "corrected-gls")
p <- jsonlite::read_json(file.path(root, "protocol.json"), simplifyVector = FALSE)
fmt <- function(x) formatC(x, digits = 16L, format = "g")
counts <- function(n, low, high) {
  ok <- vapply(0:n, function(k) {
    lower <- if (k == 0L) 0 else qbeta(.05, k, n - k + 1L)
    upper <- if (k == n) 1 else qbeta(.95, k + 1L, n - k)
    lower >= low && upper <= high
  }, logical(1))
  if (!any(ok)) return(c(-1L, -1L))
  range(which(ok)) - 1L
}
profiles <- c("pilot", "screen", "confirmation")
lines <- c("package scalafim.fmri.laws", "", "// Generated by tools/scenarios/corrected-gls/generate_bounds.R before outcomes.",
  "private[laws] object CorrectedGlsBounds:",
  paste0("  val DefaultSeed: Int = ", p$seed),
  paste0("  val T236: Double = ", fmt(qt(.975, 236))),
  paste0("  val T224: Double = ", fmt(qt(.975, 224))),
  paste0("  val F236: Double = ", fmt(qf(.95, 2, 236))),
  paste0("  val F224: Double = ", fmt(qf(.95, 2, 224))))
output <- list()
for (name in profiles) {
  n <- p$profiles[[name]]$replicates
  interval <- if (name == "confirmation") counts(n, .02, .08) else c(qbinom(.0001, n, .05), qbinom(.9999, n, .05))
  lines <- c(lines, paste0("  val ", toupper(substring(name, 1L, 1L)), substring(name, 2L), "Counts: (Int, Int) = (", interval[1], ", ", interval[2], ")"),
    paste0("  val ", toupper(substring(name, 1L, 1L)), substring(name, 2L), "MeanCritical: Double = ", fmt(qt(.95, n - 1L))))
  output[[name]] <- list(replicates = n, rejection_count_bounds = interval, coverage_count_bounds = n - rev(interval),
    mean_90_percent_critical = qt(.95, n - 1L))
}
writeLines(lines, "modules/first-level-laws/shared/src/test/scala/scalafim/fmri/laws/CorrectedGlsBounds.scala")
jsonlite::write_json(list(schema_version = "scalafim-corrected-gls-bounds/v1", r_version = as.character(getRversion()),
  profiles = output, criticals = list(df236 = list(t = qt(.975, 236), f = qf(.95, 2, 236)), df224 = list(t = qt(.975, 224), f = qf(.95, 2, 224)))),
  file.path(root, "bounds.json"), auto_unbox = TRUE, digits = 16L, pretty = TRUE)
