"""Extract bounded, self-contained Scala diagnostics fixtures from audit dumps.

The generated fixture is test data only.  Runtime ScalaFIM code never reads the
external evidence bundle.  Run from the repository root with the durable bundle
root as the sole argument.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path


SELECTED = (
    ("m2b-methods", "gamble", None),
    ("m2b-methods", "block", "Any difference between conditions"),
    ("m2b-methods", "dms", "Probe minus sample"),
    ("m2b-methods", "stop", "Successful stop minus go, time course"),
    ("m2b-methods", "dense", "Category × task"),
    ("m3-methods", "dupState", None),
    ("m4b-methods", "dup2State", None),
)


def scala_values(values: list[float]) -> str:
    return ", ".join(repr(value) for value in values)


def scala_chunks(values: list[float], chunk_size: int = 400) -> str:
    chunks = [scala_values(values[index : index + chunk_size]) for index in range(0, len(values), chunk_size)]
    return "Vector(" + ", ".join(json.dumps(chunk) for chunk in chunks) + ")"


def rows(run: dict) -> list[float]:
    columns = [column["data"] for column in run["cols"]]
    return [columns[column][row] for row in range(len(columns[0])) for column in range(len(columns))]


def emit_case(round_name: str, study: str, contrast_name: str | None, study_data: dict) -> str:
    runs = study_data["runs"]
    run_values = ",\n      ".join(
        f"AuditRun({len(run['cols'][0]['data'])}, {len(run['cols'])}, {scala_chunks(rows(run))})"
        for run in runs
    )
    if contrast_name is None:
        return f"  val {study}: Vector[AuditRun] = Vector(\n      {run_values}\n  )\n"
    contrast = next(value for value in runs[0]["cons"] if value["name"] == contrast_name)
    weights = ", ".join(f"Array({scala_values(row)})" for row in contrast["W"])
    # Historical raw-row standard error recorded by the original audit dump.
    # It predates the row-orthonormalized F definition and is retained only as
    # provenance; tests consume ContrastDiagnosticsFixture's NumPy oracle values.
    historical = next(value["se"] for value in study_data["stats"] if value["name"] == contrast_name)
    return (
        f"  val {study}: AuditCase = AuditCase(Vector(\n      {run_values}\n  ), "
        f"Vector({weights}), {historical!r})\n"
    )


def main() -> None:
    bundle = Path(sys.argv[1]).resolve()
    output = Path("modules/design/shared/src/test/scala/scalafim/fmri/design/fixtures/DurableContrastMatrixFixture.scala")
    chunks = []
    hashes = []
    for round_name, study, contrast_name in SELECTED:
        path = bundle / "audit" / round_name / "dump.json"
        raw = path.read_bytes()
        hashes.append((round_name, hashlib.sha256(raw).hexdigest()))
        chunks.append(emit_case(round_name, study, contrast_name, json.loads(raw)[study]))
    provenance = "\n".join(f"  // {name}/dump.json sha256: {digest}" for name, digest in dict(hashes).items())
    output.write_text(
        "package scalafim.fmri.design.fixtures\n\n"
        "/** Generated by tools/fixtures/extract_durable_contrast_matrices.py.\n"
        "  * These are exact selected raw audit matrices; no external path is used by tests. */\n"
        "object DurableContrastMatrixFixture:\n"
        f"{provenance}\n"
        "  final case class AuditRun(rows: Int, columns: Int, chunks: Vector[String]):\n"
        "    lazy val values: Array[Double] = chunks.iterator.flatMap(_.split(\",\").iterator).map(_.toDouble).toArray\n"
        "  /** `historicalRawRowSe` is the audit dump's raw-row standard error. It is\n"
        "    * provenance only, not an expected value for the current definitions. */\n"
        "  final case class AuditCase(runs: Vector[AuditRun], contrastRows: Vector[Array[Double]], historicalRawRowSe: Double)\n\n"
        + "\n".join(chunks)
    )


if __name__ == "__main__":
    main()
