"""Regenerate the independent NumPy oracle for DesignDiagnosticsFixture.

Run from the repository root with: python3 tools/fixtures/generate_design_diagnostics.py
The committed fixture was generated with NumPy 2.4.3 (recorded in its header);
regeneration with that version is byte-identical. Do not edit the fixture by hand.
The fixture intentionally uses a rank-deficient duplicate at a 1e-10 check
tolerance; Scala tests consume the emitted constants rather than reimplementing
the diagnostics formulas.
"""

from pathlib import Path
import numpy as np

OUT = Path("modules/design/shared/src/test/scala/scalafim/fmri/design/fixtures/DesignDiagnosticsFixture.scala")

u = np.array([0.5, -0.5, 0.5, -0.5])
v = np.array([0.5, 0.5, -0.5, -0.5])
w = np.array([0.5, -0.5, -0.5, 0.5])
x = 0.6 * u + 0.8 * v
full = np.column_stack([u, x, w])
deficient = np.column_stack([np.ones(4), u, u, w])
near_collinear = np.column_stack([
    np.array([-1.0, -1.0, 1.0, 1.0]),
    np.array([-0.999999999, -1.000000001, 0.999999999, 1.000000001]),
])

def vif(column: int) -> float:
    y = full[:, column]
    others = np.delete(full, column, axis=1)
    r = y - others @ np.linalg.pinv(others) @ y
    return 1.0 / (1.0 - (1.0 - r @ r / (y @ y)))

vifs = [vif(i) for i in range(3)]
r2 = 1.0 - np.sum((u - x * (x @ u / (x @ x))) ** 2) / (u @ u)
beta = np.linalg.pinv(np.column_stack([x, w])) @ u
near_residual = near_collinear[:, 0] - near_collinear[:, 1] * (
    near_collinear[:, 1] @ near_collinear[:, 0] / (near_collinear[:, 1] @ near_collinear[:, 1])
)
near_vif = (near_collinear[:, 0] @ near_collinear[:, 0]) / (near_residual @ near_residual)

def scala_rows(a: np.ndarray) -> str:
    return ",\n    ".join(f"{value:.17g}" for value in a.ravel())

OUT.write_text(f'''package scalafim.fmri.design.fixtures

// Generated by tools/fixtures/generate_design_diagnostics.py with NumPy {np.__version__}. Do not edit by hand.
object DesignDiagnosticsFixture:
  val fullRank: Array[Double] = Array(
    {scala_rows(full)}
  )
  val deficient: Array[Double] = Array(
    {scala_rows(deficient)}
  )
  val expectedVif: Vector[Double] = Vector({", ".join(f"{value:.17g}" for value in vifs)})
  val expectedBlockR2: Double = {r2:.17g}
  val expectedJointCoefficient: Double = {beta[0]:.17g}

  // Independent NumPy projection fixture: u and almostU differ by one
  // orthogonal direction at 1e-9. Their finite VIF is about 1e18, which
  // detects implementations that recover it as `1 / (1 - R²)`.
  val nearCollinear: Array[Double] = Array(
    {scala_rows(near_collinear)}
  )
  val expectedNearCollinearVif: Double = {near_vif:.17g}
''')
