"""Regenerate the independent SPM12 informed-basis oracle for SpmInformedBasisFixture.

Run with: uv run --with numpy==2.4.3 --with scipy==1.17.1 python tools/fixtures/generate_spm_informed_basis.py

This re-implements, in NumPy, the parts of SPM12 used by spm_get_bf.m for
'hrf (with time derivative)' and 'hrf (with time and dispersion derivatives)':

* spm_Gpdf(x, h, l): gamma density with shape h and rate l, zero for x <= 0
  when h > 1;
* spm_hrf(RT, P, T): parameters p = [6 16 1 1 6 0 32], fine bin dt = RT / T,
  u = 0:ceil(p7/dt) - p6/dt, hrf = Gpdf(u, p1/p3, dt/p3) - Gpdf(u, p2/p4, dt/p4)/p5,
  subsampled at (0:floor(p7/RT)) * T + 1 and divided by its sum;
* spm_get_bf: bf = spm_hrf(dt, [], T) with dt = TR / T (xBF.dt), the temporal
  column (bf - spm_hrf(dt, p with p6 + 1)) / 1, the dispersion column
  (bf - spm_hrf(dt, p with p3 + 0.01)) / 0.01, then spm_orth(bf);
* spm_orth(X) (default 'pad'): serial X(:, i) - x * (pinv(x) * X(:, i)) against
  all retained earlier columns, no mean removal.

The Scala kernels are in fmrihrf continuous units, so they equal these columns
up to one common positive factor (the canonical sample sum); the test estimates
that factor from the canonical column only.
"""

from pathlib import Path

import numpy as np
from scipy.special import gammaln

OUT = Path("modules/hrf/shared/src/test/scala/scalafim/fmri/hrf/fixtures/SpmInformedBasisFixture.scala")
# The same TR = 2 s spm_get_bf kernel, for design-column tests in the design
# module (which cannot see hrf test fixtures).
DESIGN_OUT = Path("modules/design/shared/src/test/scala/scalafim/fmri/design/fixtures/SpmInformedKernelFixture.scala")
T = 16


def spm_gpdf(x, h, l):
    x = np.asarray(x, dtype=float)
    f = np.zeros_like(x)
    q = x > 0
    f[q] = np.exp((h - 1.0) * np.log(x[q]) + h * np.log(l) - l * x[q] - gammaln(h))
    if h == 1.0:
        f[x == 0] = l
    return f


def spm_hrf(rt, p_override=None, fmri_t=T):
    p = np.array([6.0, 16.0, 1.0, 1.0, 6.0, 0.0, 32.0])
    if p_override is not None:
        for index, value in p_override.items():
            p[index] = value
    dt = rt / fmri_t
    u = np.arange(0, int(np.ceil(p[6] / dt)) + 1) - p[5] / dt
    hrf = spm_gpdf(u, p[0] / p[2], dt / p[2]) - spm_gpdf(u, p[1] / p[3], dt / p[3]) / p[4]
    hrf = hrf[np.arange(0, int(np.floor(p[6] / rt)) + 1) * fmri_t]
    return hrf / hrf.sum()


def spm_orth(x):
    n, m = x.shape
    keep = [j for j in range(m) if np.any(x[:, j])]
    x = x[:, keep]
    rank = np.linalg.matrix_rank(x)
    out = x[:, :1]
    kept = [0]
    for i in range(1, x.shape[1]):
        d = x[:, i] - out @ (np.linalg.pinv(out) @ x[:, i])
        if np.sum(np.abs(d)) > np.exp(-32):
            out = np.column_stack([out, d])
            kept.append(i)
        if len(kept) == rank:
            break
    padded = np.zeros((n, m))
    padded[:, [keep[k] for k in kept]] = out
    return padded


def spm_get_bf(tr, columns):
    dt = tr / T
    bf = spm_hrf(dt)
    cols = [bf]
    if columns >= 2:
        cols.append((bf - spm_hrf(dt, {5: 1.0})) / 1.0)
    if columns >= 3:
        cols.append((bf - spm_hrf(dt, {2: 1.01})) / 0.01)
    return spm_orth(np.column_stack(cols))


def literal(values):
    return ",\n    ".join(f"{value:.17g}" for value in np.asarray(values).ravel())


cases = [("tr2", 2.0, 3), ("tr072", 0.72, 2)]
blocks = []
for name, tr, columns in cases:
    bf = spm_get_bf(tr, columns)
    blocks.append(f"""  /** spm_get_bf at TR = {tr} s, {columns} columns, row-major ({bf.shape[0]} x {columns}). */
  val {name}Tr: Double = {tr!r}
  val {name}Columns: Int = {columns}
  val {name}Rows: Int = {bf.shape[0]}
  val {name}: Array[Double] = Array(
    {literal(bf)}
  )
""")

OUT.write_text(
    "package scalafim.fmri.hrf.fixtures\n\n"
    f"// Generated by tools/fixtures/generate_spm_informed_basis.py with NumPy {np.__version__}.\n"
    "// Independent re-implementation of SPM12 spm_get_bf / spm_hrf / spm_orth; do not edit.\n"
    "object SpmInformedBasisFixture:\n" + "\n".join(blocks)
)

design_tr, design_columns = 2.0, 3
design_bf = spm_get_bf(design_tr, design_columns)
DESIGN_OUT.write_text(
    "package scalafim.fmri.design.fixtures\n\n"
    f"// Generated by tools/fixtures/generate_spm_informed_basis.py with NumPy {np.__version__}.\n"
    "// Independent re-implementation of SPM12 spm_get_bf / spm_hrf / spm_orth; do not edit.\n"
    "object SpmInformedKernelFixture:\n"
    f"""  /** spm_get_bf kernel at TR = {design_tr} s, {design_columns} columns, on SPM's
    * microtime grid k * TR / {T} for k = 0 .. {design_bf.shape[0] - 1} (0 .. 32 s), row-major. */
  val tr: Double = {design_tr!r}
  val microtimeResolution: Int = {T}
  val columns: Int = {design_columns}
  val rows: Int = {design_bf.shape[0]}
  val kernel: Array[Double] = Array(
    {literal(design_bf)}
  )
"""
)
