"""Independent NumPy oracle for ContrastDiagnosticsFixture.

Run from the repository root:

    python3 tools/fixtures/generate_contrast_diagnostics.py

The script reads the frozen raw audit matrices from
DurableContrastMatrixFixture.scala (itself generated by
extract_durable_contrast_matrices.py) and recomputes every expected value with
textbook NumPy formulas (pseudo-inverse covariance, QR row bases, eigh). It
shares no code with the Scala implementation. The emitted Scala file is the
only place the expected values live; regeneration is byte-identical for a
given NumPy version.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np

FIXTURES = Path("modules/design/shared/src/test/scala/scalafim/fmri/design/fixtures")
DURABLE = FIXTURES / "DurableContrastMatrixFixture.scala"
OUT = FIXTURES / "ContrastDiagnosticsFixture.scala"


# --- frozen durable matrices -------------------------------------------------

def parse_durable(path: Path) -> dict[str, dict]:
    text = path.read_text()
    blocks = re.split(r"\n(?=  val )", text)
    parsed: dict[str, dict] = {}
    for block in blocks:
        header = re.match(r"  val (\w+): (Vector\[AuditRun\]|AuditCase)", block)
        if header is None:
            continue
        runs = []
        for match in re.finditer(r'AuditRun\((\d+), (\d+), Vector\(((?:"[^"]*"(?:, )?)*)\)\)', block):
            rows, cols = int(match.group(1)), int(match.group(2))
            chunks = [json.loads(chunk) for chunk in re.findall(r'"[^"]*"', match.group(3))]
            values = np.array([float(value) for chunk in chunks for value in chunk.split(",")])
            runs.append(values.reshape(rows, cols))
        contrast = []
        tail = block.split("\n  ), ", 1)
        if len(tail) == 2:
            contrast = [np.array([float(v) for v in row.split(",")]) for row in re.findall(r"Array\(([^)]*)\)", tail[1])]
        parsed[header.group(1)] = {"runs": runs, "contrast": contrast}
    return parsed


# --- independent formulas ----------------------------------------------------

def unscaled_covariance(x: np.ndarray) -> np.ndarray:
    """(X'X)+ formed as X+ X+' to avoid squaring the condition number."""
    pinv = np.linalg.pinv(x)
    return pinv @ pinv.T


def estimable(x: np.ndarray, rows: np.ndarray) -> bool:
    projector = np.linalg.pinv(x) @ x
    return bool(np.all(np.linalg.norm(rows - rows @ projector, axis=1) <= 1e-8 * np.linalg.norm(rows, axis=1)))


def row_basis(rows: np.ndarray) -> np.ndarray:
    """Orthonormal basis (as rows) of the contrast row space via QR."""
    rows = rows / np.linalg.norm(rows, axis=1, keepdims=True)
    rank = np.linalg.matrix_rank(rows)
    q, r = np.linalg.qr(rows.T)
    assert rank == rows.shape[0], "oracle cases use linearly independent rows"
    return q.T


def padded(rows: np.ndarray, columns: int) -> np.ndarray:
    """Contrast columns are matched by position name (audit-0, audit-1, ...);
    a run with extra trailing columns carries zero weight on them."""
    rows = np.atleast_2d(rows)
    return np.column_stack([rows, np.zeros((rows.shape[0], columns - rows.shape[1]))])


def fixed_effects_t(runs: list[np.ndarray], weights: np.ndarray, sigmas: list[float]) -> float:
    information = 0.0
    for x, sigma in zip(runs, sigmas):
        weights = padded(weights, x.shape[1])[0]
        assert estimable(x, weights[None, :])
        information += 1.0 / (sigma * sigma * float(weights @ unscaled_covariance(x) @ weights))
    return 1.0 / information


def fixed_effects_f(runs: list[np.ndarray], rows: np.ndarray, sigmas: list[float]) -> float:
    information = np.zeros((rows.shape[0], rows.shape[0]))
    for x, sigma in zip(runs, sigmas):
        # The QR basis of the padded rows is the zero-padded basis, so every
        # run shares one hypothesis coordinate system.
        basis = row_basis(padded(rows, x.shape[1]))
        assert estimable(x, basis)
        information += np.linalg.inv(sigma * sigma * basis @ unscaled_covariance(x) @ basis.T)
    return float(np.sqrt(np.max(np.linalg.eigvalsh(np.linalg.inv(information)))))


def residualized(task: np.ndarray, nuisance: np.ndarray) -> np.ndarray:
    return task - nuisance @ np.linalg.pinv(nuisance) @ task


# --- small hand-built designs ------------------------------------------------

# [intercept, u, u, w], with u and w orthogonal and centred.
duplicate_design = np.array([
    [1.0, 0.5, 0.5, 0.5],
    [1.0, -0.5, -0.5, -0.5],
    [1.0, 0.5, 0.5, -0.5],
    [1.0, -0.5, -0.5, 0.5],
    [1.0, 0.0, 0.0, 0.0],
])

# First run has task exactly equal to its nuisance column. The second has one
# unit-norm task direction orthogonal to the intercept nuisance.
singular_task_run = np.array([[1.0, 1.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]])
informative_task_run = np.array([[1.0, 0.0], [0.0, 1.0], [0.0, 0.0], [0.0, 0.0]])

# Two runs [task1, task2, intercept, drift] for concatenated task F.
concat_run_one = np.array([
    [1.0, 0.0, 1.0, -2.5],
    [0.0, 1.0, 1.0, -1.5],
    [1.0, 1.0, 1.0, -0.5],
    [0.0, 0.0, 1.0, 0.5],
    [2.0, 0.0, 1.0, 1.5],
    [0.0, 3.0, 1.0, 2.5],
])
concat_run_two = np.array([
    [0.5, 1.0, 1.0, -1.5],
    [1.0, 0.0, 1.0, -0.5],
    [0.0, 2.0, 1.0, 0.5],
    [1.5, 0.5, 1.0, 1.5],
])
concat_rows = np.array([[1.0, 0.0], [1.0, -1.0]])

# High-pass pair: [task1, task2, intercept] without, plus one cosine with.
high_pass_n = 8
high_pass_without = np.array([
    [1.0, 0.0, 1.0],
    [1.0, 0.5, 1.0],
    [0.0, 1.0, 1.0],
    [0.0, 1.0, 1.0],
    [1.0, 0.0, 1.0],
    [0.5, 0.0, 1.0],
    [0.0, 1.0, 1.0],
    [0.0, 0.0, 1.0],
])
cosine = np.cos(np.pi * (np.arange(high_pass_n) + 0.5) / high_pass_n)
high_pass_with = np.column_stack([high_pass_without, cosine])
high_pass_rows = np.array([[1.0, 0.0], [0.0, 1.0]])


def high_pass_pinned() -> tuple[float, float]:
    rows_without = np.column_stack([high_pass_rows, np.zeros((2, 1))])
    rows_with = np.column_stack([high_pass_rows, np.zeros((2, 2))])
    basis_without = row_basis(rows_without)
    basis_with = np.column_stack([basis_without, np.zeros((basis_without.shape[0], 1))])
    assert np.allclose(row_basis(rows_with) @ row_basis(rows_with).T, np.eye(2))
    c0 = basis_without @ unscaled_covariance(high_pass_without) @ basis_without.T
    c1 = basis_with @ unscaled_covariance(high_pass_with) @ basis_with.T
    values, vectors = np.linalg.eigh(c0)
    assert values[-1] - values[-2] > 1e-6 * values[-1], "worst direction must be unique"
    worst = vectors[:, -1]
    return float(worst @ c1 @ worst), float(values[-1])


def concatenated_f() -> tuple[float, float]:
    information = np.zeros((2, 2))
    for run in (concat_run_one, concat_run_two):
        residual = residualized(run[:, :2], run[:, 2:])
        information += residual.T @ residual
    covariance = np.linalg.inv(information)
    basis = row_basis(concat_rows)
    worst = float(np.sqrt(np.max(np.linalg.eigvalsh(basis @ covariance @ basis.T))))
    # Weighted concatenation with run sigmas (0.5, 2.0).
    weighted = np.zeros((2, 2))
    for run, sigma in ((concat_run_one, 0.5), (concat_run_two, 2.0)):
        residual = residualized(run[:, :2], run[:, 2:]) / sigma
        weighted += residual.T @ residual
    weighted_worst = float(np.sqrt(np.max(np.linalg.eigvalsh(basis @ np.linalg.inv(weighted) @ basis.T))))
    return worst, weighted_worst


def scala_double(value: float) -> str:
    text = repr(float(value))
    return text if any(c in text for c in ".eE") else text + ".0"


def scala_array(matrix: np.ndarray, indent: str = "    ") -> str:
    lines = [", ".join(scala_double(value) for value in row) for row in np.atleast_2d(matrix)]
    return "Array(\n" + ",\n".join(indent + line for line in lines) + "\n  )"


def main() -> None:
    durable = parse_durable(DURABLE)
    gamble = durable["gamble"]["runs"][0]
    spikes = np.zeros((gamble.shape[0], 8))
    spikes[np.arange(8), np.arange(8)] = 1.0
    gamble_rank = int(np.linalg.matrix_rank(gamble))
    spiked_rank = int(np.linalg.matrix_rank(np.column_stack([gamble, spikes])))

    f_cases = {}
    for name in ("block", "stop", "dense"):
        case = durable[name]
        f_cases[name] = fixed_effects_f(case["runs"], np.array(case["contrast"]), [1.0] * len(case["runs"]))
    dms = durable["dms"]
    dms_weights = np.array(dms["contrast"][0])
    dms_se = float(np.sqrt(fixed_effects_t(dms["runs"], dms_weights, [1.0, 1.0])))
    dms_df = [int(x.shape[0] - np.linalg.matrix_rank(x)) for x in dms["runs"]]
    weighted_sigmas = [0.8, 1.7]
    weighted_dms_variance = fixed_effects_t(dms["runs"], dms_weights, weighted_sigmas)
    block = durable["block"]
    weighted_block_se = fixed_effects_f(block["runs"], np.array(block["contrast"]), weighted_sigmas)

    dup_rank = [int(np.linalg.matrix_rank(x)) for x in durable["dupState"]["runs"]]
    dup_nullity = [int(x.shape[1] - r) for x, r in zip(durable["dupState"]["runs"], dup_rank)]
    dup2_nullity = [int(x.shape[1] - np.linalg.matrix_rank(x)) for x in durable["dup2State"]["runs"]]

    concat_worst, concat_weighted_worst = concatenated_f()
    high_with, high_without = high_pass_pinned()

    OUT.write_text(f'''package scalafim.fmri.design.fixtures

// Generated by tools/fixtures/generate_contrast_diagnostics.py with NumPy {np.__version__}.
// Do not edit by hand. Expected values are independent NumPy recomputations
// (pseudo-inverse covariances, QR row bases, eigh) from the frozen matrices in
// DurableContrastMatrixFixture and the small designs below.
object ContrastDiagnosticsFixture:
  /** Oracle values recomputed from the frozen m2b/m3/m4b audit matrices. */
  object DurableAudit:
    val gambleRank: Int = {gamble_rank}
    val gambleRankWithEightSpikes: Int = {spiked_rank}
    val blockFixedEffectsFWorstSe: Double = {scala_double(f_cases["block"])}
    val stopFixedEffectsFWorstSe: Double = {scala_double(f_cases["stop"])}
    val denseFixedEffectsFWorstSe: Double = {scala_double(f_cases["dense"])}
    val dmsFixedEffectsSe: Double = {scala_double(dms_se)}
    val dmsResidualDf: Vector[Int] = Vector({", ".join(str(v) for v in dms_df)})
    val dupStateRank: Vector[Int] = Vector({", ".join(str(v) for v in dup_rank)})
    val dupStateNullity: Vector[Int] = Vector({", ".join(str(v) for v in dup_nullity)})
    val dup2StateNullity: Vector[Int] = Vector({", ".join(str(v) for v in dup2_nullity)})
    /** Run sigmas for the heterogeneous weighted combinations below. */
    val weightedSigmas: Vector[Double] = Vector({", ".join(scala_double(v) for v in weighted_sigmas)})
    val weightedDmsFixedEffectsVariance: Double = {scala_double(weighted_dms_variance)}
    val weightedBlockFixedEffectsFWorstSe: Double = {scala_double(weighted_block_se)}

  // [intercept, u, u, w], with u and w orthogonal and centred.
  val duplicateDesign: Array[Double] = {scala_array(duplicate_design)}

  // First run has task exactly equal to its nuisance column. The second has
  // one unit-norm task direction orthogonal to the intercept nuisance.
  val singularTaskRun: Array[Double] = {scala_array(singular_task_run)}
  val informativeTaskRun: Array[Double] = {scala_array(informative_task_run)}

  // Concatenated task F: two runs of [task1, task2, intercept, drift]; the F
  // rows over (task1, task2) are {concat_rows.tolist()}.
  val concatenatedRunOne: Array[Double] = {scala_array(concat_run_one)}
  val concatenatedRunTwo: Array[Double] = {scala_array(concat_run_two)}
  val concatenatedFRows: Vector[Vector[Double]] = Vector({", ".join("Vector(" + ", ".join(scala_double(v) for v in row) + ")" for row in concat_rows)})
  val concatenatedFWorstSe: Double = {scala_double(concat_worst)}
  /** Run sigmas (0.5, 2.0). */
  val concatenatedWeightedFWorstSe: Double = {scala_double(concat_weighted_worst)}

  // High-pass pair: [task1, task2, intercept] and the same plus one cosine.
  // Variances are along the unique worst direction of the without-cosine F
  // covariance for rows task1 and task2.
  val highPassWithout: Array[Double] = {scala_array(high_pass_without)}
  val highPassWith: Array[Double] = {scala_array(high_pass_with)}
  val highPassWithVariance: Double = {scala_double(high_with)}
  val highPassWithoutVariance: Double = {scala_double(high_without)}
''')


if __name__ == "__main__":
    main()
