"""Regenerate Gaussian binary64-input precision fixtures with mpmath 1.3.0."""
from pathlib import Path
import mpmath as mp

mp.mp.dps = 90
points = [
    (7.49004329853202, 0.3926858591878316),
    (7.490043325179883, 0.39268587912057873),
    (5.119960070064869, 0.3496555300787389),
    (5.119960057433808, 0.34965553914398373),
]

def value(t, tau, v):
    return mp.exp(-mp.mpf('0.5') * (t - tau) ** 2 * mp.exp(-2 * v))

lines = [
    'package scalafim.fmri.hrf.family', '',
    '// Generated by tools/hrf/generate_gaussian_precision_oracle.py; mpmath 1.3.0, 90 digits.',
    '// Inputs are exact binary64 values; derivatives come from independent high-precision differentiation.',
    'private[family] object GaussianPrecisionFixtures:',
    '  final case class Sample(index: Int, jet: Vector[Double])',
    '  final case class Case(tau: Double, logSd: Double, samples: Vector[Sample])',
    '  val cases: Vector[Case] = Vector(',
]
for tau, v in points:
    peak = round(tau * 10)
    indices = sorted(set([0, 31, 32, 63, 64, 95, 96, 127, 128, 159, 160, 200, 240] + list(range(peak - 3, peak + 4))))
    lines.append(f'    Case({tau!r}, {v!r}, Vector(')
    for i in indices:
        t, x, y = mp.mpf(i * 0.1), mp.mpf(tau), mp.mpf(v)
        f = lambda a, b: value(t, a, b)
        orders = [(0, 0), (1, 0), (0, 1), (2, 0), (1, 1), (0, 2)]
        jet = [repr(float(mp.diff(f, (x, y), order))) for order in orders]
        lines.append(f'      Sample({i}, Vector({", ".join(jet)})),')
    lines[-1] = lines[-1].rstrip(',')
    lines.append('    )),')
lines[-1] = lines[-1].rstrip(',')
lines.append('  )')
root = Path(__file__).resolve().parents[2]
path = root / 'modules/hrf/shared/src/test/scala/scalafim/fmri/hrf/family/GaussianPrecisionFixtures.scala'
path.write_text('\n'.join(lines) + '\n')
print(path)
