package scalafim.fmri.motion.fixtures

import scalafim.fmri.motion.RigidPose

object VolreggerFixtures:
  final case class CoreFixture(
      metadata: Map[String, String],
      values: Map[String, Vector[Double]]
  ):
    def string(key: String): String =
      metadata.getOrElse(key, throw new IllegalArgumentException(s"missing fixture metadata: $key"))

    def doubles(key: String): Vector[Double] =
      values.getOrElse(key, throw new IllegalArgumentException(s"missing fixture values: $key"))

  object CoreFixture:
    def parse(text: String): CoreFixture =
      val metadata = Map.newBuilder[String, String]
      val values = Map.newBuilder[String, Vector[Double]]

      text.split("\\r?\\n").foreach { rawLine =>
        val line = rawLine.trim
        if line.nonEmpty && !line.startsWith("#") then
          val eq = line.indexOf('=')
          require(eq > 0, s"fixture line must be key=value: $line")
          val key = line.substring(0, eq).trim
          val value = line.substring(eq + 1).trim
          if key.startsWith("metadata.") then metadata += key.stripPrefix("metadata.") -> value
          else values += key -> parseDoubles(value)
      }

      CoreFixture(metadata.result(), values.result())

    private def parseDoubles(value: String): Vector[Double] =
      if value.isEmpty then Vector.empty
      else
        value.split(",").toVector.map { token =>
          token.trim match
            case "NA" | "NaN" => Double.NaN
            case other => other.toDouble
        }

  val coreFixtureText: String =
    """# Generated by tools/motion/generate_volregger_fixtures.R
      |metadata.fixture_version=1
      |metadata.volregger_commit=f350a33140adc38ee860eae5efa0d8e80d1e6b94
      |metadata.generated_by=tools/motion/generate_volregger_fixtures.R
      |metadata.source_files=R/utils.R;R/transform_metrics.R;R/fd_dvars.R;R/apply_motion.R;R/estimate_motion.R;R/control.R;R/profiles.R;R/classes.R;R/reporting.R;R/cli.R;src/api_apply.cpp;src/api_estimate.cpp;src/api_spline.cpp;tests/testthat/test-synthetic-ablation-modes.R;tests/testthat/test-ic-efficacy.R;tests/testthat/test-reporting-cli.R;tests/testthat/test-external-benchmark-guardrails.R
      |metadata.profile.fast_fmri.components=capture_boost;ic_stencil;whiten;fast_native;edge_exclude;valid_template_refresh;parallel_frames;heptic_final
      |metadata.profile.fast_native_parallel.components=capture_boost;ic_stencil;whiten;fast_native;parallel_frames
      |metadata.profile.ic_stencil.components=capture_boost;ic_stencil
      |metadata.profile.ic_whiten.components=capture_boost;ic_stencil;whiten
      |metadata.profile.slice_spline.components=capture_boost;slice_spline
      |metadata.profile.fast_fmri.engine=rigid_robust
      |metadata.profile.slice_spline.engine=rigid_spline
      |metadata.spline.method=cubic_bspline_smoother
      |metadata.cli.commands=estimate;apply;run;report
      |metadata.cli.run.outputs=<prefix>_corrected.nii.gz;<prefix>_fit.rds;<prefix>_motion.tsv;<prefix>_summary.csv;<prefix>_frames.csv;<prefix>_matrices.csv;<prefix>_summary.txt;<prefix>_report.rds;<prefix>_overview.png
      |metadata.report.summary_columns=engine;components;n_frames;tx_abs_max;ty_abs_max;tz_abs_max;rx_abs_max;ry_abs_max;rz_abs_max;fd_mean;fd_p95;fd_max;dvars_mean;dvars_p95;robust_dvars_mean;robust_dvars_p95;motion_spikes;fit_failures;censor_suggested;cost_drop_mean;packet_correction_mag_mean;packet_correction_mag_max
      |metadata.report.fast_fmri.components=rigid;robust_template;valid_template_refresh;overlap_taper;capture_boost;ic_stencil;whitening
      |metadata.benchmark.required_columns=estimate_sec;apply_sec;report_sec;elapsed_sec;tsnr_ratio;disp_p95;fd_error
      |metadata.benchmark.truth_scenarios=low_motion;moderate_motion;hard_motion_plus_nuisance
      |metadata.benchmark.claim_families=truth_displacement;truth_pose;truth_matrix
      |pose=1.199999999999999956,-0.500000000000000000,0.800000000000000044,0.100000000000000006,-0.050000000000000003,0.080000000000000002
      |matrix_row_major=0.995555963731887816,-0.084489086417525852,-0.041592275174652311,1.199999999999999956,0.079814821411095277,0.991423108071215919,-0.103488236363004943,-0.500000000000000000,0.049979169270678331,0.099708650872138788,0.993760669165504318,0.800000000000000044,0.000000000000000000,0.000000000000000000,0.000000000000000000,1.000000000000000000
      |inverse_row_major=0.995555963731887594,0.079814821411095263,0.049979169270678324,-1.194743081189260092,-0.084489086417525838,0.991423108071215808,0.099708650872138760,0.517331537038927980,-0.041592275174652305,-0.103488236363004957,0.993760669165504207,-0.796841923304323130,0.000000000000000000,0.000000000000000000,0.000000000000000000,1.000000000000000000
      |fd_trace_row_major=0.00,0.00,0.00,0.00,0.00,0.00,0.50,0.00,0.00,0.01,0.00,0.00,0.50,-0.25,0.00,0.01,0.02,0.00
      |fd=0.00,1.00,1.25
      |dvars_values=1,2,5
      |dvars_raw=NA,1,3
      |robust_dvars_values=0,1,11,14
      |dvars_robust=NA,1,9,3
      |translation_summary=1,1,1,1,0,1
      |radius_fd_pose=9.3631269021804151
      |apply_edge_input=1,0,0
      |apply_edge_plus_x_clamp=1,1,0
      |apply_edge_plus_x_zero=0,1,0
      |estimator_identity_dims=5,5,3,3
      |estimator_identity_motion_row_major=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
      |estimator_identity_cost_init=0,0,0
      |estimator_identity_cost_final=0,0,0
      |estimator_identity_overlap=1,1,1
      |estimator_translation_dims=7,5,5,2
      |estimator_translation_motion_row_major=0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.7041536834737017747,-0.0136600245973531112,0.0209200742470178093,-0.0047253524520048593,-0.0839981623610547151,0.0658916938990843082
      |estimator_translation_cost_init=0.0000000000000000,1.7976374979905614
      |estimator_translation_cost_final=0.00000000000000000,0.18619187801621348
      |estimator_translation_overlap=1,1
      |spline_pose_row_major=0.00000000000000000,0.00000000000000000,0.00000000000000000,0.00000000000000000,0.00000000000000000,0.00000000000000000,3.00000000000000000,0.00000000000000000,0.00000000000000000,0.00000000000000000,0.00000000000000000,0.29999999999999999,0.00000000000000000,6.00000000000000000,0.00000000000000000,0.10000000000000001,0.00000000000000000,0.00000000000000000,0.00000000000000000,0.00000000000000000,9.00000000000000000,0.00000000000000000,0.20000000000000001,0.00000000000000000
      |spline_tr=1.25
      |spline_smooth_iter=2
      |spline_slice_times=0.00,0.50,0.25,0.75
      |spline_mb_groups=1,2,1,3
      |spline_smoothed_pose_row_major=0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,1.4166666666666667407,1.3333333333333332593,0.2500000000000000000,0.0222222222222222231,0.0055555555555555558,0.1416666666666666630,0.6666666666666666297,2.8333333333333334814,2.5000000000000000000,0.0472222222222222210,0.0555555555555555594,0.0666666666666666657,0.0000000000000000000,0.0000000000000000000,9.0000000000000000000,0.0000000000000000000,0.2000000000000000111,0.0000000000000000000
      |spline_times=0.00,1.25,2.50,3.75
      |spline_packet_offsets_slice_times=0.00,0.50,0.25,0.75
      |spline_packet_offsets_mb_groups=0.0,0.5,0.0,1.0
      |profile_fast_fmri_flags=1.000000000000000000,1.000000000000000000,1.000000000000000000,0.000000000000000000,0.000000000000000000,0.050000000000000003,1.000000000000000000
      |profile_fast_native_parallel_flags=1.000000000000000000,1.000000000000000000,1.000000000000000000,0.000000000000000000,0.000000000000000000,0.050000000000000003,1.000000000000000000
      |profile_ic_stencil_flags=1.000000000000000000,0.000000000000000000,0.000000000000000000,0.000000000000000000,0.000000000000000000,0.050000000000000003,1.000000000000000000
      |profile_ic_whiten_flags=1.000000000000000000,1.000000000000000000,0.000000000000000000,0.000000000000000000,0.000000000000000000,0.050000000000000003,1.000000000000000000
      |profile_slice_spline_flags=1.000000000000000000,1.000000000000000000,0.000000000000000000,1.000000000000000000,0.000000000000000000,0.050000000000000003,1.000000000000000000
      |ic_whiten_noninferiority_gates=1.08000000000000007,1.05000000000000004,0.14999999999999999,1.12000000000000011
      |ic_nuisance_improvement_gates=0.97999999999999998,0.94999999999999996,0.10000000000000001,1.19999999999999996
      |expanded_capture_success_gates=-1,2
      |""".stripMargin

  val coreFixture: CoreFixture =
    CoreFixture.parse(coreFixtureText)

  val translationAndYaw: RigidPose =
    RigidPose.unsafe(1.0, 2.0, 3.0, 0.0, 0.0, math.Pi / 2.0)

  val fdTrace: Vector[RigidPose] =
    Vector(
      RigidPose.identity,
      RigidPose.unsafe(0.5, 0.0, 0.0, 0.01, 0.0, 0.0),
      RigidPose.unsafe(0.5, -0.25, 0.0, 0.01, 0.02, 0.0)
    )

  val fdExpected: Vector[Double] =
    Vector(0.0, 1.0, 1.25)

  val dvarsRunValues: Vector[Double] =
    Vector(1.0, 2.0, 5.0)

  val dvarsExpected: Vector[Double] =
    Vector(Double.NaN, 1.0, 3.0)

  val robustDvarsRunValues: Vector[Double] =
    Vector(0.0, 1.0, 11.0, 14.0)

  val robustDvarsExpected: Vector[Double] =
    Vector(Double.NaN, 1.0, 9.0, 3.0)

  val estimatorDims: Vector[Int] =
    Vector(7, 5, 5)

  val estimatorTranslationX: Double =
    1.0

  val estimatorRotationZ: Double =
    0.18

  val estimatorCaptureRotationZ: Double =
    0.35
