package scalafim.fmri.motion.fixtures

import scalafim.fmri.motion.RigidPose

object VolreggerFixtures:
  final case class CoreFixture(
      metadata: Map[String, String],
      values: Map[String, Vector[Double]]
  ):
    def string(key: String): String =
      metadata.getOrElse(key, throw new IllegalArgumentException(s"missing fixture metadata: $key"))

    def doubles(key: String): Vector[Double] =
      values.getOrElse(key, throw new IllegalArgumentException(s"missing fixture values: $key"))

  object CoreFixture:
    def parse(text: String): CoreFixture =
      val metadata = Map.newBuilder[String, String]
      val values = Map.newBuilder[String, Vector[Double]]

      text.split("\\r?\\n").foreach { rawLine =>
        val line = rawLine.trim
        if line.nonEmpty && !line.startsWith("#") then
          val eq = line.indexOf('=')
          require(eq > 0, s"fixture line must be key=value: $line")
          val key = line.substring(0, eq).trim
          val value = line.substring(eq + 1).trim
          if key.startsWith("metadata.") then metadata += key.stripPrefix("metadata.") -> value
          else values += key -> parseDoubles(value)
      }

      CoreFixture(metadata.result(), values.result())

    private def parseDoubles(value: String): Vector[Double] =
      if value.isEmpty then Vector.empty
      else
        value.split(",").toVector.map { token =>
          token.trim match
            case "NA" | "NaN" => Double.NaN
            case other => other.toDouble
        }

  val coreFixtureText: String =
    """# Generated by tools/motion/generate_volregger_fixtures.R
      |metadata.fixture_version=1
      |metadata.volregger_commit=f350a33140adc38ee860eae5efa0d8e80d1e6b94
      |metadata.generated_by=tools/motion/generate_volregger_fixtures.R
      |metadata.source_files=R/utils.R;R/transform_metrics.R;R/fd_dvars.R
      |pose=1.199999999999999956,-0.500000000000000000,0.800000000000000044,0.100000000000000006,-0.050000000000000003,0.080000000000000002
      |matrix_row_major=0.995555963731887816,-0.084489086417525852,-0.041592275174652311,1.199999999999999956,0.079814821411095277,0.991423108071215919,-0.103488236363004943,-0.500000000000000000,0.049979169270678331,0.099708650872138788,0.993760669165504318,0.800000000000000044,0.000000000000000000,0.000000000000000000,0.000000000000000000,1.000000000000000000
      |inverse_row_major=0.995555963731887594,0.079814821411095263,0.049979169270678324,-1.194743081189260092,-0.084489086417525838,0.991423108071215808,0.099708650872138760,0.517331537038927980,-0.041592275174652305,-0.103488236363004957,0.993760669165504207,-0.796841923304323130,0.000000000000000000,0.000000000000000000,0.000000000000000000,1.000000000000000000
      |fd_trace_row_major=0.00,0.00,0.00,0.00,0.00,0.00,0.50,0.00,0.00,0.01,0.00,0.00,0.50,-0.25,0.00,0.01,0.02,0.00
      |fd=0.00,1.00,1.25
      |dvars_values=1,2,5
      |dvars_raw=NA,1,3
      |robust_dvars_values=0,1,11,14
      |dvars_robust=NA,1,9,3
      |translation_summary=1,1,1,1,0,1
      |radius_fd_pose=9.3631269021804151
      |apply_edge_input=1,0,0
      |apply_edge_plus_x_clamp=1,1,0
      |apply_edge_plus_x_zero=0,1,0
      |estimator_identity_dims=5,5,3,3
      |estimator_identity_motion_row_major=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
      |estimator_identity_cost_init=0,0,0
      |estimator_identity_cost_final=0,0,0
      |estimator_identity_overlap=1,1,1
      |estimator_translation_dims=7,5,5,2
      |estimator_translation_motion_row_major=0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.0000000000000000000,0.7041536834737017747,-0.0136600245973531112,0.0209200742470178093,-0.0047253524520048593,-0.0839981623610547151,0.0658916938990843082
      |estimator_translation_cost_init=0.0000000000000000,1.7976374979905614
      |estimator_translation_cost_final=0.00000000000000000,0.18619187801621348
      |estimator_translation_overlap=1,1
      |""".stripMargin

  val coreFixture: CoreFixture =
    CoreFixture.parse(coreFixtureText)

  val translationAndYaw: RigidPose =
    RigidPose.unsafe(1.0, 2.0, 3.0, 0.0, 0.0, math.Pi / 2.0)

  val fdTrace: Vector[RigidPose] =
    Vector(
      RigidPose.identity,
      RigidPose.unsafe(0.5, 0.0, 0.0, 0.01, 0.0, 0.0),
      RigidPose.unsafe(0.5, -0.25, 0.0, 0.01, 0.02, 0.0)
    )

  val fdExpected: Vector[Double] =
    Vector(0.0, 1.0, 1.25)

  val dvarsRunValues: Vector[Double] =
    Vector(1.0, 2.0, 5.0)

  val dvarsExpected: Vector[Double] =
    Vector(Double.NaN, 1.0, 3.0)

  val robustDvarsRunValues: Vector[Double] =
    Vector(0.0, 1.0, 11.0, 14.0)

  val robustDvarsExpected: Vector[Double] =
    Vector(Double.NaN, 1.0, 9.0, 3.0)

  val estimatorDims: Vector[Int] =
    Vector(7, 5, 5)

  val estimatorTranslationX: Double =
    1.0

  val estimatorRotationZ: Double =
    0.18

  val estimatorCaptureRotationZ: Double =
    0.35
