#!/usr/bin/env Rscript

# Generate HierScan parity fixtures for scalafim shared JVM/JS tests.
#
# Calls neurothresh's whole-brain step-down descent (the path hier_scan takes
# with method = "stepdown" and no parcels) on small deterministic inputs with a
# fixed null matrix, and records every significant region it reports.
#
# Usage (from the repository root):
#   Rscript tools/r-parity/generate_threshold_hierscan_fixtures.R \
#     > modules/threshold/shared/src/test/scala/scalafim/fmri/threshold/fixtures/HierScanRParityFixtures.scala

suppressMessages(library(neurothresh))

fmt_num <- function(x) paste0(formatC(x, digits = 17, format = "fg", flag = "#"), "d")
fmt_vec <- function(x) paste0("Vector(", paste(vapply(x, fmt_num, character(1)), collapse = ", "), ")")
fmt_int_vec <- function(x) paste0("Vector(", paste(as.integer(x), collapse = ", "), ")")

make_case <- function(name, dims, stat, nulls, alpha, kappa, gamma, min_voxels, prior_eta, prior = rep(1.0, prod(dims))) {
  n <- prod(dims)
  mask_idx <- seq_len(n)
  pi_vec <- neurothresh:::.prep_prior(prior, eta = prior_eta)
  grid <- neurothresh:::.index_to_grid(mask_idx, dims)
  x <- as.integer(grid[, 1]); y <- as.integer(grid[, 2]); z <- as.integer(grid[, 3])
  bbox <- neurothresh:::bbox_from_indices_cpp(mask_idx, x, y, z)
  perm_fun <- function(b) nulls[b, ]
  hits <- neurothresh:::hier_descend(
    mask_idx, bbox,
    alpha_budget = alpha,
    stat, pi_vec, x, y, z,
    perm_fun, nrow(nulls), kappa,
    gamma = gamma, min_alpha = 1e-6, min_voxels = min_voxels
  )
  hit_lines <- vapply(hits, function(h) {
    sprintf(
      "        RHit(%s, %s, %s, %s)",
      fmt_int_vec(sort(h$indices) - 1L), fmt_num(h$score), fmt_num(h$p_adj), fmt_num(h$alpha_test)
    )
  }, character(1))
  null_rows <- apply(nulls, 1, fmt_vec)
  paste0(
    "  object ", name, ":\n",
    "    val dims: Vector[Int] = ", fmt_int_vec(dims), "\n",
    "    val alpha: Double = ", fmt_num(alpha), "\n",
    "    val kappas: Vector[Double] = ", fmt_vec(kappa), "\n",
    "    val gamma: Double = ", fmt_num(gamma), "\n",
    "    val minVoxels: Int = ", min_voxels, "\n",
    "    val priorEta: Double = ", fmt_num(prior_eta), "\n",
    "    val prior: Vector[Double] = ", fmt_vec(prior), "\n",
    "    val stat: Vector[Double] = ", fmt_vec(stat), "\n",
    "    val nulls: Vector[Vector[Double]] = Vector(\n      ", paste(null_rows, collapse = ",\n      "), "\n    )\n",
    "    val hits: Vector[RHit] =\n      Vector(\n",
    if (length(hit_lines) > 0) paste(hit_lines, collapse = ",\n") else "",
    "\n      )\n"
  )
}

set.seed(20260930)
dims <- c(4L, 4L, 4L)
n <- prod(dims)
grid <- neurothresh:::.index_to_grid(seq_len(n), dims)
in_block <- grid[, 1] <= 2 & grid[, 2] <= 2 & grid[, 3] <= 2
in_edge <- grid[, 1] >= 3 & grid[, 2] >= 3 & grid[, 3] == 4

stat_block <- round(rnorm(n) * 0.5, 6)
stat_block[in_block] <- stat_block[in_block] + 3.5
stat_block[in_edge] <- stat_block[in_edge] + 2.0
nulls_block <- matrix(round(rnorm(39 * n), 6), nrow = 39)

stat_single <- round(rnorm(n) * 0.3, 6)
stat_single[1] <- 7.0
nulls_single <- matrix(round(rnorm(19 * n), 6), nrow = 19)

cat("package scalafim.fmri.threshold.fixtures\n\n")
cat("// Generated by tools/r-parity/generate_threshold_hierscan_fixtures.R with neurothresh ",
    as.character(packageVersion("neurothresh")), ". Do not edit.\n", sep = "")
cat("object HierScanRParityFixtures:\n\n")
cat("  /** One significant region: sorted 0-based mask indices, score, adjusted p, test alpha. */\n")
cat("  final case class RHit(indices: Vector[Int], score: Double, adjustedP: Double, alphaTest: Double)\n\n")
cat(make_case("BlockSignal", dims, stat_block, nulls_block, alpha = 0.2, kappa = c(1, 2), gamma = 0.5, min_voxels = 2L, prior_eta = 0.9))
cat("\n")
cat(make_case("SingleVoxel", dims, stat_single, nulls_single, alpha = 0.3, kappa = c(1), gamma = 0.5, min_voxels = 2L, prior_eta = 0.9))
cat("\n")

# Odd, unequal extents and a non-uniform prior: children have unequal sizes
# and masses, two separated signals are rejected as siblings so the
# descendant budget is split by mass, and adjusted p-values sit above the
# 1/(B + 1) floor.
dims_u <- c(5L, 3L, 4L)
n_u <- prod(dims_u)
grid_u <- neurothresh:::.index_to_grid(seq_len(n_u), dims_u)
prior_u <- round(1 + 2 * (grid_u[, 1] >= 4) + 0.5 * (grid_u[, 3] <= 2), 6)
stat_u <- round(rnorm(n_u) * 0.6, 6)
near <- grid_u[, 1] <= 2 & grid_u[, 2] <= 2 & grid_u[, 3] <= 2
far <- grid_u[, 1] >= 4 & grid_u[, 3] >= 3
stat_u[near] <- stat_u[near] + 1.6
stat_u[far] <- stat_u[far] + 1.3
nulls_u <- matrix(round(rnorm(99 * n_u), 6), nrow = 99)
cat(make_case("UnequalPrior", dims_u, stat_u, nulls_u, alpha = 0.4, kappa = c(1, 2), gamma = 0.5, min_voxels = 2L, prior_eta = 0.5, prior = prior_u))
