#!/usr/bin/env Rscript
# Actual neuroatlas merge oracle; compare canonical parcel ancestry, not its ids.
r_pkg <- Sys.getenv('NEUROATLAS_R', file.path(path.expand('~'), 'code', 'neuroatlas'))
pkgload::load_all(r_pkg, quiet = TRUE)
root <- normalizePath(getwd())
out <- file.path(root, 'modules/atlas/shared/src/test/resources/scalafim/atlas/oracle')
scala <- file.path(root, 'modules/atlas/shared/src/test/scala/scalafim/atlas/fixtures/AtlasCompositionFixture.scala')
dir.create(out, recursive = TRUE, showWarnings = FALSE)
coords <- do.call(rbind, lapply(1:2, function(x) do.call(rbind, lapply(1:2, function(y) cbind(x, y, 1:2)))))
space <- neuroim2::NeuroSpace(c(2, 2, 2), spacing = c(2, 3, 4), origin = c(-10, 5, 12))
make <- function(name, values) {
  labels <- array(0L, c(2, 2, 2))
  labels[coords] <- values
  new_atlas(name, neuroim2::NeuroVol(labels, space), ids = c(7L, 19L),
    labels = paste0(name, c('-A', '-B')), hemi = c('left', 'right'),
    cmap = matrix(1:6, 2), ref = new_atlas_ref('toy', name,
      template_space = 'MNI152NLin6Asym', coord_space = 'MNI152NLin6Asym', confidence = 'high'))
}
cases <- list(
  list(name = 'partial-overlap', first = c(7L,7L,19L,0L,0L,0L,19L,0L), second = c(0L,7L,0L,7L,19L,0L,19L,0L)),
  list(name = 'disjoint', first = c(7L,0L,19L,0L,0L,0L,19L,0L), second = c(0L,7L,0L,7L,19L,0L,0L,0L)),
  list(name = 'fully-occluded', first = c(7L,19L,19L,0L,0L,0L,0L,0L), second = c(0L,7L,7L,19L,0L,0L,0L,0L))
)
rows <- list()
for (i in seq_along(cases)) {
  c <- cases[[i]]
  a <- make('first', c$first)
  b <- make('second', c$second)
  merged <- suppressWarnings(merge_atlases(a, b))
  stopifnot(identical(neuroim2::trans(neuroim2::space(merged$atlas)), neuroim2::trans(space)))
  meta <- atlas_metadata(merged)
  stopifnot(identical(meta$parents$atlas1, atlas_metadata(a)), identical(meta$parents$atlas2, atlas_metadata(b)))
  actual <- methods::as(merged$atlas, 'array')[coords]
  # R preserves first ids and offsets the second. Record ancestry in a fixed
  # independent code: first 7/19 => 1/2, second 7/19 => 3/4, background => 0.
  map <- c('0' = 0L, '7' = 1L, '19' = 2L, '20' = 3L, '21' = 4L)
  ancestry <- unname(map[as.character(actual)])
  stopifnot(!anyNA(ancestry))
  c$ancestry <- ancestry
  cases[[i]] <- c
  rows[[i]] <- data.frame(case = c$name, x = coords[,1]-1L, y = coords[,2]-1L, z = coords[,3]-1L,
    first_label = c$first, second_label = c$second, R_label = actual, ancestry = ancestry)
}
stopifnot(identical(cases[[1]]$ancestry, c(1L,3L,2L,3L,4L,0L,4L,0L)),
  identical(cases[[2]]$ancestry, c(1L,3L,2L,3L,4L,0L,2L,0L)),
  identical(cases[[3]]$ancestry, c(1L,3L,3L,4L,0L,0L,0L,0L)))
write.table(do.call(rbind, rows), file.path(out, 'parcel-composition.tsv'), sep = '\t', quote = FALSE, row.names = FALSE)
iv <- function(x) paste0('Vector(', paste(x, collapse = ', '), ')')
q <- function(x) as.character(jsonlite::toJSON(x, auto_unbox = TRUE))
lines <- c('package scalafim.atlas.fixtures', '',
  '// Generated by tools/r-parity/generate_atlas_composition.R; do not edit.',
  'object AtlasCompositionFixture:',
  '  final case class Case(name: String, first: Vector[Int], second: Vector[Int], ancestry: Vector[Int])',
  '  val cases: Vector[Case] = Vector(')
for (i in seq_along(cases)) {
  c <- cases[[i]]
  lines <- c(lines, paste0('    Case(', q(c$name), ', ', iv(c$first), ', ', iv(c$second), ', ', iv(c$ancestry), ')',
    if (i < length(cases)) ',' else ''))
}
writeLines(c(lines, '  )'), scala)
sha <- function(path) digest::digest(file = path, algo = 'sha256')
jsonlite::write_json(list(reference = 'neuroatlas',
  commit = system2('git', c('-C', shQuote(r_pkg), 'rev-parse', 'HEAD'), stdout = TRUE),
  atlas_R_sha256 = sha(file.path(r_pkg, 'R/atlas.R')),
  constructor_sha256 = sha(file.path(r_pkg, 'R/atlas_constructor.R')),
  metadata_sha256 = sha(file.path(r_pkg, 'R/atlas_metadata.R')),
  generator_sha256 = sha(file.path(root, 'tools/r-parity/generate_atlas_composition.R')),
  tsv_sha256 = sha(file.path(out, 'parcel-composition.tsv')), scala_sha256 = sha(scala),
  R_version = R.version.string, cases = length(cases),
  ordinal_layout = 'explicit x,y,z; row-major-last-axis-fastest/v1',
  scope = 'Synthetic exact-grid second-parent precedence and parcel ancestry; R retains occluded inventory while Scala explicitly drops it. No assets, other overlap policies or generic resampling parity.'),
  file.path(out, 'parcel-composition.json'), auto_unbox = TRUE, pretty = TRUE)
message('Three actual neuroatlas merge cases passed; both parent metadata records preserved')
