#!/usr/bin/env Rscript

# Generate the independent base-R receipt for explicit modulator policies.
#
# From the ScalaFIM repository root:
#   Rscript tools/r-parity/generate_modulator_policy_receipt.R
#   python3 tools/r-parity/finalize_modulator_policy_receipt.py

if (!requireNamespace("jsonlite", quietly = TRUE)) {
  stop("jsonlite is required to generate the modulator-policy receipt", call. = FALSE)
}

out_file <- Sys.getenv(
  "MODULATOR_POLICY_RECEIPT_OUT",
  file.path("docs", "scenarios", "fixtures", "design.modulator-policies.v1.r.json")
)
scala_out <- Sys.getenv(
  "MODULATOR_POLICY_SCALA_OUT",
  file.path(
    "modules", "design", "shared", "src", "test", "scala",
    "scalafim", "fmri", "design", "fixtures", "ModulatorPolicyRFixture.scala"
  )
)

serial_residual <- function(reference, target) {
  unname(qr.resid(qr(matrix(reference, ncol = 1)), target))
}

grouped_residual <- function(reference, target, groups) {
  result <- numeric(length(target))
  for (group in unique(groups)) {
    rows <- which(groups == group)
    result[rows] <- serial_residual(reference[rows], target[rows])
  }
  result
}

whole_x <- c(1, 2, 3, 4, 5, 6)
whole_y <- c(1, 5, 6, 9, 9, 12)
cell_x <- c(1, 2, 1, 2)
cell_y <- c(1, 7, 5, 5)
cells <- c("A", "A", "B", "B")
degenerate_y <- 2 * whole_x

inputs <- list(
  whole_term = list(x = whole_x, y = whole_y),
  within_cells = list(x = cell_x, y = cell_y, cell = cells),
  degenerate = list(x = whole_x, y = degenerate_y)
)
outputs <- list(
  whole_term_residual = serial_residual(whole_x, whole_y),
  within_cells_residual = grouped_residual(cell_x, cell_y, cells),
  degenerate_residual = serial_residual(whole_x, degenerate_y)
)

source <- list(
  r_version = as.character(getRversion()),
  stats_version = as.character(utils::packageVersion("stats")),
  producer = "tools/r-parity/generate_modulator_policy_receipt.R",
  reference = "base R qr and qr.resid"
)
accepted_differences <- c(
  "R fmridesign does not implicitly apply ScalaFIM ordered modulator policies; base-R QR supplies only the independent numerical reference.",
  "R model-frame na.action defaults are not used; ScalaFIM missing-value behavior is selected explicitly by MissingValuePolicy."
)
receipt <- list(
  schema_version = "scalafim-r-policy-fixture/v1",
  producer_command = "LC_ALL=C LANG=C Rscript tools/r-parity/generate_modulator_policy_receipt.R && python3 tools/r-parity/finalize_modulator_policy_receipt.py",
  accepted_differences = accepted_differences,
  conventions = list(
    dtype = "float64",
    json_encoding = "sorted-key UTF-8 JSON",
    orthogonalization = "ordered residualization without an implicit intercept",
    grouping = "independent QR residualization within each declared cell",
    missing_values = "no R na.action policy is imported into ScalaFIM"
  ),
  hashes = list(inputs_sha256 = "", outputs_sha256 = ""),
  source = source
)
payload <- list(
  schema_version = "scalafim-r-policy-fixture/v1",
  scenario_id = "design.modulator-policies.v1",
  inputs = inputs,
  outputs = outputs,
  source = source,
  receipt = receipt
)

scala_string <- function(value) {
  paste0("\"", gsub("\\\\", "\\\\\\\\", gsub("\"", "\\\\\"", value)), "\"")
}
scala_number <- function(value) {
  if (abs(value) < 5e-16) "0.0" else sprintf("%.17g", value)
}
scala_vector <- function(values, render) {
  if (length(values) == 0) "Vector.empty"
  else paste0("Vector(", paste(vapply(values, render, character(1)), collapse = ", "), ")")
}
scala_doubles <- function(values) scala_vector(as.numeric(values), scala_number)
scala_strings <- function(values) scala_vector(as.character(values), scala_string)

dir.create(dirname(out_file), recursive = TRUE, showWarnings = FALSE)
jsonlite::write_json(payload, out_file, auto_unbox = TRUE, digits = 17, pretty = TRUE)
message("wrote ", out_file)

dir.create(dirname(scala_out), recursive = TRUE, showWarnings = FALSE)
writeLines(
  c(
    "package scalafim.fmri.design.fixtures",
    "",
    "// Generated by tools/r-parity/generate_modulator_policy_receipt.R from base R QR.",
    "object ModulatorPolicyRFixture:",
    paste0("  val wholeX: Vector[Double] = ", scala_doubles(whole_x)),
    paste0("  val wholeY: Vector[Double] = ", scala_doubles(whole_y)),
    paste0("  val wholeResidual: Vector[Double] = ", scala_doubles(outputs$whole_term_residual)),
    paste0("  val cellX: Vector[Double] = ", scala_doubles(cell_x)),
    paste0("  val cellY: Vector[Double] = ", scala_doubles(cell_y)),
    paste0("  val cells: Vector[String] = ", scala_strings(cells)),
    paste0("  val cellResidual: Vector[Double] = ", scala_doubles(outputs$within_cells_residual)),
    paste0("  val degenerateY: Vector[Double] = ", scala_doubles(degenerate_y)),
    paste0("  val degenerateResidual: Vector[Double] = ", scala_doubles(outputs$degenerate_residual)),
    paste0("  val acceptedDifferences: Vector[String] = ", scala_strings(accepted_differences))
  ),
  scala_out
)
message("wrote ", scala_out)
