#!/usr/bin/env Rscript
# Independent neuroatlas alignment oracle. No asset downloads or Scala code.
r_pkg <- Sys.getenv('NEUROATLAS_R', file.path(path.expand('~'), 'code', 'neuroatlas'))
pkgload::load_all(r_pkg, quiet = TRUE)
root <- normalizePath(getwd())
out <- file.path(root, 'modules/atlas/shared/src/test/resources/scalafim/atlas/oracle')
scala <- file.path(root, 'modules/atlas/shared/src/test/scala/scalafim/atlas/fixtures/ParcelAlignmentFixture.scala')
dir.create(out, recursive = TRUE, showWarnings = FALSE)
ids <- c(1L, 180L, 181L, 360L)
volume_keys <- c('R_V1_ROI', 'R_p24_ROI', 'L_V1_ROI', 'L_p24_ROI')
surface_keys <- c('L_V1_ROI', 'L_p24_ROI', 'R_V1_ROI', 'R_p24_ROI')
make_atlas <- function(keys, representation, convention) {
  x <- list(name = 'Alignment oracle', ids = ids,
            roi_metadata = data.frame(id = ids, label_full = keys),
            atlas_ref = new_atlas_ref('glasser', 'HCP-MMP1.0',
              representation = representation,
              template_space = if (representation == 'volume') 'MNI152' else 'fsaverage',
              coord_space = if (representation == 'volume') 'MNI152' else 'fsaverage',
              id_convention = convention))
  class(x) <- 'atlas'
  x
}
volume <- make_atlas(volume_keys, 'volume', 'hcp_R_first')
surface <- make_atlas(surface_keys, 'surface', 'surfatlas_L_first')
cases <- list(
  list(name = 'volume-to-surface', target = 'surface', keys = rev(volume_keys), values = rev(ids), partial = FALSE),
  list(name = 'surface-to-volume', target = 'volume', keys = surface_keys[c(3, 1, 4, 2)], values = ids[c(3, 1, 4, 2)], partial = FALSE),
  list(name = 'partial', target = 'surface', keys = volume_keys[c(1, 3)], values = c(11, 33), partial = TRUE),
  list(name = 'duplicate', target = 'surface', keys = c(volume_keys, volume_keys[1]), values = c(ids, 999), partial = FALSE),
  list(name = 'unknown', target = 'surface', keys = c(volume_keys, 'L_unknown_ROI'), values = c(ids, 999), partial = FALSE),
  list(name = 'missing', target = 'surface', keys = volume_keys[-1], values = ids[-1], partial = FALSE)
)
rows <- list()
for (i in seq_along(cases)) {
  x <- cases[[i]]
  target <- if (x$target == 'surface') surface else volume
  result <- tryCatch(align_parcel_values(target,
    data.frame(label_full = x$keys, value = x$values), value,
    by = 'label_full', allow_partial = x$partial), error = identity)
  if (inherits(result, 'error')) {
    x$outcome <- class(result)[grepl('^neuroatlas_error_', class(result))][1]
    x$expected <- numeric()
  } else {
    x$outcome <- 'pass'
    x$expected <- as.numeric(result)
  }
  x$target_keys <- target$roi_metadata$label_full
  cases[[i]] <- x
  rows[[i]] <- data.frame(case = x$name, target = x$target, outcome = x$outcome,
    input_keys = paste(x$keys, collapse = ';'), input_values = paste(x$values, collapse = ';'),
    target_keys = paste(x$target_keys, collapse = ';'), expected = paste(x$expected, collapse = ';'))
}
wrong <- tryCatch(align_parcel_values(surface,
  data.frame(id = ids, value = ids, id_convention = 'hcp_R_first'), value, by = 'id'), error = identity)
stopifnot(inherits(wrong, 'neuroatlas_error_id_convention'))
stopifnot(identical(cases[[1]]$expected, c(181, 360, 1, 180)))
stopifnot(identical(cases[[4]]$outcome, 'neuroatlas_error_duplicate_parcel_key'))
stopifnot(identical(cases[[5]]$outcome, 'neuroatlas_error_unknown_parcel_key'))
stopifnot(identical(cases[[6]]$outcome, 'neuroatlas_error_missing_parcel_key'))
write.table(do.call(rbind, rows), file.path(out, 'parcel-alignment.tsv'), sep = '\t', quote = FALSE, row.names = FALSE, na = 'NaN')
q <- function(x) as.character(jsonlite::toJSON(x, auto_unbox = TRUE))
sv <- function(x) paste0('Vector(', paste(vapply(x, q, character(1)), collapse = ', '), ')')
dv <- function(x) paste0('Vector(', paste(ifelse(is.na(x), 'Double.NaN', sprintf('%.1f', x)), collapse = ', '), ')')
lines <- c('package scalafim.atlas.fixtures', '',
  '// Generated by tools/r-parity/generate_atlas_parcel_alignment.R; do not edit.',
  'object ParcelAlignmentFixture:',
  '  final case class Case(name: String, target: String, keys: Vector[String], values: Vector[Double], partial: Boolean, outcome: String, targetKeys: Vector[String], expected: Vector[Double])',
  '  val cases: Vector[Case] = Vector(')
for (i in seq_along(cases)) {
  x <- cases[[i]]
  lines <- c(lines, paste0('    Case(', q(x$name), ', ', q(x$target), ', ', sv(x$keys), ', ', dv(x$values), ', ', tolower(as.character(x$partial)), ', ', q(x$outcome), ', ', sv(x$target_keys), ', ', dv(x$expected), ')', if (i < length(cases)) ',' else ''))
}
lines <- c(lines, '  )')
writeLines(lines, scala)
sha <- function(path) digest::digest(file = path, algo = 'sha256')
manifest <- list(reference = 'neuroatlas',
  commit = system2('git', c('-C', shQuote(r_pkg), 'rev-parse', 'HEAD'), stdout = TRUE),
  parcel_data_sha256 = sha(file.path(r_pkg, 'R/parcel_data.R')),
  generator_sha256 = sha(file.path(root, 'tools/r-parity/generate_atlas_parcel_alignment.R')),
  tsv_sha256 = sha(file.path(out, 'parcel-alignment.tsv')),
  scala_sha256 = sha(scala), R_version = R.version.string,
  cases = length(cases), cross_convention_numeric_join = 'neuroatlas_error_id_convention',
  scope = 'Synthetic key alignment only; no acquired atlas or loader qualification')
jsonlite::write_json(manifest, file.path(out, 'parcel-alignment.json'), auto_unbox = TRUE, pretty = TRUE)
message('Generated six independent key alignment cases; unqualified cross-convention numeric IDs rejected')
