#!/usr/bin/env Rscript

# Independent active-face oracle for the nonnegative canonical-effect root.
# Reuse the canonical-effect DGP and base-R sufficient-statistic equations,
# suppress its Scala output, then enumerate every non-empty coordinate face.

invisible(capture.output(source(
  "tools/r-parity/generate_canonical_effect_fixtures.R",
  local = .GlobalEnv
)))

nonnegative_direction <- function(effect, residual, ridge_fraction) {
  ridge <- ridge_fraction * mean(diag(residual))
  regularized <- residual + diag(ridge, nrow(residual))
  dimension <- nrow(effect)
  best <- NULL

  for (mask in seq_len(2 ^ dimension - 1L)) {
    active <- which(as.logical(intToBits(mask)[seq_len(dimension)]))
    active_effect <- effect[active, active, drop = FALSE]
    active_residual <- regularized[active, active, drop = FALSE]
    upper <- chol(active_residual)
    whitened <- solve(t(upper), active_effect) %*% solve(upper)
    solved <- eigen((whitened + t(whitened)) / 2, symmetric = TRUE)
    candidate <- drop(solve(upper, solved$vectors[, 1, drop = FALSE]))
    if (all(candidate <= 1e-10)) candidate <- -candidate

    if (all(candidate >= -1e-10)) {
      candidate <- pmax(candidate, 0)
      direction <- numeric(dimension)
      direction[active] <- candidate
      direction <- direction /
        sqrt(drop(t(direction) %*% regularized %*% direction))
      root <- drop(t(direction) %*% effect %*% direction)
      if (is.null(best) || root > best$root) {
        best <- list(direction = direction, root = root)
      }
    }
  }

  stopifnot(!is.null(best), all(best$direction >= -1e-12))
  c(best, list(ridge = ridge))
}

constrained_folds <- lapply(seq_along(moments), function(held_out) {
  training <- setdiff(seq_along(moments), held_out)
  effect <- Reduce(`+`, lapply(moments[training], `[[`, "effect"))
  residual <- Reduce(`+`, lapply(moments[training], `[[`, "residual"))
  fit <- nonnegative_direction(effect, residual, ridge_fraction)
  held <- moments[[held_out]]
  heldout_root <- drop(t(fit$direction) %*% held$effect %*% fit$direction) /
    drop(t(fit$direction) %*% held$residual %*% fit$direction)
  list(
    direction = fit$direction,
    training_root = fit$root,
    ridge = fit$ridge,
    heldout_root = heldout_root
  )
})

heldout <- vapply(constrained_folds, `[[`, numeric(1), "heldout_root")
mean_root <- mean(heldout)
mean_correlation <- sqrt(mean_root / (1 + mean_root))

cat("package scalafim.fmri.mvpa\n\n")
cat("object ConstrainedCanonicalReferenceFixtures:\n")
cat("  final case class Fold(\n")
cat("      direction: Vector[Double],\n")
cat("      trainingRoot: Double,\n")
cat("      ridge: Double,\n")
cat("      heldOutRoot: Double\n")
cat("  )\n\n")
cat("  /** Independent active-face base-R oracle generated by tools/r-parity/generate_constrained_canonical_fixtures.R.\n")
cat("    */\n")
cat("  val folds: Vector[Fold] = Vector(\n")
for (index in seq_along(constrained_folds)) {
  fold <- constrained_folds[[index]]
  suffix <- if (index < length(constrained_folds)) "," else ""
  cat("    Fold(\n")
  cat("      ", fmt_vec(fold$direction), ",\n", sep = "")
  cat("      ", fmt_num(fold$training_root), ",\n", sep = "")
  cat("      ", fmt_num(fold$ridge), ",\n", sep = "")
  cat("      ", fmt_num(fold$heldout_root), "\n", sep = "")
  cat("    )", suffix, "\n", sep = "")
}
cat("  )\n\n")
cat("  val meanHeldOutRoot: Double = ", fmt_num(mean_root), "\n", sep = "")
cat(
  "  val rootToCorrelationOfMean: Double = ",
  fmt_num(mean_correlation),
  "\n",
  sep = ""
)
