#!/usr/bin/env Rscript
# Independent neuroatlas parcel_volume oracle, with explicit coordinate ordering.
r_pkg <- Sys.getenv('NEUROATLAS_R', file.path(path.expand('~'), 'code', 'neuroatlas'))
pkgload::load_all(r_pkg, quiet = TRUE)
root <- normalizePath(getwd())
out <- file.path(root, 'modules/atlas/shared/src/test/resources/scalafim/atlas/oracle')
scala <- file.path(root, 'modules/atlas/shared/src/test/scala/scalafim/atlas/fixtures/ParcelExpansionFixture.scala')
dir.create(out, recursive = TRUE, showWarnings = FALSE)
ids <- c(7L, 19L, 42L)
labels <- array(c(0L, 7L, 7L, 19L, 19L, 42L, 42L, 0L), c(2, 2, 2))
space <- neuroim2::NeuroSpace(dim = dim(labels), spacing = c(2, 3, 4), origin = c(-10, 5, 12))
atlas <- list(name = 'Expansion oracle', ids = ids, labels = c('A', 'B', 'C'),
  orig_labels = c('lh_A', 'rh_B', 'lh_C'), hemi = c('left', 'right', 'left'),
  atlas = neuroim2::NeuroVol(labels, space = space))
class(atlas) <- c('toy', 'atlas')
cases <- list(
  list(name = 'reordered-finite', ids = c(42L, 7L, 19L), values = c(3.75, -1.25, 2.5), partial = FALSE, background = -99),
  list(name = 'missing-parcel', ids = c(42L, 7L), values = c(0.3, 0.1), partial = TRUE, background = -99),
  list(name = 'missing-background', ids = c(7L, 19L, 42L), values = c(-4, 0, 9), partial = FALSE, background = NA_real_)
)
# Scala/Ravel's last axis is fastest; do not equate R's linear storage order.
coords <- do.call(rbind, lapply(1:2, function(x) do.call(rbind, lapply(1:2, function(y) cbind(x, y, 1:2)))))
rows <- list()
for (i in seq_along(cases)) {
  c <- cases[[i]]
  result <- parcel_volume(atlas, data.frame(id = c$ids, statistic = c$values), statistic,
    by = 'id', allow_partial = c$partial, background = c$background)
  stopifnot(identical(neuroim2::space(result), space))
  actual <- array(as.numeric(result), dim(labels))
  c$expected <- actual[coords]
  cases[[i]] <- c
  rows[[i]] <- data.frame(case = c$name, x = coords[, 1] - 1L, y = coords[, 2] - 1L,
    z = coords[, 3] - 1L, source_label = labels[coords], value = c$expected)
}
stopifnot(identical(cases[[1]]$expected, c(-99, 2.5, -1.25, 3.75, -1.25, 3.75, 2.5, -99)))
write.table(do.call(rbind, rows), file.path(out, 'parcel-expansion.tsv'), sep = '\t', quote = FALSE, row.names = FALSE, na = 'NaN')
q <- function(x) as.character(jsonlite::toJSON(x, auto_unbox = TRUE))
iv <- function(x) paste0('Vector(', paste(x, collapse = ', '), ')')
dv <- function(x) paste0('Vector(', paste(ifelse(is.na(x), 'Double.NaN', sprintf('%.17g', x)), collapse = ', '), ')')
lines <- c('package scalafim.atlas.fixtures', '',
  '// Generated by tools/r-parity/generate_atlas_parcel_expansion.R; do not edit.',
  'object ParcelExpansionFixture:',
  paste0('  val labels: Vector[Int] = ', iv(labels[coords])),
  '  final case class Case(name: String, ids: Vector[Int], values: Vector[Double], partial: Boolean, background: Double, expected: Vector[Double])',
  '  val cases: Vector[Case] = Vector(')
for (i in seq_along(cases)) {
  c <- cases[[i]]
  bg <- if (is.na(c$background)) 'Double.NaN' else sprintf('%.17g', c$background)
  lines <- c(lines, paste0('    Case(', q(c$name), ', ', iv(c$ids), ', ', dv(c$values), ', ', tolower(c$partial), ', ', bg, ', ', dv(c$expected), ')', if (i < length(cases)) ',' else ''))
}
writeLines(c(lines, '  )'), scala)
sha <- function(path) digest::digest(file = path, algo = 'sha256')
jsonlite::write_json(list(reference = 'neuroatlas',
  commit = system2('git', c('-C', shQuote(r_pkg), 'rev-parse', 'HEAD'), stdout = TRUE),
  parcel_data_sha256 = sha(file.path(r_pkg, 'R/parcel_data.R')),
  generator_sha256 = sha(file.path(root, 'tools/r-parity/generate_atlas_parcel_expansion.R')),
  tsv_sha256 = sha(file.path(out, 'parcel-expansion.tsv')), scala_sha256 = sha(scala),
  R_version = R.version.string, cases = length(cases),
  ordinal_layout = 'explicit x,y,z; row-major-last-axis-fastest/v1',
  scope = 'Synthetic finite and missing-value expansion; exact R space retained; no asset acquisition or infinity-policy parity'),
  file.path(out, 'parcel-expansion.json'), auto_unbox = TRUE, pretty = TRUE)
message('Generated three independent coordinate-keyed expansion cases; exact source space retained')
