#!/usr/bin/env Rscript

# Independent continuous-time oracle for a phase/cell mixed-width HRF design.
# The custom kernels are stated directly below; no ScalaFIM design code or
# rendered column names participate in matrix construction.

if (!requireNamespace("jsonlite", quietly = TRUE)) {
  stop("jsonlite is required to generate the heterogeneous-HRF receipt", call. = FALSE)
}

out_file <- Sys.getenv(
  "HETEROGENEOUS_HRF_RECEIPT_OUT",
  file.path("docs", "scenarios", "fixtures", "design.heterogeneous-hrf.v1.r.json")
)
scala_out <- Sys.getenv(
  "HETEROGENEOUS_HRF_SCALA_OUT",
  file.path(
    "modules", "design", "shared", "src", "test", "scala",
    "scalafim", "fmri", "design", "fixtures", "HeterogeneousHrfRFixture.scala"
  )
)

scans <- 0:27
conditions <- c("A", "B", "A", "B")
sample_onsets <- c(1, 7, 13, 19)
probe_onsets <- c(3, 9, 15, 21)
horizon <- 4

compact <- function(lag, value) {
  ifelse(lag >= 0 & lag <= horizon, value, 0)
}
sample_kernel <- function(lag) compact(lag, exp(-lag))
probe_a_kernel <- function(lag) compact(lag, exp(-0.5 * lag))
probe_b_canonical <- function(lag) compact(lag, exp(-lag))
probe_b_temporal <- function(lag) compact(lag, lag * exp(-lag))

event_column <- function(onsets, cells, selected, kernel) {
  vapply(scans, function(scan) {
    selected_onsets <- onsets[cells == selected]
    sum(vapply(scan - selected_onsets, kernel, numeric(1)))
  }, numeric(1))
}

matrix <- cbind(
  sample_A = event_column(sample_onsets, conditions, "A", sample_kernel),
  sample_B = event_column(sample_onsets, conditions, "B", sample_kernel),
  probe_A_canonical = event_column(probe_onsets, conditions, "A", probe_a_kernel),
  probe_B_canonical = event_column(probe_onsets, conditions, "B", probe_b_canonical),
  probe_B_temporal = event_column(probe_onsets, conditions, "B", probe_b_temporal)
)

source <- list(
  r_version = as.character(getRversion()),
  stats_version = as.character(utils::packageVersion("stats")),
  producer = "tools/r-parity/generate_heterogeneous_hrf_receipt.R",
  reference = "independent base-R continuous-time event summation"
)
accepted_differences <- c(
  "The oracle uses explicitly stated custom kernels so no fmridesign or fmrihrf default basis convention is imported.",
  "Column alignment is declared structurally as phase, cell, and basis element rather than inferred from rendered labels."
)
schema <- "scalafim-r-kernel-fixture/v1"
inputs <- list(
  scans = scans,
  conditions = conditions,
  sample_onsets = sample_onsets,
  probe_onsets = probe_onsets,
  compact_horizon = horizon,
  phase_assignments = list(
    sample = list(A = c("canonical"), B = c("canonical")),
    probe = list(A = c("canonical"), B = c("canonical", "temporal-derivative"))
  )
)
outputs <- list(
  column_keys = colnames(matrix),
  matrix = unname(split(matrix, row(matrix)))
)
receipt <- list(
  schema_version = schema,
  producer_command = "LC_ALL=C LANG=C Rscript tools/r-parity/generate_heterogeneous_hrf_receipt.R && python3 tools/r-parity/finalize_heterogeneous_hrf_receipt.py",
  accepted_differences = accepted_differences,
  conventions = list(
    dtype = "float64",
    json_encoding = "sorted-key UTF-8 JSON",
    matrix_orientation = "rows are scans; columns follow outputs.column_keys",
    hrf_basis = "explicit compact custom kernels evaluated at scan minus onset",
    column_order = "sample A, sample B, probe A canonical, probe B canonical, probe B temporal derivative"
  ),
  hashes = list(inputs_sha256 = "", outputs_sha256 = ""),
  source = source
)
payload <- list(
  schema_version = schema,
  scenario_id = "design.heterogeneous-hrf.v1",
  inputs = inputs,
  outputs = outputs,
  source = source,
  receipt = receipt
)

scala_string <- function(value) {
  paste0("\"", gsub("\\\\", "\\\\\\\\", gsub("\"", "\\\\\"", value)), "\"")
}
scala_number <- function(value) {
  if (abs(value) < 5e-16) "0.0" else sprintf("%.17g", value)
}
scala_vector <- function(values, render) {
  if (length(values) == 0) "Vector.empty"
  else paste0("Vector(", paste(vapply(values, render, character(1)), collapse = ", "), ")")
}
scala_doubles <- function(values) scala_vector(as.numeric(values), scala_number)
scala_strings <- function(values) scala_vector(as.character(values), scala_string)

dir.create(dirname(out_file), recursive = TRUE, showWarnings = FALSE)
jsonlite::write_json(payload, out_file, auto_unbox = TRUE, digits = 17, pretty = TRUE)
message("wrote ", out_file)

dir.create(dirname(scala_out), recursive = TRUE, showWarnings = FALSE)
matrix_rows <- apply(matrix, 1, scala_doubles)
writeLines(
  c(
    "package scalafim.fmri.design.fixtures",
    "",
    "// Generated by tools/r-parity/generate_heterogeneous_hrf_receipt.R.",
    "object HeterogeneousHrfRFixture:",
    paste0("  val scans: Vector[Double] = ", scala_doubles(scans)),
    paste0("  val conditions: Vector[String] = ", scala_strings(conditions)),
    paste0("  val sampleOnsets: Vector[Double] = ", scala_doubles(sample_onsets)),
    paste0("  val probeOnsets: Vector[Double] = ", scala_doubles(probe_onsets)),
    paste0("  val columnKeys: Vector[String] = ", scala_strings(colnames(matrix))),
    "  val matrix: Vector[Vector[Double]] = Vector(",
    paste0("    ", paste(matrix_rows, collapse = ",\n    ")),
    "  )",
    paste0("  val acceptedDifferences: Vector[String] = ", scala_strings(accepted_differences))
  ),
  scala_out
)
message("wrote ", scala_out)
