#!/usr/bin/env Rscript

# Independent base-R oracle for crossvalidated squared Mahalanobis distance
# with identity precision. The fixture deliberately contains a condition pair
# whose two independent partition contrasts reverse sign: its crossvalidated
# estimate is negative even though the within-partition plug-in estimate is
# strictly positive. Pair coordinates use the declared effect-axis upper
# triangle, never a matrix implementation's traversal order.

fmt_num <- function(value) {
  if (value == 0) return("0.0")
  sprintf("%.17g", value)
}

fmt_strings <- function(values) {
  paste0("Vector(", paste(sprintf('"%s"', values), collapse = ", "), ")")
}

fmt_doubles <- function(values) {
  paste0("Vector(", paste(vapply(values, fmt_num, character(1)), collapse = ", "), ")")
}

fmt_pairs <- function(values) {
  entries <- vapply(values, function(value) {
    sprintf('"%s" -> "%s"', value[[1]], value[[2]])
  }, character(1))
  paste0("Vector(", paste(entries, collapse = ", "), ")")
}

fmt_matrix <- function(values, indent) {
  rows <- apply(values, 1, function(row) {
    paste0("Vector(", paste(vapply(row, fmt_num, character(1)), collapse = ", "), ")")
  })
  pad <- paste(rep(" ", indent), collapse = "")
  row_pad <- paste(rep(" ", indent + 2), collapse = "")
  paste0(
    "GaleTestMatrix.fromRows(\n",
    pad, "Vector(\n",
    row_pad, paste(rows, collapse = paste0(",\n", row_pad)), "\n",
    pad, ")\n",
    paste(rep(" ", indent - 2), collapse = ""), ")"
  )
}

effect_labels <- c("a", "b", "c")
feature_labels <- c("v1", "v2")
partition_labels <- c("run-1", "run-2")

partition_patterns <- list(
  matrix(
    c(
      1.0, 0.0,
      -1.0, 0.0,
      0.0, 2.0
    ),
    nrow = 3,
    byrow = TRUE,
    dimnames = list(effect_labels, feature_labels)
  ),
  matrix(
    c(
      -1.0, 0.0,
      1.0, 0.0,
      0.0, 1.0
    ),
    nrow = 3,
    byrow = TRUE,
    dimnames = list(effect_labels, feature_labels)
  )
)

pair_indices <- combn(seq_along(effect_labels), 2L, simplify = FALSE)
pair_order <- lapply(pair_indices, function(pair) effect_labels[pair])
ordered_partition_pairs <- Filter(
  function(pair) pair[[1]] != pair[[2]],
  asplit(expand.grid(seq_along(partition_patterns), seq_along(partition_patterns)), 1L)
)

contrast <- function(patterns, pair) {
  patterns[pair[[1]], ] - patterns[pair[[2]], ]
}

raw_crossvalidated <- vapply(pair_indices, function(pair) {
  products <- vapply(ordered_partition_pairs, function(partition_pair) {
    left <- contrast(partition_patterns[[partition_pair[[1]]]], pair)
    right <- contrast(partition_patterns[[partition_pair[[2]]]], pair)
    sum(left * right)
  }, numeric(1))
  mean(products)
}, numeric(1))

naive_squared <- vapply(pair_indices, function(pair) {
  mean(vapply(partition_patterns, function(patterns) {
    difference <- contrast(patterns, pair)
    sum(difference ^ 2)
  }, numeric(1)))
}, numeric(1))

per_feature_crossvalidated <- raw_crossvalidated / length(feature_labels)

stopifnot(
  identical(vapply(pair_order, paste, collapse = ":", character(1)), c("a:b", "a:c", "b:c")),
  isTRUE(all.equal(raw_crossvalidated, c(-4.0, 1.0, 1.0), tolerance = 1e-15)),
  isTRUE(all.equal(naive_squared, c(4.0, 3.5, 3.5), tolerance = 1e-15)),
  naive_squared[[1]] > 0,
  raw_crossvalidated[[1]] < 0
)

cat("package scalafim.fmri.mvpa\n\n")
cat("import gale.linalg.DMat\n\n")
cat("/** Fixed base-R reference for crossvalidated squared Mahalanobis distance. Generated by\n")
cat("  * tools/r-parity/generate_crossvalidated_rdm_fixtures.R.\n")
cat("  */\n")
cat("object CrossvalidatedRdmReferenceFixtures:\n")
cat("  val effectLabels: Vector[String] = ", fmt_strings(effect_labels), "\n", sep = "")
cat("  val featureLabels: Vector[String] = ", fmt_strings(feature_labels), "\n", sep = "")
cat("  val partitionLabels: Vector[String] = ", fmt_strings(partition_labels), "\n", sep = "")
cat("  val pairOrder: Vector[(String, String)] = ", fmt_pairs(pair_order), "\n", sep = "")
cat("  val partitionPatterns: Vector[DMat] = Vector(\n")
cat("    ", paste(vapply(partition_patterns, fmt_matrix, character(1), indent = 6), collapse = ",\n    "), "\n", sep = "")
cat("  )\n")
cat("  val naiveSquaredDistances: Vector[Double] = ", fmt_doubles(naive_squared), "\n", sep = "")
cat("  val rawCrossvalidatedDistances: Vector[Double] = ", fmt_doubles(raw_crossvalidated), "\n", sep = "")
cat("  val perFeatureCrossvalidatedDistances: Vector[Double] = ", fmt_doubles(per_feature_crossvalidated), "\n", sep = "")
