#!/usr/bin/env Rscript

# Ribbon-fill parity oracle for scalafim.surface.RibbonOperator (STP P8.01).
#
# Six white->pial segments on an oblique, anisotropic 7x6x5 grid exercise the
# neurotransform ribbon kernel: an interior segment, segments in the lower and
# upper half-voxel clamping bands, one leaving the grid, one wholly outside it,
# and a zero-length segment. The script records
#   * cpp_ribbon_weights (the vertex x voxel matrix W that ribbon sampling and
#     its adjoint share) as nonzero (vertex, i, j, k, weight) rows, and
#   * backproject_surface_to_volume(method = "ribbon"), the public surf->vol
#     adjoint W^T s, as nonzero (i, j, k, value) rows.
# Voxel indices are 0-based grid coordinates, so the fixture is independent of
# R's x-fastest and ScalaFIM's z-fastest linear orders.
#
# Run from the repository root:
#   Rscript tools/r-parity/generate_ribbon_fill_fixture.R
# It rewrites
#   modules/surface/shared/src/test/scala/scalafim/surface/fixtures/RibbonRFixture.scala

suppressMessages(library(neurotransform))

out_path <- file.path(
  "modules", "surface", "shared", "src", "test", "scala", "scalafim",
  "surface", "fixtures", "RibbonRFixture.scala"
)
revision_file <- file.path(path.expand("~/code/neurotransform"), ".git", "refs", "heads", "main")
revision <- if (file.exists(revision_file)) trimws(readLines(revision_file, n = 1L)) else "unknown"

dims <- c(7L, 6L, 5L)
theta <- 20 * pi / 180
rotation <- matrix(c(cos(theta), sin(theta), 0, -sin(theta), cos(theta), 0, 0, 0, 1), 3, 3)
voxel_to_world <- diag(4)
voxel_to_world[1:3, 1:3] <- rotation %*% diag(c(2, 2.5, 3))
voxel_to_world[1:3, 4] <- c(-6, -5, -4)

to_world <- function(vox) {
  t(voxel_to_world[1:3, 1:3] %*% t(vox) + voxel_to_world[1:3, 4])
}

inner_vox <- rbind(
  c(1.2, 1.3, 1.1),
  c(-0.4, 2.2, 0.3),
  c(5.2, 4.1, 3.6),
  c(-3.0, -3.0, -3.0),
  c(3.0, 2.0, 2.0),
  c(6.3, 5.2, 4.4)
)
outer_vox <- rbind(
  c(4.7, 3.9, 2.8),
  c(2.5, 4.6, 3.9),
  c(8.5, 6.8, 5.9),
  c(-2.0, -2.0, -1.5),
  c(3.0, 2.0, 2.0),
  c(6.6, 5.45, 4.6)
)
inner <- to_world(inner_vox)
outer <- to_world(outer_vox)
n_steps <- 4L

world_to_voxel <- solve(voxel_to_world)
w <- neurotransform:::cpp_ribbon_weights(
  inner, outer, world_to_voxel, dims,
  n_steps = n_steps, mask = rep(TRUE, prod(dims))
)

lin_to_ijk <- function(lin) {
  z <- lin %/% (dims[1] * dims[2])
  rem <- lin %% (dims[1] * dims[2])
  y <- rem %/% dims[1]
  x <- rem %% dims[1]
  cbind(x, y, z)
}

keep <- w$vals > 0
weight_ijk <- lin_to_ijk(w$cols[keep] - 1L)
weight_rows <- cbind(w$rows[keep] - 1L, weight_ijk, w$vals[keep])
weight_rows <- weight_rows[order(weight_rows[, 1], weight_rows[, 4], weight_rows[, 3], weight_rows[, 2]), , drop = FALSE]

surface_values <- c(1.5, -2.0, 0.25, 3.0, 7.0, -1.0)
morphism <- VolToSurfMorphism(
  "vol", "surf",
  method = "ribbon", ribbon_inner = "white", ribbon_outer = "pial",
  ribbon_inner_coords = inner, ribbon_outer_coords = outer,
  n_ribbon_samples = n_steps
)
grid <- methods::new("Grid", dims = dims, affine = voxel_to_world)
filled <- backproject_surface_to_volume(
  surface_values, morphism, grid,
  surface_coords = inner, method = "ribbon"
)
nonzero <- which(filled != 0, arr.ind = TRUE)
adjoint_rows <- cbind(nonzero - 1L, filled[nonzero])
adjoint_rows <- adjoint_rows[order(adjoint_rows[, 3], adjoint_rows[, 2], adjoint_rows[, 1]), , drop = FALSE]

num <- function(x) sprintf("%.17g", x)
vec <- function(x) paste0("Vector(", paste(num(x), collapse = ", "), ")")
rows_literal <- function(m) {
  paste0(
    "Vector(\n",
    paste0("    ", apply(m, 1, vec), collapse = ",\n"),
    "\n  )"
  )
}

lines <- c(
  "package scalafim.surface.fixtures",
  "",
  "// Generated by tools/r-parity/generate_ribbon_fill_fixture.R; do not edit by hand.",
  "object RibbonRFixture:",
  sprintf("  val neurotransformVersion: String = \"%s\"", as.character(packageVersion("neurotransform"))),
  sprintf("  val neurotransformRevision: String = \"%s\"", revision),
  sprintf("  val dims: Vector[Int] = Vector(%s)", paste(dims, collapse = ", ")),
  sprintf("  val steps: Int = %d", n_steps),
  sprintf("  val voxelToWorldRowMajor: Vector[Double] = %s", vec(as.vector(t(voxel_to_world)))),
  sprintf("  val white: Vector[Vector[Double]] = %s", rows_literal(inner)),
  sprintf("  val pial: Vector[Vector[Double]] = %s", rows_literal(outer)),
  "  /** Nonzero cpp_ribbon_weights rows: vertex, i, j, k, weight (0-based). */",
  sprintf("  val weights: Vector[Vector[Double]] = %s", rows_literal(weight_rows)),
  sprintf("  val surfaceValues: Vector[Double] = %s", vec(surface_values)),
  "  /** Nonzero backproject_surface_to_volume(method = \"ribbon\") voxels: i, j, k, value (0-based). */",
  sprintf("  val adjoint: Vector[Vector[Double]] = %s", rows_literal(adjoint_rows))
)
writeLines(lines, out_path)
cat(sprintf("wrote %s (%d weights, %d adjoint voxels)\n", out_path, nrow(weight_rows), nrow(adjoint_rows)))
