#!/usr/bin/env Rscript

# Regenerate the Scala golden fixtures used by RParityCorpusSuite.
#
# From the scalafim repository root:
#   Rscript tools/r-parity/generate_fmridesign_r_parity_fixtures.R
#
# By default this loads the live R source at ~/code/fmridesign with pkgload and
# writes the merged design module's RParityFixtures.scala. Override those paths with:
#   FMRIDESIGN_R=/path/to/fmridesign RPARITY_OUT=/path/to/RParityFixtures.scala \
#     Rscript tools/r-parity/generate_fmridesign_r_parity_fixtures.R

if (!requireNamespace("pkgload", quietly = TRUE)) {
  stop("pkgload is required to generate parity fixtures", call. = FALSE)
}

r_pkg <- Sys.getenv("FMRIDESIGN_R", file.path(path.expand("~"), "code", "fmridesign"))
out_file <- Sys.getenv(
  "RPARITY_OUT",
  file.path(
    "modules", "design", "shared", "src", "test", "scala",
    "io", "neuroim", "fmri", "design", "fixtures", "RParityFixtures.scala"
  )
)

pkgload::load_all(r_pkg, quiet = TRUE)

scala_string <- function(x) {
  paste0("\"", gsub("\\\\", "\\\\\\\\", gsub("\"", "\\\\\"", x)), "\"")
}

scala_vector_string <- function(xs) {
  paste0("Vector(", paste(vapply(xs, scala_string, character(1)), collapse = ", "), ")")
}

scala_vector_double <- function(xs) {
  paste0("Vector(", paste(sprintf("%.9f", as.numeric(xs)), collapse = ", "), ")")
}

scala_vector_int <- function(xs) {
  paste0("Vector(", paste(as.integer(xs), collapse = ", "), ")")
}

sf_event <- fmrihrf::sampling_frame(blocklens = 12, TR = 1)
event_data <- data.frame(
  onset = c(1, 5, 9),
  block = 1,
  cond = factor(c("A", "B", "A")),
  x = c(1, 2, 3)
)
event_contrasts <- contrast_set(
  diff = column_contrast(pattern_A = "cond.A", pattern_B = "cond.B", name = "diff")
)
event_model_fixture <- event_model(
  onset ~ hrf(cond, x, name = "task", contrasts = event_contrasts),
  data = event_data,
  block = ~block,
  sampling_frame = sf_event
)
event_dm <- as.matrix(design_matrix(event_model_fixture))
event_col_indices <- attr(design_matrix(event_model_fixture), "col_indices")
event_f <- Fcontrasts(event_model_fixture)
event_attached <- contrasts(event_model_fixture)

sf_base <- fmrihrf::sampling_frame(blocklens = c(3, 2), TR = 1)
baseline_fixture <- baseline_model(basis = "constant", sframe = sf_base, intercept = "runwise")
baseline_dm <- as.matrix(design_matrix(baseline_fixture))

lines <- c(
  "package scalafim.fmri.design.fixtures",
  "",
  "// Generated by tools/r-parity/generate_fmridesign_r_parity_fixtures.R from the live R fmridesign source.",
  "object RParityFixtures:",
  "  final case class MatrixFixture(rows: Int, cols: Int, columnNames: Vector[String], values: Vector[Double])",
  "  final case class EventFixture(",
  "      termKeys: Vector[String],",
  "      matrix: MatrixFixture,",
  "      rColIndices1Based: Map[String, Vector[Int]],",
  "      rTermSpans1Based: Vector[Int],",
  "      attachedContrastKeys: Vector[String],",
  "      attachedContrastWeights: Vector[Double],",
  "      fContrastKeys: Vector[String],",
  "      fContrastWeights: Vector[Double]",
  "  )",
  "  final case class BaselineFixture(termKeys: Vector[String], matrix: MatrixFixture)",
  "",
  "  val eventInteraction: EventFixture =",
  "    EventFixture(",
  paste0("      termKeys = ", scala_vector_string(names(terms(event_model_fixture))), ","),
  "      matrix = MatrixFixture(",
  paste0("        rows = ", nrow(event_dm), ","),
  paste0("        cols = ", ncol(event_dm), ","),
  paste0("        columnNames = ", scala_vector_string(colnames(event_dm)), ","),
  paste0("        values = ", scala_vector_double(as.vector(t(event_dm)))),
  "      ),",
  paste0("      rColIndices1Based = Map(\"", names(event_col_indices)[[1]], "\" -> ", scala_vector_int(event_col_indices[[1]]), "),"),
  paste0("      rTermSpans1Based = ", scala_vector_int(attr(design_matrix(event_model_fixture), "term_spans")), ","),
  paste0("      attachedContrastKeys = ", scala_vector_string(names(event_attached)), ","),
  paste0("      attachedContrastWeights = ", scala_vector_double(as.vector(event_attached[[1]])), ","),
  paste0("      fContrastKeys = ", scala_vector_string(names(event_f)), ","),
  paste0("      fContrastWeights = ", scala_vector_double(as.vector(event_f[[1]]))),
  "    )",
  "",
  "  val baselineConstantRunwise: BaselineFixture =",
  "    BaselineFixture(",
  paste0("      termKeys = ", scala_vector_string(names(baseline_fixture$terms)), ","),
  "      matrix = MatrixFixture(",
  paste0("        rows = ", nrow(baseline_dm), ","),
  paste0("        cols = ", ncol(baseline_dm), ","),
  paste0("        columnNames = ", scala_vector_string(colnames(baseline_dm)), ","),
  paste0("        values = ", scala_vector_double(as.vector(t(baseline_dm)))),
  "      )",
  "    )"
)

dir.create(dirname(out_file), recursive = TRUE, showWarnings = FALSE)
writeLines(lines, out_file)
message("wrote ", out_file)
