// Generated by tools/r-parity/generate_group_metafor_fixture.R. Do not edit by hand.
package scalafim.fmri.group.fixtures

object GroupMetaforFixtures:
  val SchemaVersion = "scalafim-group-metafor-fixture/v1"
  val Oracle = "metafor 5.0.1"
  val AbsoluteTolerance = 1e-8
  val RelativeTolerance = 1e-8
  val PValueTolerance = 1e-7

  final case class Expected(
      policy: String,
      coefficients: Vector[Double],
      standardErrors: Vector[Double],
      covarianceRowMajor: Vector[Double],
      statistics: Vector[Double],
      pValues: Vector[Double],
      tau2: Double,
      fixedQ: Double,
      residualDf: Int
  )

  final case class Case(
      id: String,
      subjects: Int,
      terms: Vector[String],
      designRowMajor: Vector[Double],
      effects: Vector[Double],
      variances: Vector[Double],
      expected: Vector[Expected]
  )

  val Cases: Vector[Case] = Vector(
    Case(
      id = "intercept_heterogeneous",
      subjects = 8,
      terms = Vector("intercept"),
      designRowMajor = Vector(1e+00, 1e+00, 1e+00, 1e+00, 1e+00, 1e+00, 1e+00, 1e+00),
      effects = Vector(-2.9999999999999999e-01, 1.0000000000000001e-01, 2.5e-01, 4.0000000000000002e-01, 8.0000000000000004e-01, 1.1000000000000001e+00, 1.3999999999999999e+00, 1.8e+00),
      variances = Vector(4.0000000000000001e-02, 8.9999999999999997e-02, 1.6e-01, 2.5e-01, 3.5999999999999999e-01, 4.8999999999999999e-01, 6.4000000000000001e-01, 8.1000000000000005e-01),
      expected = Vector(
      Expected(
        policy = "FE-z",
        coefficients = Vector(1.0468305510830603e-01),
        standardErrors = Vector(1.3611203939991529e-01),
        covarianceRowMajor = Vector(1.8526487269604094e-02),
        statistics = Vector(7.6909475142557582e-01),
        pValues = Vector(4.4183706376371679e-01),
        tau2 = 0e+00,
        fixedQ = 1.4109894907320561e+01,
        residualDf = 7
      ),
      Expected(
        policy = "DL-z",
        coefficients = Vector(3.8571958033975184e-01),
        standardErrors = Vector(2.2997649452670163e-01),
        covarianceRowMajor = Vector(5.2889188034790022e-02),
        statistics = Vector(1.6772130609850979e+00),
        pValues = Vector(9.3500825908488766e-02),
        tau2 = 1.8325981695138374e-01,
        fixedQ = 1.4109894907320561e+01,
        residualDf = 7
      ),
      Expected(
        policy = "PM-z",
        coefficients = Vector(3.7711405715119023e-01),
        standardErrors = Vector(2.2575581125067906e-01),
        covarianceRowMajor = Vector(5.0965686313452233e-02),
        statistics = Vector(1.6704511616422715e+00),
        pValues = Vector(9.4830134471860381e-02),
        tau2 = 1.7091158873991405e-01,
        fixedQ = 1.4109894907320561e+01,
        residualDf = 7
      ),
      Expected(
        policy = "DL-mKH",
        coefficients = Vector(3.8571958033975184e-01),
        standardErrors = Vector(2.2997649452670163e-01),
        covarianceRowMajor = Vector(5.2889188034790022e-02),
        statistics = Vector(1.6772130609850979e+00),
        pValues = Vector(1.3740173593472269e-01),
        tau2 = 1.8325981695138374e-01,
        fixedQ = 1.4109894907320561e+01,
        residualDf = 7
      ),
      Expected(
        policy = "PM-mKH",
        coefficients = Vector(3.7711405715119023e-01),
        standardErrors = Vector(2.2575581125067906e-01),
        covarianceRowMajor = Vector(5.0965686313452233e-02),
        statistics = Vector(1.6704511616422715e+00),
        pValues = Vector(1.3875609900739441e-01),
        tau2 = 1.7091158873991405e-01,
        fixedQ = 1.4109894907320561e+01,
        residualDf = 7
      )
      )
    ),
    Case(
      id = "offset_moderator",
      subjects = 10,
      terms = Vector("intercept", "age"),
      designRowMajor = Vector(1e+00, 4.2e+01, 1e+00, 4.5e+01, 1e+00, 4.7e+01, 1e+00, 5e+01, 1e+00, 5.4e+01, 1e+00, 5.7e+01, 1e+00, 6.1e+01, 1e+00, 6.4e+01, 1e+00, 6.8e+01, 1e+00, 7.3e+01),
      effects = Vector(2.2e-01, 8.0000000000000002e-02, 3.1e-01, 4.0999999999999998e-01, 3.4999999999999998e-01, 6.2e-01, 7.9000000000000004e-01, 6.9999999999999996e-01, 1.02e+00, 1.1499999999999999e+00),
      variances = Vector(8.0000000000000002e-02, 1.3e-01, 5.0000000000000003e-02, 2.0999999999999999e-01, 1.1e-01, 2.7000000000000002e-01, 8.9999999999999997e-02, 1.7999999999999999e-01, 1.4000000000000001e-01, 3.1e-01),
      expected = Vector(
      Expected(
        policy = "FE-z",
        coefficients = Vector(-1.1991485306084586e+00, 3.1587444936618907e-02),
        standardErrors = Vector(6.3933214288676055e-01, 1.1855261184213171e-02),
        covarianceRowMajor = Vector(4.0874558892817719e-01, -7.4692937497002759e-03, -7.4692937497002759e-03, 1.4054721774591148e-04),
        statistics = Vector(-1.8756268458425585e+00, 2.6644242118159078e+00),
        pValues = Vector(6.0706537412857614e-02, 7.7120241812189752e-03),
        tau2 = 0e+00,
        fixedQ = 6.7174602257521565e-01,
        residualDf = 8
      ),
      Expected(
        policy = "DL-z",
        coefficients = Vector(-1.1991485306084586e+00, 3.1587444936618907e-02),
        standardErrors = Vector(6.3933214288676055e-01, 1.1855261184213171e-02),
        covarianceRowMajor = Vector(4.0874558892817719e-01, -7.4692937497002759e-03, -7.4692937497002759e-03, 1.4054721774591148e-04),
        statistics = Vector(-1.8756268458425585e+00, 2.6644242118159078e+00),
        pValues = Vector(6.0706537412857614e-02, 7.7120241812189752e-03),
        tau2 = 0e+00,
        fixedQ = 6.7174602257521565e-01,
        residualDf = 8
      ),
      Expected(
        policy = "PM-z",
        coefficients = Vector(-1.1991485306084586e+00, 3.1587444936618907e-02),
        standardErrors = Vector(6.3933214288676055e-01, 1.1855261184213171e-02),
        covarianceRowMajor = Vector(4.0874558892817719e-01, -7.4692937497002759e-03, -7.4692937497002759e-03, 1.4054721774591148e-04),
        statistics = Vector(-1.8756268458425585e+00, 2.6644242118159078e+00),
        pValues = Vector(6.0706537412857614e-02, 7.7120241812189752e-03),
        tau2 = 0e+00,
        fixedQ = 6.7174602257521565e-01,
        residualDf = 8
      ),
      Expected(
        policy = "DL-mKH",
        coefficients = Vector(-1.1991485306084586e+00, 3.1587444936618907e-02),
        standardErrors = Vector(6.3933214288676055e-01, 1.1855261184213171e-02),
        covarianceRowMajor = Vector(4.0874558892817719e-01, -7.4692937497002759e-03, -7.4692937497002759e-03, 1.4054721774591148e-04),
        statistics = Vector(-1.8756268458425585e+00, 2.6644242118159078e+00),
        pValues = Vector(9.755943459598633e-02, 2.8608515665169889e-02),
        tau2 = 0e+00,
        fixedQ = 6.7174602257521565e-01,
        residualDf = 8
      ),
      Expected(
        policy = "PM-mKH",
        coefficients = Vector(-1.1991485306084586e+00, 3.1587444936618907e-02),
        standardErrors = Vector(6.3933214288676055e-01, 1.1855261184213171e-02),
        covarianceRowMajor = Vector(4.0874558892817719e-01, -7.4692937497002759e-03, -7.4692937497002759e-03, 1.4054721774591148e-04),
        statistics = Vector(-1.8756268458425585e+00, 2.6644242118159078e+00),
        pValues = Vector(9.755943459598633e-02, 2.8608515665169889e-02),
        tau2 = 0e+00,
        fixedQ = 6.7174602257521565e-01,
        residualDf = 8
      )
      )
    ),
    Case(
      id = "two_moderators",
      subjects = 12,
      terms = Vector("intercept", "dose", "site"),
      designRowMajor = Vector(1e+00, -1.8e+00, 0e+00, 1e+00, -1.3e+00, 1e+00, 1e+00, -9.0000000000000002e-01, 0e+00, 1e+00, -4.0000000000000002e-01, 1e+00, 1e+00, -1.0000000000000001e-01, 0e+00, 1e+00, 2.0000000000000001e-01, 1e+00, 1e+00, 5.9999999999999998e-01, 0e+00, 1e+00, 9.0000000000000002e-01, 1e+00, 1e+00, 1.3e+00, 0e+00, 1e+00, 1.7e+00, 1e+00, 1e+00, 2.1000000000000001e+00, 0e+00, 1e+00, 2.5e+00, 1e+00),
      effects = Vector(-1.4999999999999999e-01, 3.4000000000000002e-01, 2e-02, 4.7999999999999998e-01, 2.7000000000000002e-01, 6.0999999999999999e-01, 4.4e-01, 9.4999999999999996e-01, 7.1999999999999997e-01, 1.1799999999999999e+00, 9.1000000000000003e-01, 1.4199999999999999e+00),
      variances = Vector(5.9999999999999998e-02, 1.7999999999999999e-01, 8.9999999999999997e-02, 2.2e-01, 7.0000000000000007e-02, 1.4000000000000001e-01, 1.1e-01, 2.8999999999999998e-01, 8.0000000000000002e-02, 1.9e-01, 1.3e-01, 2.5e-01),
      expected = Vector(
      Expected(
        policy = "FE-z",
        coefficients = Vector(3.1667953873333538e-01, 2.8420914896694671e-01, 3.3397481234123838e-01),
        standardErrors = Vector(1.1845248879218531e-01, 7.7213592392366706e-02, 2.2155557586382377e-01),
        covarianceRowMajor = Vector(1.4030992101062786e-02, 2.9833462700611026e-04, -1.4174794659790994e-02, 2.9833462700611026e-04, 5.9619388501345504e-03, -3.1720944390470972e-03, -1.4174794659790994e-02, -3.1720944390470972e-03, 4.9086873196350571e-02),
        statistics = Vector(2.6734730689274273e+00, 3.6808175887312227e+00, 1.507408744009727e+00),
        pValues = Vector(7.5070303558608421e-03, 2.3248728665841849e-04, 1.3170591886524421e-01),
        tau2 = 0e+00,
        fixedQ = 2.2509191700366843e-01,
        residualDf = 9
      ),
      Expected(
        policy = "DL-z",
        coefficients = Vector(3.1667953873333538e-01, 2.8420914896694671e-01, 3.3397481234123838e-01),
        standardErrors = Vector(1.1845248879218531e-01, 7.7213592392366706e-02, 2.2155557586382377e-01),
        covarianceRowMajor = Vector(1.4030992101062786e-02, 2.9833462700611026e-04, -1.4174794659790994e-02, 2.9833462700611026e-04, 5.9619388501345504e-03, -3.1720944390470972e-03, -1.4174794659790994e-02, -3.1720944390470972e-03, 4.9086873196350571e-02),
        statistics = Vector(2.6734730689274273e+00, 3.6808175887312227e+00, 1.507408744009727e+00),
        pValues = Vector(7.5070303558608421e-03, 2.3248728665841849e-04, 1.3170591886524421e-01),
        tau2 = 0e+00,
        fixedQ = 2.2509191700366843e-01,
        residualDf = 9
      ),
      Expected(
        policy = "PM-z",
        coefficients = Vector(3.1667953873333538e-01, 2.8420914896694671e-01, 3.3397481234123838e-01),
        standardErrors = Vector(1.1845248879218531e-01, 7.7213592392366706e-02, 2.2155557586382377e-01),
        covarianceRowMajor = Vector(1.4030992101062786e-02, 2.9833462700611026e-04, -1.4174794659790994e-02, 2.9833462700611026e-04, 5.9619388501345504e-03, -3.1720944390470972e-03, -1.4174794659790994e-02, -3.1720944390470972e-03, 4.9086873196350571e-02),
        statistics = Vector(2.6734730689274273e+00, 3.6808175887312227e+00, 1.507408744009727e+00),
        pValues = Vector(7.5070303558608421e-03, 2.3248728665841849e-04, 1.3170591886524421e-01),
        tau2 = 0e+00,
        fixedQ = 2.2509191700366843e-01,
        residualDf = 9
      ),
      Expected(
        policy = "DL-mKH",
        coefficients = Vector(3.1667953873333538e-01, 2.8420914896694671e-01, 3.3397481234123838e-01),
        standardErrors = Vector(1.1845248879218531e-01, 7.7213592392366706e-02, 2.2155557586382377e-01),
        covarianceRowMajor = Vector(1.4030992101062786e-02, 2.9833462700611026e-04, -1.4174794659790994e-02, 2.9833462700611026e-04, 5.9619388501345504e-03, -3.1720944390470972e-03, -1.4174794659790994e-02, -3.1720944390470972e-03, 4.9086873196350571e-02),
        statistics = Vector(2.6734730689274273e+00, 3.6808175887312227e+00, 1.507408744009727e+00),
        pValues = Vector(2.5477059449317149e-02, 5.0690383136246901e-03, 1.6597587773822073e-01),
        tau2 = 0e+00,
        fixedQ = 2.2509191700366843e-01,
        residualDf = 9
      ),
      Expected(
        policy = "PM-mKH",
        coefficients = Vector(3.1667953873333538e-01, 2.8420914896694671e-01, 3.3397481234123838e-01),
        standardErrors = Vector(1.1845248879218531e-01, 7.7213592392366706e-02, 2.2155557586382377e-01),
        covarianceRowMajor = Vector(1.4030992101062786e-02, 2.9833462700611026e-04, -1.4174794659790994e-02, 2.9833462700611026e-04, 5.9619388501345504e-03, -3.1720944390470972e-03, -1.4174794659790994e-02, -3.1720944390470972e-03, 4.9086873196350571e-02),
        statistics = Vector(2.6734730689274273e+00, 3.6808175887312227e+00, 1.507408744009727e+00),
        pValues = Vector(2.5477059449317149e-02, 5.0690383136246901e-03, 1.6597587773822073e-01),
        tau2 = 0e+00,
        fixedQ = 2.2509191700366843e-01,
        residualDf = 9
      )
      )
    )
  )
