package scalafim.fmri.laws.profile.spike

/** Causal Gaussian kernel `h(t) = exp(-(t - tau)^2 / (2 sigma^2))` for
  * `t >= 0`, in the chart `theta = (tau, log sigma)`.
  *
  * The kernel is deliberately unnormalised: at `alpha = 0` shape scoring is
  * invariant to a positive scale, so normalisation belongs to amplitude
  * readout, not to the decoder. Spike code (PHRF-25); not a public API.
  */
object SpikeGaussianFamily:

  /** Number of shape parameters. */
  val Dimension: Int = 2

  /** Jet layout, component-major: value, d/dtau, d/dv, d2/dtau2, d2/dtau dv,
    * d2/dv2 with `v = log sigma`.
    */
  val JetComponents: Int = 6

  final case class Domain(tauMin: Double, tauMax: Double, logSdMin: Double, logSdMax: Double):
    def clampTau(tau: Double): Double = math.min(tauMax, math.max(tauMin, tau))
    def clampLogSd(v: Double): Double = math.min(logSdMax, math.max(logSdMin, v))
    def onBoundary(tau: Double, v: Double, tol: Double = 1e-9): Boolean =
      tau <= tauMin + tol || tau >= tauMax - tol || v <= logSdMin + tol || v >= logSdMax - tol

  /** Peak latency and full width at half maximum implied by the chart. */
  def peakLatency(tau: Double): Double = tau
  def fwhm(logSd: Double): Double = 2.0 * math.sqrt(2.0 * math.log(2.0)) * math.exp(logSd)

  /** Kernel values at `times` into `out(0 until n)`.
    *
    * On a uniform grid the Gaussian is generated by a two-term recurrence
    * (`h_{i+1} = h_i q_i`, `q_{i+1} = q_i rho`) from two exponentials instead
    * of one per sample; non-uniform grids fall back to direct evaluation.
    */
  def valueInto(times: Array[Double], tau: Double, logSd: Double, out: Array[Double]): Unit =
    val n = times.length
    val inv2 = math.exp(-2.0 * logSd)
    if isUniform(times) then
      val dt = times(1) - times(0)
      val u0 = times(0) - tau
      var h = math.exp(-0.5 * u0 * u0 * inv2)
      var q = math.exp(-(u0 * dt + 0.5 * dt * dt) * inv2)
      val rho = math.exp(-dt * dt * inv2)
      var i = 0
      while i < n do
        out(i) = if h < 1e-300 then 0.0 else h
        h *= q
        q *= rho
        i += 1
    else
      var i = 0
      while i < n do
        val t = times(i)
        if t < 0.0 then out(i) = 0.0
        else
          val u = t - tau
          out(i) = math.exp(-0.5 * u * u * inv2)
        i += 1

  private def isUniform(times: Array[Double]): Boolean =
    times.length >= 2 && times(0) >= 0.0 && {
      val dt = times(1) - times(0)
      math.abs((times(times.length - 1) - times(0)) - dt * (times.length - 1)) < 1e-9 * math.max(1.0, times(times.length - 1))
    }

  /** Value and first parameter derivatives only (three components). */
  def firstOrderJetInto(times: Array[Double], tau: Double, logSd: Double, out: Array[Double]): Unit =
    jetComponentsInto(times, tau, logSd, out, 3)

  /** Kernel value and first/second parameter derivatives at `times`, written
    * component-major into `out` of length `JetComponents * n`.
    */
  def jetInto(times: Array[Double], tau: Double, logSd: Double, out: Array[Double]): Unit =
    jetComponentsInto(times, tau, logSd, out, JetComponents)

  private def jetComponentsInto(times: Array[Double], tau: Double, logSd: Double, out: Array[Double], components: Int): Unit =
    val n = times.length
    val inv2 = math.exp(-2.0 * logSd)
    valueInto(times, tau, logSd, out)
    var i = 0
    while i < n do
      val h = out(i)
      val u = times(i) - tau
      val a = u * inv2
      val a2 = u * a
      out(n + i) = h * a
      out(2 * n + i) = h * a2
      if components > 3 then
        out(3 * n + i) = h * (a * a - inv2)
        out(4 * n + i) = h * (a2 * a - 2.0 * a)
        out(5 * n + i) = h * (a2 * a2 - 2.0 * a2)
      i += 1
