package scalafim.multivar

/** Generated by tools/oracles/lowrankmodels/render_scala_encoding_fixture.py.
  * Source: modules/multivar/shared/src/test/resources/lowrankmodels/encoding-v1.json
  */
final case class LowRankModelsEncodingOracleCase(
    id: String,
    loss: String,
    rank: Int,
    data: Vector[Double],
    observed: Vector[Boolean],
    decoder: Vector[Vector[Double]],
    penalty: LowRankModelsOraclePenalty,
    initial: Vector[Double],
    solution: Vector[Double],
    naturalParameters: Vector[Double],
    decoded: Vector[Double],
    observedEntryLoss: Double,
    rowPenalty: Double,
    totalObjective: Double,
    proxGradientResidual: Double,
    residualStep: Double,
    iterations: Int,
    objectiveTrajectory: Vector[Double]
)

object LowRankModelsEncodingOracleFixtureData:
  val schemaVersion: String = "scalafim.lowrankmodels.encoding-oracle.v1"
  val provenance: LowRankModelsOracleProvenance = LowRankModelsOracleProvenance(
    repository = "https://github.com/madeleineudell/LowRankModels.jl.git",
    commit = "a18f0df45f1a6ce37634bf4e347062b6090397eb",
    juliaVersion = "1.6.7",
    packageVersion = "1.1.1"
  )
  val cases: Vector[LowRankModelsEncodingOracleCase] = Vector(
    LowRankModelsEncodingOracleCase(
      id = "quadratic-dense-ridge",
      loss = "quadratic",
      rank = 2,
      data = Vector(0.7, -1.2, 0.4),
      observed = Vector(true, true, true),
      decoder = Vector(Vector(1.0, 0.2), Vector(-0.4, 0.8), Vector(0.3, -0.5)),
      penalty = LowRankModelsOraclePenalty(
        LowRankModelsOraclePenaltyKind.SquaredFrobenius,
        0.3,
        0.15
      ),
      initial = Vector(0.5, -0.5),
      solution = Vector(0.7218586387467102, -0.6708115183188958),
      naturalParameters = Vector(0.587696335082931, -0.8253926701538008, 0.5519633507834609),
      decoded = Vector(0.587696335082931, -0.8253926701538008, 0.5519633507834609),
      observedEntryLoss = 0.08801781235482078,
      rowPenalty = 0.14566019811638337,
      totalObjective = 0.23367801047120415,
      proxGradientResidual = 6.2259918578685706e-12,
      residualStep = 0.4541284403669724,
      iterations = 40,
      objectiveTrajectory = Vector(0.2999999999999999, 0.2406060217790511, 0.2344410452424318, 0.2337744943261981, 0.23369394525498702, 0.2336816183538588, 0.23367902270717483, 0.23367832298376623, 0.23367811031418342, 0.23367804272915027, 0.23367802093052564, 0.23367801386634232, 0.23367801157366774, 0.2336780108292338, 0.23367801058747975, 0.23367801050896686, 0.23367801048346837, 0.2336780104751872, 0.23367801047249773, 0.23367801047162426, 0.23367801047134062, 0.23367801047124842, 0.23367801047121856, 0.23367801047120884, 0.2336780104712057, 0.23367801047120462, 0.2336780104712043, 0.2336780104712042, 0.23367801047120412, 0.23367801047120415, 0.23367801047120415, 0.23367801047120415, 0.23367801047120415, 0.23367801047120412, 0.23367801047120415, 0.23367801047120418, 0.23367801047120418, 0.23367801047120415, 0.23367801047120418, 0.2336780104712042, 0.23367801047120415)
    ),
    LowRankModelsEncodingOracleCase(
      id = "quadratic-sparse-l1",
      loss = "quadratic",
      rank = 1,
      data = Vector(0.9, 0.0, -0.2, 1.1),
      observed = Vector(true, false, true, true),
      decoder = Vector(Vector(1.0), Vector(-0.7), Vector(0.4), Vector(1.2)),
      penalty = LowRankModelsOraclePenalty(
        LowRankModelsOraclePenaltyKind.L1,
        0.15,
        0.15
      ),
      initial = Vector(-0.3),
      solution = Vector(0.7653846153835501),
      naturalParameters = Vector(0.7653846153835501, -0.535769230768485, 0.30615384615342006, 0.91846153846026),
      decoded = Vector(0.7653846153835501, -0.535769230768485, 0.30615384615342006, 0.91846153846026),
      observedEntryLoss = 0.1536346153847752,
      rowPenalty = 0.1148076923075325,
      totalObjective = 0.26844230769230776,
      proxGradientResidual = 2.769950374569835e-12,
      residualStep = 0.38076923076923075,
      iterations = 6,
      objectiveTrajectory = Vector(1.8339999999999999, 0.26858986346153846, 0.2684423224478847, 0.26844230769378324, 0.26844230769230787, 0.2684423076923077, 0.26844230769230776)
    ),
    LowRankModelsEncodingOracleCase(
      id = "logistic-sparse-ridge",
      loss = "logistic",
      rank = 2,
      data = Vector(1.0, 0.0, 1.0),
      observed = Vector(true, false, true),
      decoder = Vector(Vector(1.0, 0.2), Vector(-0.3, 0.7), Vector(-0.5, 0.9)),
      penalty = LowRankModelsOraclePenalty(
        LowRankModelsOraclePenaltyKind.SquaredFrobenius,
        0.25,
        0.125
      ),
      initial = Vector(0.2, -0.4),
      solution = Vector(0.5994770489372953, 1.3003973806653735),
      naturalParameters = Vector(0.85955652507037, 0.7304350517845728, 0.8706191181301886),
      decoded = Vector(0.7025679913957473, 0.6749007344405188, 0.7048745072705944),
      observedEntryLoss = 0.7027485934385498,
      rowPenalty = 0.25630075998049157,
      totalObjective = 0.9590493534190413,
      proxGradientResidual = 8.25935994771311e-12,
      residualStep = 1.8857142857142857,
      iterations = 34,
      objectiveTrajectory = Vector(1.6093133190698907, 1.0869923560504495, 0.9863876676737631, 0.965192170663133, 0.9604620018323344, 0.9593777764074358, 0.9591261051935063, 0.9590673348871219, 0.959053571184704, 0.9590503433175519, 0.9590495858103945, 0.9590494079832317, 0.959049366231241, 0.9590493564275644, 0.9590493541255047, 0.9590493535849348, 0.9590493534579969, 0.959049353428189, 0.9590493534211894, 0.9590493534195458, 0.9590493534191598, 0.9590493534190692, 0.9590493534190477, 0.959049353419043, 0.9590493534190416, 0.9590493534190414, 0.9590493534190414, 0.9590493534190412, 0.9590493534190414, 0.9590493534190413, 0.9590493534190414, 0.9590493534190412, 0.9590493534190412, 0.9590493534190412, 0.9590493534190413)
    )
  )
