package scalafim.multivar

/** Generated by tools/oracles/lowrankmodels/render_scala_fixture.py.
  * Source: modules/multivar/shared/src/test/resources/lowrankmodels/objective-v1.json
  */
final case class LowRankModelsOracleProvenance(
    repository: String,
    commit: String,
    juliaVersion: String,
    packageVersion: String
)

enum LowRankModelsOraclePenaltyKind:
  case NoPenalty
  case L1
  case SquaredFrobenius

final case class LowRankModelsOraclePenalty(
    kind: LowRankModelsOraclePenaltyKind,
    scalaWeight: Double,
    juliaScale: Double
)

final case class LowRankModelsOracleObjective(
    observedEntryLoss: Double,
    rowPenalty: Double,
    decoderPenalty: Double,
    total: Double,
    responseConstant: Double
)

sealed trait LowRankModelsOracleCase:
  def id: String
  def rank: Int
  def rowCodes: Vector[Vector[Double]]
  def decoder: Vector[Vector[Double]]
  def rowPenalty: LowRankModelsOraclePenalty
  def decoderPenalty: LowRankModelsOraclePenalty
  def objective: LowRankModelsOracleObjective

final case class LowRankModelsScalarOracleCase(
    id: String,
    loss: String,
    rank: Int,
    data: Vector[Vector[Double]],
    observed: Vector[Vector[Boolean]],
    rowCodes: Vector[Vector[Double]],
    decoder: Vector[Vector[Double]],
    naturalParameters: Vector[Vector[Double]],
    naturalGradients: Vector[Vector[Option[Double]]],
    decoded: Vector[Vector[Double]],
    rowPenalty: LowRankModelsOraclePenalty,
    decoderPenalty: LowRankModelsOraclePenalty,
    objective: LowRankModelsOracleObjective
) extends LowRankModelsOracleCase

final case class LowRankModelsCategoricalOracleCase(
    id: String,
    levels: Int,
    rank: Int,
    data: Vector[Int],
    observed: Vector[Boolean],
    rowCodes: Vector[Vector[Double]],
    decoder: Vector[Vector[Double]],
    naturalParameters: Vector[Vector[Double]],
    naturalGradients: Vector[Vector[Option[Double]]],
    decoded: Vector[Vector[Double]],
    rowPenalty: LowRankModelsOraclePenalty,
    decoderPenalty: LowRankModelsOraclePenalty,
    objective: LowRankModelsOracleObjective
) extends LowRankModelsOracleCase

object LowRankModelsOracleFixtureData:
  val schemaVersion: String = "scalafim.lowrankmodels.oracle.v1"
  val provenance: LowRankModelsOracleProvenance = LowRankModelsOracleProvenance(
    repository = "https://github.com/madeleineudell/LowRankModels.jl.git",
    commit = "a18f0df45f1a6ce37634bf4e347062b6090397eb",
    juliaVersion = "1.6.7",
    packageVersion = "1.1.1"
  )
  val cases: Vector[LowRankModelsOracleCase] = Vector(
    LowRankModelsScalarOracleCase(
      id = "quadratic-masked-rank2",
      loss = "quadratic",
      rank = 2,
      data = Vector(Vector(1.0, -0.5), Vector(2.0, 0.0), Vector(-1.0, 1.5)),
      observed = Vector(Vector(true, true), Vector(true, false), Vector(true, true)),
      rowCodes = Vector(Vector(0.5, -0.2), Vector(1.0, 0.3), Vector(-0.4, 0.8)),
      decoder = Vector(Vector(0.7, -0.1), Vector(-0.3, 0.9)),
      naturalParameters = Vector(Vector(0.37, -0.33), Vector(0.6699999999999999, -0.02999999999999997), Vector(-0.36, 0.8400000000000001)),
      naturalGradients = Vector(Vector(Some(-0.63), Some(0.16999999999999998)), Vector(Some(-1.33), None), Vector(Some(0.64), Some(-0.6599999999999999))),
      decoded = Vector(Vector(0.37, -0.33), Vector(0.6699999999999999, -0.02999999999999997), Vector(-0.36, 0.8400000000000001)),
      rowPenalty = LowRankModelsOraclePenalty(LowRankModelsOraclePenaltyKind.L1, 0.2, 0.2),
      decoderPenalty = LowRankModelsOraclePenalty(LowRankModelsOraclePenaltyKind.SquaredFrobenius, 0.4, 0.2),
      objective = LowRankModelsOracleObjective(1.5199500000000001, 0.6400000000000001, 0.28, 2.4399500000000005, 0.0)
    ),
    LowRankModelsScalarOracleCase(
      id = "logistic-masked-rank2",
      loss = "logistic",
      rank = 2,
      data = Vector(Vector(1.0, 0.0), Vector(0.0, 1.0), Vector(1.0, 1.0), Vector(0.0, 0.0)),
      observed = Vector(Vector(true, true), Vector(true, false), Vector(true, true), Vector(false, true)),
      rowCodes = Vector(Vector(0.4, -0.3), Vector(0.8, 0.2), Vector(-0.5, 0.7), Vector(0.1, 0.6)),
      decoder = Vector(Vector(0.9, -0.4), Vector(-0.2, 0.8)),
      naturalParameters = Vector(Vector(0.48000000000000004, -0.32), Vector(0.6400000000000001, 0.0), Vector(-0.73, 0.6599999999999999), Vector(-0.14999999999999997, 0.45999999999999996)),
      naturalGradients = Vector(Vector(Some(-0.382252125230751), Some(0.42067574785125056)), Vector(Some(0.6547534606063193), None), Vector(Some(-0.6748052725823135), Some(-0.3407396115486146)), Vector(None, Some(0.6130141761393355))),
      decoded = Vector(Vector(0.617747874769249, 0.42067574785125056), Vector(0.6547534606063193, 0.5), Vector(0.3251947274176865, 0.6592603884513855), Vector(0.46257015465625045, 0.6130141761393355)),
      rowPenalty = LowRankModelsOraclePenalty(LowRankModelsOraclePenaltyKind.L1, 0.2, 0.2),
      decoderPenalty = LowRankModelsOraclePenalty(LowRankModelsOraclePenaltyKind.SquaredFrobenius, 0.4, 0.2),
      objective = LowRankModelsOracleObjective(4.580399349953536, 0.72, 0.33000000000000007, 5.630399349953536, 0.0)
    ),
    LowRankModelsScalarOracleCase(
      id = "poisson-masked-rank2",
      loss = "poisson",
      rank = 2,
      data = Vector(Vector(0.0, 2.0), Vector(3.0, 1.0), Vector(1.0, 4.0)),
      observed = Vector(Vector(true, true), Vector(true, false), Vector(true, true)),
      rowCodes = Vector(Vector(0.2, -0.1), Vector(0.6, 0.3), Vector(-0.2, 0.5)),
      decoder = Vector(Vector(0.4, -0.2), Vector(0.1, 0.7)),
      naturalParameters = Vector(Vector(0.10000000000000002, -0.04999999999999999), Vector(0.18, 0.27), Vector(-0.18000000000000002, 0.32999999999999996)),
      naturalGradients = Vector(Vector(Some(1.1051709180756477), Some(-1.048770575499286)), Vector(Some(-1.8027826368781898), None), Vector(Some(-0.164729788588728), Some(-2.60903187153622))),
      decoded = Vector(Vector(1.1051709180756477, 0.951229424500714), Vector(1.1972173631218102, 1.3099644507332473), Vector(0.835270211411272, 1.3909681284637803)),
      rowPenalty = LowRankModelsOraclePenalty(LowRankModelsOraclePenaltyKind.L1, 0.2, 0.2),
      decoderPenalty = LowRankModelsOraclePenalty(LowRankModelsOraclePenaltyKind.SquaredFrobenius, 0.4, 0.2),
      objective = LowRankModelsOracleObjective(4.127164717177006, 0.38, 0.14, 4.647164717177006, 0.2273086716037822)
    ),
    LowRankModelsCategoricalOracleCase(
      id = "categorical-masked-rank2",
      levels = 3,
      rank = 2,
      data = Vector(0, 2, 1, 0),
      observed = Vector(true, false, true, true),
      rowCodes = Vector(Vector(0.5, -0.2), Vector(1.0, 0.3), Vector(-0.4, 0.8), Vector(0.2, 0.6)),
      decoder = Vector(Vector(0.7, -0.1), Vector(-0.3, 0.9), Vector(0.2, -0.5)),
      naturalParameters = Vector(Vector(0.37, -0.33, 0.2), Vector(0.6699999999999999, -0.02999999999999997, 0.05000000000000002), Vector(-0.36, 0.8400000000000001, -0.48000000000000004), Vector(0.07999999999999999, 0.48000000000000004, -0.26)),
      naturalGradients = Vector(Vector(Some(-0.5726952468506682), Some(0.21219326065417418), Some(0.36050198619649404)), Vector(None, None, None), Vector(Some(0.19204778667171205), Some(-0.36237889349715036), Some(0.17033110682543834)), Vector(Some(-0.687850682239502), Some(0.4656720615869838), Some(0.22217862065251812))),
      decoded = Vector(Vector(0.4273047531493318, 0.21219326065417418, 0.36050198619649404), Vector(0.4915140730843876, 0.2440786653003637, 0.2644072616152487), Vector(0.19204778667171202, 0.6376211065028496, 0.17033110682543834), Vector(0.31214931776049804, 0.4656720615869838, 0.22217862065251812)),
      rowPenalty = LowRankModelsOraclePenalty(LowRankModelsOraclePenaltyKind.L1, 0.2, 0.2),
      decoderPenalty = LowRankModelsOraclePenalty(LowRankModelsOraclePenaltyKind.SquaredFrobenius, 0.4, 0.2),
      objective = LowRankModelsOracleObjective(2.4645424848099573, 0.8000000000000002, 0.338, 3.6025424848099576, 0.0)
    )
  )
