package scalafim.fmri.mvpa

import gale.linalg.{DMat, DVec, Matrix, Vec}

/** Fixed base-R reference for the canonical-effect estimand. Generated by
  * tools/r-parity/generate_canonical_effect_fixtures.R. X and Z are time-by-column; C is contrast-by-design.
  */
object CanonicalEffectReferenceFixtures:
  final case class RunReference(
      response: DMat,
      cross: DMat,
      total: DMat,
      effect: DMat,
      residual: DMat
  )

  final case class FoldReference(
      heldOutRun: Int,
      direction: DVec,
      trainingRoot: Double,
      ridge: Double,
      heldOutRoot: Double,
      heldOutCorrelation: Double
  )

  val analyticEffect: DMat = matrixFromRows(
    Vector(
      Vector(4, 2),
      Vector(2, 1)
    )
  )
  val analyticResidual: DMat = matrixFromRows(
    Vector(
      Vector(2, 0.0),
      Vector(0.0, 3)
    )
  )
  val analyticDirection: DVec = vectorFromArray(Array(0.65465367070797709, 0.21821789023599236))
  val analyticRoot: Double = 2.3333333333333335
  val analyticCorrelation: Double = 0.83666002653407556

  val contrast: DMat = matrixFromRows(
    Vector(
      Vector(0.0, 1, 0.0)
    )
  )
  val design: DMat = matrixFromRows(
    Vector(
      Vector(1, -1, -1),
      Vector(1, -1, -0.7142857142857143),
      Vector(1, 1, -0.4285714285714286),
      Vector(1, 1, -0.1428571428571429),
      Vector(1, -1, 0.14285714285714279),
      Vector(1, -1, 0.42857142857142838),
      Vector(1, 1, 0.71428571428571419),
      Vector(1, 1, 1)
    )
  )
  val expectedXtX: DMat = matrixFromRows(
    Vector(
      Vector(8, 0.0, -4.4408920985006262e-16),
      Vector(0.0, 8, 2.2857142857142856),
      Vector(-4.4408920985006262e-16, 2.2857142857142856, 3.4285714285714284)
    )
  )
  val ridgeFraction: Double = 0.02

  val runs: Vector[RunReference] =
    Vector(
      RunReference(
        response = matrixFromRows(
          Vector(
            Vector(-0.90000000000000013, 0.10000000000000006, -0.14999999999999997),
            Vector(-1.142857142857143, 0.5, -0.092857142857142833),
            Vector(0.91428571428571426, -0.85000000000000009, 0.21428571428571425),
            Vector(0.67142857142857149, -0.55000000000000004, 0.47142857142857142),
            Vector(-1.0214285714285714, 0.75, -0.47142857142857142),
            Vector(-0.56428571428571428, 0.64999999999999991, -0.56428571428571428),
            Vector(0.99285714285714288, -0.20000000000000009, 0.49285714285714288),
            Vector(1.05, -0.40000000000000008, 0.099999999999999978)
          )
        ),
        cross = matrixFromRows(
          Vector(
            Vector(-2.2204460492503131e-16, 7.2571428571428571, 2.6000000000000005),
            Vector(-2.7755575615628914e-16, -4, -0.17142857142857171),
            Vector(0.0, 2.5571428571428574, 0.20000000000000001)
          )
        ),
        total = matrixFromRows(
          Vector(
            Vector(6.8528571428571432, -3.5592857142857146, 2.1478571428571427),
            Vector(-3.5592857142857146, 2.4700000000000002, -1.3617857142857144),
            Vector(2.1478571428571427, -1.3617857142857144, 1.092857142857143)
          )
        ),
        effect = matrixFromRows(
          Vector(
            Vector(4.7114845938375352, -3.3142857142857145, 2.0673669467787117),
            Vector(-3.3142857142857141, 2.3314285714285714, -1.4542857142857144),
            Vector(2.0673669467787117, -1.4542857142857144, 0.90714635854341763)
          )
        ),
        residual = matrixFromRows(
          Vector(
            Vector(0.16970588235294137, -0.11500000000000021, -0.071176470588235841),
            Vector(-0.11500000000000021, 0.13000000000000034, 0.10250000000000004),
            Vector(-0.071176470588235841, 0.10250000000000004, 0.17404411764705863)
          )
        )
      ),
      RunReference(
        response = matrixFromRows(
          Vector(
            Vector(-0.95000000000000007, 0.39999999999999991, -0.40000000000000002),
            Vector(-0.70714285714285707, 0.32857142857142851, -0.11428571428571427),
            Vector(0.58571428571428574, -0.69285714285714284, 0.3214285714285714),
            Vector(0.9285714285714286, -0.86428571428571421, 0.10714285714285712),
            Vector(-0.62857142857142856, 0.56428571428571428, -0.057142857142857106),
            Vector(-0.88571428571428568, 0.99285714285714277, -0.37142857142857144),
            Vector(0.90714285714285714, -0.52857142857142858, 0.16428571428571431),
            Vector(0.75, -0.19999999999999996, 0.34999999999999998)
          )
        ),
        cross = matrixFromRows(
          Vector(
            Vector(3.3306690738754696e-16, 6.3428571428571434, 2),
            Vector(-1.1102230246251565e-16, -4.5714285714285712, -0.2857142857142857),
            Vector(5.5511151231257827e-17, 1.8857142857142857, 0.62857142857142867)
          )
        ),
        total = matrixFromRows(
          Vector(
            Vector(5.1728571428571426, -3.6842857142857142, 1.5249999999999999),
            Vector(-3.6842857142857142, 3.1185714285714283, -1.0707142857142857),
            Vector(1.5249999999999999, -1.0707142857142857, 0.57857142857142851)
          )
        ),
        effect = matrixFromRows(
          Vector(
            Vector(3.8750140056022424, -3.3887955182072833, 1.1345098039215689),
            Vector(-3.3887955182072838, 2.9635854341736696, -0.99215686274509807),
            Vector(1.1345098039215689, -0.99215686274509818, 0.33215686274509809)
          )
        ),
        residual = matrixFromRows(
          Vector(
            Vector(0.13117647058823412, -0.12882352941176434, 0.023823529411764355),
            Vector(-0.12882352941176389, 0.13117647058823501, -0.026176470588235246),
            Vector(0.023823529411764355, -0.026176470588235468, 0.13117647058823517)
          )
        )
      ),
      RunReference(
        response = matrixFromRows(
          Vector(
            Vector(-1.2, 2.7755575615628914e-17, 0.0),
            Vector(-1.4285714285714286, 0.33571428571428574, -0.3571428571428571),
            Vector(1.0928571428571427, -0.62857142857142867, 0.58571428571428574),
            Vector(0.96428571428571419, -0.29285714285714287, 0.22857142857142859),
            Vector(-0.96428571428571419, 0.54285714285714282, -0.47857142857142859),
            Vector(-1.0428571428571429, 0.3785714285714285, -0.33571428571428574),
            Vector(1.4285714285714286, -0.085714285714285771, 0.10714285714285718),
            Vector(1.1500000000000001, -0.25, 0.25)
          )
        ),
        cross = matrixFromRows(
          Vector(
            Vector(0.0, 9.2714285714285722, 3.2000000000000002),
            Vector(-3.0531133177191805e-16, -2.5142857142857147, -1.1102230246251565e-16),
            Vector(8.3266726846886741e-17, 2.342857142857143, 0.085714285714285743)
          )
        ),
        total = matrixFromRows(
          Vector(
            Vector(10.985714285714286, -2.7771428571428576, 2.6228571428571428),
            Vector(-2.7771428571428576, 1.1014285714285714, -1.0135714285714286),
            Vector(2.6228571428571428, -1.0135714285714286, 0.93857142857142883)
          )
        ),
        effect = matrixFromRows(
          Vector(
            Vector(7.8676505602240931, -2.771260504201682, 2.5193277310924378),
            Vector(-2.7712605042016811, 0.97613445378151287, -0.88739495798319346),
            Vector(2.5193277310924378, -0.88739495798319357, 0.80672268907563038)
          )
        ),
        residual = matrixFromRows(
          Vector(
            Vector(0.13139705882352537, -0.0058823529411755615, 0.023529411764704911),
            Vector(-0.0058823529411760056, 0.12529411764705856, -0.12617647058823511),
            Vector(0.023529411764705355, -0.12617647058823511, 0.12970588235294134)
          )
        )
      )
    )

  val folds: Vector[FoldReference] =
    Vector(
      FoldReference(
        heldOutRun = 0,
        direction = vectorFromArray(Array(1.9479516833805883, 0.20735275171652526, 0.37060137137310328)),
        trainingRoot = 44.893919986899007,
        ridge = 0.0051995098039215306,
        heldOutRoot = 36.850057104696077,
        heldOutCorrelation = 0.98670155599348053
      ),
      FoldReference(
        heldOutRun = 1,
        direction = vectorFromArray(Array(1.7081017444730848, -0.05025719372655172, 0.83919832185458376)),
        trainingRoot = 52.308195326961197,
        ridge = 0.005734313725490171,
        heldOutRoot = 27.224609879838816,
        heldOutCorrelation = 0.9821252092225311
      ),
      FoldReference(
        heldOutRun = 2,
        direction = vectorFromArray(Array(1.4332483545445247, -0.36759957603601767, 0.89400907746045211)),
        trainingRoot = 36.220962969190857,
        ridge = 0.0057818627450980306,
        heldOutRoot = 49.816358575475654,
        heldOutCorrelation = 0.99011176013114099
      )
    )

  val meanHeldOutRoot: Double = 37.96367518667018
  val rootToCorrelationOfMean: Double = 0.98708412503833465

  private def matrixFromRows(rows: Vector[Vector[Double]]): DMat =
    Matrix.tabulate(rows.length, rows.head.length): (row, column) =>
      rows(row)(column)

  private def vectorFromArray(values: Array[Double]): DVec =
    val builder = Vec.newBuilder(values.length)
    var position = 0
    while position < values.length do
      builder(position) = values(position)
      position += 1
    builder.result()
