package scalafim.fmri.mvpa

object ConstrainedCanonicalReferenceFixtures:
  final case class Fold(
      direction: Vector[Double],
      trainingRoot: Double,
      ridge: Double,
      heldOutRoot: Double
  )

  /** Independent active-face base-R oracle generated by tools/r-parity/generate_constrained_canonical_fixtures.R.
    */
  val folds: Vector[Fold] = Vector(
    Fold(
      Vector(1.9479516833805883, 0.20735275171652526, 0.37060137137310328),
      44.893919986899007,
      0.0051995098039215306,
      36.850057104696077
    ),
    Fold(
      Vector(1.729557586555297, 0.0, 0.84619068194331404),
      52.281618163267552,
      0.005734313725490171,
      27.245772663817224
    ),
    Fold(
      Vector(1.7257864366468352, 0.0, 0.85239503005897954),
      35.894204718195027,
      0.0057818627450980306,
      56.651231335688571
    )
  )

  val meanHeldOutRoot: Double = 40.249020368067292
  val rootToCorrelationOfMean: Double = 0.98780413039174098
