package scalafim.fmri.mvpa

import gale.linalg.DMat

/** Fixed base-R reference for crossvalidated squared Mahalanobis distance. Generated by
  * tools/r-parity/generate_crossvalidated_rdm_fixtures.R.
  */
object CrossvalidatedRdmReferenceFixtures:
  val effectLabels: Vector[String] = Vector("a", "b", "c")
  val featureLabels: Vector[String] = Vector("v1", "v2")
  val partitionLabels: Vector[String] = Vector("run-1", "run-2")
  val pairOrder: Vector[(String, String)] = Vector("a" -> "b", "a" -> "c", "b" -> "c")
  val partitionPatterns: Vector[DMat] = Vector(
    GaleTestMatrix.fromRows(
      Vector(
        Vector(1, 0.0),
        Vector(-1, 0.0),
        Vector(0.0, 2)
      )
    ),
    GaleTestMatrix.fromRows(
      Vector(
        Vector(-1, 0.0),
        Vector(1, 0.0),
        Vector(0.0, 1)
      )
    )
  )
  val naiveSquaredDistances: Vector[Double] = Vector(4, 3.5, 3.5)
  val rawCrossvalidatedDistances: Vector[Double] = Vector(-4, 1, 1)
  val perFeatureCrossvalidatedDistances: Vector[Double] = Vector(-2, 0.5, 0.5)
