package scalafim.phrfcmp.run

import java.nio.file.{Files, Path, Paths}

import scala.jdk.CollectionConverters.*

import scalafim.fmri.fit.{ResponseBlock, RidgeLssFit}
import scalafim.phrfcmp.ingest.Matrix
import scalafim.phrfcmp.prep.NativeArm

/**
  * S11 trial parity on the committed R fixtures (`tools/phrf-comparison/parity`, generated by
  * `generate_parity_fixtures.R` with R session info in `meta.json`): the Scala trial arms against `fmrilss::lsa` and
  * `fmrilss::lss` (1e-8) and rLSS against the R dense penalised solve (1e-10), for both whitening conventions
  * (`exact_first` primary, `identity_first` secondary) and both trial cells (`tx` TR-aligned, `ts` 0.1 s onsets).
  * Inputs are the fixtures' own whitened `Y`, `X_trial`, `F`; relative error is `max|a - b| / max|b|`, the S11 definition.
  * S11 owns the formal gate; this suite wires the Scala side so the S4 estimators are held to the R numbers now.
  */
class S11TrialParitySuite extends munit.FunSuite:

  private val TolFit = 1e-8
  private val TolRlss = 1e-10
  private val RunLen = 150

  private def fixtures: Path =
    def find(p: Path): Option[Path] =
      if p == null then None
      else
        val d = p.resolve("tools/phrf-comparison/parity/fixtures")
        if Files.isDirectory(d) then Some(d) else find(p.getParent)
    find(Paths.get(sys.props("user.dir")).toAbsolutePath).getOrElse(fail("S11 fixtures directory not found"))

  private def lines(p: Path): Vector[Array[String]] =
    Files.readAllLines(p).asScala.toVector.filter(_.nonEmpty).map(_.split(",", -1))

  /** Numeric CSV with a header; `labelled` drops the first (row-name) column. */
  private def csv(p: Path, labelled: Boolean = false): Matrix =
    val rows = lines(p).drop(1).map(r => (if labelled then r.drop(1) else r).map(_.toDouble))
    Matrix.of(rows.length, rows.head.length, rows.flatten.toArray).fold(e => fail(e.message), identity)

  private def column(p: Path, name: String): Vector[String] =
    val all = lines(p)
    val ix = all.head.indexOf(name)
    assert(ix >= 0, s"no column $name in $p")
    all.drop(1).map(_(ix))

  private def block(m: Matrix, from: Int, rows: Int): Matrix =
    Matrix.of(rows, m.cols, m.data.slice(from * m.cols, (from + rows) * m.cols)).fold(e => fail(e.message), identity)

  private def relErr(a: Matrix, b: Matrix): Double =
    assertEquals((a.rows, a.cols), (b.rows, b.cols))
    var diff = 0.0
    var scale = 0.0
    var i = 0
    while i < a.data.length do
      diff = math.max(diff, math.abs(a.data(i) - b.data(i)))
      scale = math.max(scale, math.abs(b.data(i)))
      i += 1
    diff / scale

  private def relErr(a: Seq[Double], b: Seq[Double]): Double =
    a.zip(b).map((x, y) => math.abs(x - y)).max / b.map(math.abs).max

  private final case class Cell(name: String, dir: Path, variant: String, vdir: Path, in: TrialNativeInputs)

  private def load(cell: String, variant: String): Cell =
    val dir = fixtures.resolve("trial").resolve(cell)
    val vdir = if variant == "primary" then dir else dir.resolve(variant)
    val y = csv(vdir.resolve("Y_white.csv"))
    val x = csv(vdir.resolve("X_trial_white.csv"))
    val f = csv(vdir.resolve("F_white.csv"))
    val runId = Array.tabulate(y.rows)(_ / RunLen)
    val trials = lines(dir.resolve("trials.csv")).drop(1)
    val trialRun = trials.map(_(1).toInt - 1).toArray
    val trialCond = trials.map(r => r(3).charAt(0) - 'A').toArray
    val in = TrialNativeInputs
      .of(y, x, f, runId, trialRun, trialCond, Array.tabulate(trials.length)(identity), Array.tabulate(trials.length)(identity))
      .fold(e => fail(e.message), identity)
    Cell(cell, dir, variant, vdir, in)

  private val results = scala.collection.mutable.ArrayBuffer.empty[String]
  private def record(label: String, err: Double, tol: Double): Unit =
    results += f"S11-TRIAL $label%-52s relerr=$err%.3e (tol $tol%.0e)"
    assert(err <= tol, s"$label relative error $err exceeds $tol")

  for
    cellName <- Seq("tx", "ts")
    variant <- Seq("primary", "identity_first")
  do
    lazy val c = load(cellName, variant)
    val tag = s"$cellName/$variant"

    test(s"$tag: LSA matches fmrilss::lsa at 1e-8"):
      val got = TrialNativeRunner.lsa(c.in).fold(e => fail(e.message), identity)
      record(s"$tag LSA vs fmrilss::lsa", relErr(got.amplitudes, csv(c.vdir.resolve("beta_lsa.csv"), labelled = true)), TolFit)

    test(s"$tag: LSS matches fmrilss::lss at 1e-8"):
      val got = TrialNativeRunner.lss(c.in).fold(e => fail(e.message), identity)
      record(s"$tag LSS vs fmrilss::lss", relErr(got.amplitudes, csv(c.vdir.resolve("beta_lss.csv"), labelled = true)), TolFit)

    test(s"$tag: the LSS-equivalence flag matches the R single-group dense solve at 1e-10 and fmrilss::lss at 1e-8"):
      val got = TrialNativeRunner.rlssAsLss(c.in).fold(e => fail(e.message), identity)
      record(s"$tag rLSS pooled r=0 vs R dense", relErr(got.amplitudes, csv(c.vdir.resolve("rlss_lss_equivalent.csv"), labelled = true)), TolRlss)
      record(s"$tag rLSS pooled r=0 vs fmrilss::lss", relErr(got.amplitudes, csv(c.vdir.resolve("beta_lss.csv"), labelled = true)), TolFit)

    test(s"$tag: condition-centred rLSS matches the R dense penalised solve at 1e-10 (amplitudes and deviations, six ridges)"):
      val ridges = column(c.vdir.resolve("rlss_ridges.csv"), "r").map(_.toDouble)
      val amp = csv(c.vdir.resolve("rlss_amp.csv"), labelled = true)
      val dev = csv(c.vdir.resolve("rlss_delta.csv"), labelled = true)
      val n = c.in.trials
      val prepared = TrialNativeRunner.prepareRlss(c.in, TrialNativeRunner.conditionGrouping(c.in)).fold(e => fail(e.message), identity)
      val y = ResponseBlock.fromMatrix(gale.linalg.DMat.tabulate(c.in.y.rows, c.in.y.cols)((r, v) => c.in.y(r, v))).fold(e => fail(e.message), identity)
      val proj = prepared.project(y).fold(e => fail(e.message), identity)
      def m(f: RidgeLssFit, which: String): Matrix =
        val d = if which == "amp" then f.amplitudes.value else f.deviations.value
        Matrix.of(d.rows, d.cols, Array.tabulate(d.rows * d.cols)(k => d(k / d.cols, k % d.cols))).fold(e => fail(e.message), identity)
      ridges.zipWithIndex.foreach { (r, k) =>
        val fit = proj.solve(r).fold(e => fail(e.message), identity)
        record(s"$tag rLSS amplitudes k=$k", relErr(m(fit, "amp"), block(amp, k * n, n)), TolRlss)
        record(s"$tag rLSS deviations k=$k", relErr(m(fit, "dev"), block(dev, k * n, n)), TolRlss)
      }

    test(s"$tag: q_i, the information-ratio grid and its inverse match the R closed forms"):
      val rq = column(c.vdir.resolve("df_q.csv"), "q").map(_.toDouble)
      val prepared = TrialNativeRunner.prepareRlss(c.in, TrialNativeRunner.conditionGrouping(c.in)).fold(e => fail(e.message), identity)
      val q = prepared.q
      record(s"$tag q_i vs R residual projection", relErr(q, rq), TolRlss)
      val ridges = lines(c.vdir.resolve("rlss_ridges.csv")).drop(1)
      record(s"$tag ratio(r_k) vs R", relErr(ridges.map(r => InformationRatio(q.toArray, r(2).toDouble)), ridges.map(_(3).toDouble)), 1e-10)
      val grid = lines(c.vdir.resolve("df_edf_grid.csv")).drop(1)
      record(s"$tag ratio(p_k) vs R", relErr(grid.map(r => InformationRatio(q.toArray, r(1).toDouble)), grid.map(_(2).toDouble)), 1e-10)
      val inverse = lines(c.vdir.resolve("df_inverse.csv")).drop(1)
      val got = inverse.map(r => InformationRatio.solvePenalty(q.toArray, r(0).toDouble).fold(e => fail(e.message), identity))
      record(s"$tag ratio inverse vs R uniroot", relErr(got, inverse.map(_(1).toDouble)), 1e-9)

    test(s"$tag: the tuned runner completes on the fixture (stimulus unseen: condition-mean prediction)"):
      val r = TrialNativeRunner.run(NativeArm.Rlss, c.in, RlssSettings(AlphaGrid.Pilot, PenaltyScale.Identity, Some(JointEdf.targets(c.in, AlphaGrid.Pilot)))).fold(e => fail(e.message), identity)
      assertEquals(r.fit.amplitudes.rows, c.in.trials)
      assert(r.fit.amplitudes.data.forall(_.isFinite))
      assertEquals(r.tuning.map(_.foldMaps.length), Some(3))

  override def afterAll(): Unit = results.foreach(println)
