# Independent R oracle for scalafim's complete B-spline HRF basis
# (`Hrfs.bspline(..., includeIntercept = true)`).
#
# Definition under test: a clamped B-spline basis of order degree + 1 on
# [0, span] with W = max(nBasis, degree + 1) columns and W - degree - 1
# interior knots uniformly spaced over the actual span. In R this is
#   splines::bs(t, knots = <uniform interior>, degree = degree,
#               intercept = TRUE, Boundary.knots = c(0, span))
#
# Usage (from the repository root):
#   Rscript docs/verification/hrf-complete-bspline-20261004/generate_complete_bspline_fixture.R \
#     [path/to/fmrihrf checkout]
#
# Writes the Scala fixture object and prints the fmrihrf cross-checks.

source("tools/r-parity/receipt_serialization.R")

args <- commandArgs(trailingOnly = TRUE)
fmrihrf_dir <- if (length(args) >= 1L) args[[1L]] else path.expand("~/code/fmrihrf")
out_path <- "modules/hrf/shared/src/test/scala/scalafim/fmri/hrf/fixtures/CompleteBsplineRFixtures.scala"

complete_bs <- function(t, span, n_basis, degree) {
  width <- max(n_basis, degree + 1L)
  intervals <- width - degree
  interior <- if (intervals > 1L) span * seq_len(intervals - 1L) / intervals else numeric(0)
  splines::bs(t, knots = interior, degree = degree, intercept = TRUE,
              Boundary.knots = c(0, span))
}

configs <- list(
  list(name = "cubic5_span24_5", n_basis = 5L, degree = 3L, span = 24.5),
  list(name = "cubic8_span24", n_basis = 8L, degree = 3L, span = 24),
  list(name = "quadratic6_span17_3", n_basis = 6L, degree = 2L, span = 17.3),
  list(name = "linear4_span10", n_basis = 4L, degree = 1L, span = 10),
  list(name = "quartic12_span32_75", n_basis = 12L, degree = 4L, span = 32.75),
  list(name = "cubic2_minimum_span7_75", n_basis = 2L, degree = 3L, span = 7.75)
)

# In-support times only: every knot, every midpoint, both endpoints and an
# irrational offset. Out-of-support zeros are a scalafim policy, not R's.
times_for <- function(span, width, degree) {
  intervals <- width - degree
  grid <- span * seq(0, 2L * intervals) / (2L * intervals)
  extra <- span * c(1 / pi, 1 / sqrt(2), exp(-1), 0.999999)
  # Canonicalize before evaluating so the serialized times are exactly the
  # points R evaluated at.
  canonicalize_receipt_numbers(sort(unique(c(grid, extra))))
}

fixtures <- lapply(configs, function(cfg) {
  width <- max(cfg$n_basis, cfg$degree + 1L)
  times <- times_for(cfg$span, width, cfg$degree)
  values <- complete_bs(times, cfg$span, cfg$n_basis, cfg$degree)
  stopifnot(ncol(values) == width)
  stopifnot(max(abs(rowSums(values) - 1)) < 1e-14)
  c(cfg, list(width = width, times = times, values = as.vector(t(values))))
})

fmt <- function(x) paste(receipt_format_number(x), collapse = ", ")

lines <- c(
  "package scalafim.fmri.hrf.fixtures",
  "",
  "// Generated by docs/verification/hrf-complete-bspline-20261004/generate_complete_bspline_fixture.R",
  sprintf("// with %s, splines %s. Do not edit by hand.", R.version.string,
          as.character(packageVersion("splines"))),
  sprintf("// Numbers: %s.", receipt_serialization_convention()),
  "//",
  "// Oracle: splines::bs(t, knots = uniform interior knots over span, degree,",
  "//   intercept = TRUE, Boundary.knots = c(0, span)).",
  "object CompleteBsplineRFixtures:",
  "",
  "  /** `values` is row-major: times.length rows by `width` columns. */",
  "  final case class Fixture(",
  "      name: String,",
  "      nBasis: Int,",
  "      degree: Int,",
  "      span: Double,",
  "      width: Int,",
  "      times: Vector[Double],",
  "      values: Vector[Double]",
  "  ):",
  "    def at(timeIndex: Int, basis: Int): Double = values(timeIndex * width + basis)",
  "",
  "  val all: Vector[Fixture] = Vector("
)
entries <- vapply(fixtures, function(f) {
  sprintf(paste0("    Fixture(name = \"%s\", nBasis = %d, degree = %d, span = %s, width = %d,\n",
                 "      times = Vector(%s),\n      values = Vector(%s))"),
          f$name, f$n_basis, f$degree, receipt_format_number(f$span), f$width,
          fmt(f$times), fmt(f$values))
}, character(1))
lines <- c(lines, paste(entries, collapse = ",\n"), "  )")
writeLines(lines, out_path)
cat("wrote ", out_path, "\n", sep = "")

# ---- fmrihrf cross-checks (reported in the receipt; not part of the fixture) ----
cat("installed fmrihrf: ", as.character(packageVersion("fmrihrf")), "\n", sep = "")

# Installed 0.4.0 hrf_bspline is the legacy convention (drops only the first
# spline). It is not the complete basis: it cannot reproduce a constant.
legacy <- fmrihrf::hrf_bspline(seq(0, 24, by = 0.5), span = 24, N = 5, degree = 3)
cat(sprintf("installed legacy: ncol = %d, row-sum range = %s\n", ncol(legacy),
            paste(format(range(rowSums(legacy)), digits = 6), collapse = " .. ")))

# The fmrihrf checkout's current hrf_bspline (unreleased, N + 2 clamped basis
# with first and last splines dropped) is the complete basis of width N + 2
# with its two boundary columns removed.
src_file <- file.path(fmrihrf_dir, "R", "hrf-functions.R")
if (file.exists(src_file)) {
  env <- new.env()
  exprs <- parse(src_file)
  for (e in exprs) {
    if (is.call(e) && identical(e[[1L]], as.name("<-")) &&
        identical(e[[2L]], as.name("hrf_bspline"))) eval(e, env)
  }
  sha <- tryCatch(system2("git", c("-C", fmrihrf_dir, "rev-parse", "--short", "HEAD"),
                          stdout = TRUE), error = function(e) "unknown")
  worst <- 0
  for (cfg in list(c(3L, 3L, 24), c(5L, 3L, 24.5), c(6L, 2L, 17.3), c(10L, 4L, 32.75))) {
    N <- cfg[[1L]]; degree <- cfg[[2L]]; span <- cfg[[3L]]
    t <- seq(0, span, length.out = 97L)
    head_basis <- env$hrf_bspline(t, span = span, N = N, degree = degree)
    full <- complete_bs(t, span, N + 2L, degree)
    worst <- max(worst, max(abs(head_basis - full[, -c(1L, ncol(full)), drop = FALSE])))
  }
  cat(sprintf("fmrihrf checkout %s hrf_bspline(N) vs complete(N + 2)[, -c(1, last)]: max |diff| = %.3g\n",
              sha, worst))
} else {
  cat("fmrihrf checkout not found at", fmrihrf_dir, "\n")
}
