package scalafim.multivar
package family.paired

import scalafim.multivar.core.*

import gale.linalg.DMat
import gale.linalg.DVec

/** Golden paired latent-method fixtures generated by
  * tools/r-parity/generate_multivar_paired_r_parity_fixtures.R.
  * Provenance: R 4.5.1; stats 4.5.1; base svd/eigen/solve/cancor.
  * Component signs are canonicalized so the largest-magnitude x weight is positive.
  */
object PairedLatentRReferenceFixtures:
  final case class PairedReference(
      x: DMat,
      y: DMat,
      components: Int,
      singularValues: DVec,
      xWeights: DMat,
      yWeights: DMat,
      xScores: DMat,
      yScores: DMat,
      xRidge: Double = 0.0,
      yRidge: Double = 0.0,
      baseCancorCorrelations: Option[DVec] = None,
      fullCoefficient: Option[DMat] = None,
      workingCoefficient: Option[DMat] = None,
      predictedWorking: Option[DMat] = None,
      predicted: Option[DMat] = None
  )

  val plsc: PairedReference =
    PairedReference(
      x = GaleNumerics.matrixFromRows(
        Vector(
          Vector(1.2000000000000000, -0.29999999999999999, 0.69999999999999996),
          Vector(0.10000000000000001, 1.3999999999999999, -1.1000000000000001),
          Vector(-0.80000000000000004, 0.50000000000000000, 0.20000000000000001),
          Vector(1.8999999999999999, -1.2000000000000000, 1.3000000000000000),
          Vector(-1.1000000000000001, 0.0, -0.40000000000000002)
        )
      ),
      y = GaleNumerics.matrixFromRows(
        Vector(
          Vector(0.40000000000000002, 1.1000000000000001),
          Vector(1.2000000000000000, -0.69999999999999996),
          Vector(-0.59999999999999998, 0.29999999999999999),
          Vector(1.5000000000000000, 0.90000000000000002),
          Vector(-1.0000000000000000, -0.50000000000000000)
        )
      ),
      components = 2,
      singularValues = DVec.fromSeq(Vector(1.5955931168427702, 0.52705654865865581)),
      xWeights = GaleNumerics.matrixFromRows(
        Vector(
          Vector(0.84632974713746134, -0.53173135618183553),
          Vector(-0.32931725144925278, -0.56870737573814556),
          Vector(0.41865989419593325, 0.62756169866719647)
        )
      ),
      yWeights = GaleNumerics.matrixFromRows(
        Vector(
          Vector(0.71362273704191981, -0.70053022003108389),
          Vector(0.70053022003108389, 0.71362273704191981)
        )
      ),
      xScores = GaleNumerics.matrixFromRows(
        Vector(
          Vector(1.1551400586096523, 0.067715879223200007),
          Vector(-1.0892498002579647, -1.4437932253325820),
          Vector(-1.0103031839226391, 0.36243184166275633),
          Vector(2.2951523444277626, 0.58387758726056416),
          Vector(-1.3507394188568114, 0.42976791718606189)
        )
      ),
      yScores = GaleNumerics.matrixFromRows(
        Vector(
          Vector(0.68782886733154591, 0.55793498659378116),
          Vector(-0.0022273390908693624, -1.2870101161065417),
          Vector(-0.58621804573524106, 0.68756701699132894),
          Vector(1.3327078340714407, -0.35537280284879519),
          Vector(-1.4320913165768760, 0.39688091537022685)
        )
      )
    )

  val cca: PairedReference =
    PairedReference(
      x = GaleNumerics.matrixFromRows(
        Vector(
          Vector(0.20000000000000001, 1.1000000000000001, -0.40000000000000002),
          Vector(1.0000000000000000, 0.29999999999999999, 0.80000000000000004),
          Vector(-0.50000000000000000, 1.3999999999999999, 0.10000000000000001),
          Vector(1.7000000000000000, -0.80000000000000004, 1.2000000000000000),
          Vector(-1.2000000000000000, 0.59999999999999998, -0.69999999999999996),
          Vector(0.40000000000000002, -1.1000000000000001, 0.50000000000000000),
          Vector(1.3000000000000000, 0.90000000000000002, -1.0000000000000000)
        )
      ),
      y = GaleNumerics.matrixFromRows(
        Vector(
          Vector(1.1000000000000001, -0.20000000000000001),
          Vector(0.34999999999999998, 1.3000000000000000),
          Vector(1.4500000000000000, -0.75000000000000000),
          Vector(-0.90000000000000002, 0.40000000000000002),
          Vector(0.25000000000000000, -1.2000000000000000),
          Vector(-1.1000000000000001, 0.94999999999999996),
          Vector(0.80000000000000004, 0.10000000000000001)
        )
      ),
      components = 2,
      singularValues = DVec.fromSeq(Vector(0.91943325226025518, 0.59090976111307569)),
      xWeights = GaleNumerics.matrixFromRows(
        Vector(
          Vector(-0.11969357060781248, 0.88110865654092385),
          Vector(0.92107783149679789, 0.77431418123861673),
          Vector(-0.056285766554914303, 0.50793970494998375)
        )
      ),
      yWeights = GaleNumerics.matrixFromRows(
        Vector(
          Vector(0.82227404473414611, 0.72672077131624757),
          Vector(-0.29547652284021897, 1.1438612624766011)
        )
      ),
      xScores = GaleNumerics.matrixFromRows(
        Vector(
          Vector(0.74957084178228095, 0.15800016420261961),
          Vector(-0.15058919976730473, 0.85296339038444569),
          Vector(1.0815368073793317, 0.027488211470549598),
          Vector(-1.2700746204612168, 0.82116973258060744),
          Vector(0.47348865485129349, -1.6150909570589773),
          Vector(-1.3513962915316600, -0.91212356875916722),
          Vector(0.46746380774727597, 0.66759302717992219)
        )
      ),
      yScores = GaleNumerics.matrixFromRows(
        Vector(
          Vector(0.75986125755739686, 0.27013170144503157),
          Vector(-0.30005906025354129, 1.4408830166727478),
          Vector(1.2101692607764682, -0.10463972295641255),
          Vector(-1.0619727456150267, -0.49699308370150286),
          Vector(0.35640484237359155, -1.4914422166503798),
          Vector(-1.3889396421239766, -0.013213543602622084),
          Vector(0.42453608728508724, 0.39527384879313759)
        )
      ),
      xRidge = 0.070000000000000007,
      yRidge = 0.11000000000000000,
      baseCancorCorrelations = Some(DVec.fromSeq(Vector(0.99714812007756748, 0.70104782791830689)))
    )

  val rrr: PairedReference =
    PairedReference(
      x = GaleNumerics.matrixFromRows(
        Vector(
          Vector(1.0000000000000000, 0.20000000000000001, -0.40000000000000002),
          Vector(0.50000000000000000, 1.3000000000000000, 0.69999999999999996),
          Vector(-0.80000000000000004, 0.40000000000000002, 1.1000000000000001),
          Vector(1.7000000000000000, -1.0000000000000000, 0.29999999999999999),
          Vector(-1.3999999999999999, -0.59999999999999998, -0.90000000000000002),
          Vector(0.20000000000000001, 0.80000000000000004, -1.2000000000000000)
        )
      ),
      y = GaleNumerics.matrixFromRows(
        Vector(
          Vector(1.5800000000000001, -0.32000000000000001),
          Vector(0.81999999999999995, 1.4399999999999999),
          Vector(-1.5600000000000001, 1.0700000000000001),
          Vector(1.2000000000000000, -1.7000000000000000),
          Vector(-1.3200000000000001, -0.38000000000000000),
          Vector(1.6499999999999999, 0.41999999999999998)
        )
      ),
      components = 1,
      singularValues = DVec.fromSeq(Vector(3.3794108499835707)),
      xWeights = GaleNumerics.matrixFromRows(
        Vector(
          Vector(1.2457849270204118),
          Vector(0.12349752006175785),
          Vector(-0.82866742000518390)
        )
      ),
      yWeights = GaleNumerics.matrixFromRows(
        Vector(
          Vector(0.92358814766826380),
          Vector(-0.38338614149014982)
        )
      ),
      xScores = GaleNumerics.matrixFromRows(
        Vector(
          Vector(1.2749087069524201),
          Vector(-0.12367064649555443),
          Vector(-2.1858057876797456),
          Vector(1.4186939377889700),
          Vector(-1.3994394239433823),
          Vector(1.0153132133772924)
        )
      ),
      yScores = GaleNumerics.matrixFromRows(
        Vector(
          Vector(1.2510012960953705),
          Vector(-0.12568530515517373),
          Vector(-2.1819722242542863),
          Vector(1.4291106752378369),
          Vector(-1.4044011636531857),
          Vector(1.0319467217294380)
        )
      ),
      fullCoefficient = Some(
        GaleNumerics.matrixFromRows(
          Vector(
            Vector(1.1830336838864235, -0.39946419997166854),
            Vector(0.59048487866895505, 1.1003718434226728),
            Vector(-0.77169292637693676, 0.30241306874934548)
          )
        )
      ),
      workingCoefficient = Some(
        GaleNumerics.matrixFromRows(
          Vector(
            Vector(1.1505921931398253, -0.47761667629694354),
            Vector(0.11406084579546318, -0.047347237700079710),
            Vector(-0.76534740747562702, 0.31769960473438486)
          )
        )
      ),
      predictedWorking = Some(
        GaleNumerics.matrixFromRows(
          Vector(
            Vector(1.1774905711003270, -0.48878232991068449),
            Vector(-0.11422074331776580, 0.047413611975522948),
            Vector(-2.0187843186057064, 0.83800764698537533),
            Vector(1.3102889061107099, -0.54390759476437989),
            Vector(-1.2925056653338107, 0.53652568099485132),
            Vector(0.93773125004624625, -0.38925701528068535)
          )
        )
      ),
      predicted = Some(
        GaleNumerics.matrixFromRows(
          Vector(
            Vector(1.5724905711003270, -0.40044899657735117),
            Vector(0.28077925668223425, 0.13574694530885628),
            Vector(-1.6237843186057064, 0.92634098031870871),
            Vector(1.7052889061107099, -0.45557426143104657),
            Vector(-0.89750566533381071, 0.62485901432818469),
            Vector(1.3327312500462463, -0.30092368194735203)
          )
        )
      )
    )
