package scalafim.fmri.fit.fixtures

import gale.linalg.{DMat, Matrix}

// Generated by modules/fit/tools/generate_fmriar_estimated_gls_parity.R.
object FmriArEstimatedGlsFixture:
  val rows: Int = 24
  val runLengths: Vector[Int] = Vector(12, 12)
  val censoredTimepoints: Vector[Int] = Vector(3, 8, 13, 19)

  val design: DMat =
    Matrix.tabulate(rows, 2) { (row, column) =>
      Vector(Vector(-1.25, 1.0), Vector(-0.75, 1.0), Vector(-0.25, 1.0), Vector(0.25, 1.0), Vector(0.75, 1.0), Vector(1.25, 1.0), Vector(-1.25, 1.0), Vector(-0.75, 1.0), Vector(-0.25, 1.0), Vector(0.25, 1.0), Vector(0.75, 1.0), Vector(1.25, 1.0), Vector(-0.94999999999999996, 1.0), Vector(-0.45000000000000001, 1.0), Vector(0.049999999999999989, 1.0), Vector(0.55000000000000004, 1.0), Vector(1.05, 1.0), Vector(1.55, 1.0), Vector(-0.94999999999999996, 1.0), Vector(-0.45000000000000001, 1.0), Vector(0.049999999999999989, 1.0), Vector(0.55000000000000004, 1.0), Vector(1.05, 1.0), Vector(1.55, 1.0))(row)(column)
    }

  val response: DMat =
    Matrix.tabulate(rows, 2) { (row, column) =>
      Vector(Vector(-1.5323303516026501, 2.2682401887105645), Vector(-0.99461643804379485, 1.5114690196093421), Vector(-0.63691551925885947, 0.6766972728846502), Vector(-0.52362706117446367, 1.5379253311162455), Vector(0.92202753754339595, 0.80942191658615459), Vector(1.8571746954236097, 0.34117104322360581), Vector(-1.5954171369561252, 2.0494467602873767), Vector(-1.1112283704675381, 0.97674517147134488), Vector(-0.56699652685405377, 0.69784985995093196), Vector(-0.99018289486611288, 0.61178543236810234), Vector(0.20320371188404768, 0.4266562363414218), Vector(1.178372502651132, -0.31278721351426103), Vector(-1.7986245907346585, 1.4061107518557923), Vector(-0.40299109094082575, 0.96099259831883344), Vector(-0.370663668045568, -0.036878026406279019), Vector(0.091571228501331481, 0.49685243120216221), Vector(0.25785024495906406, -0.046609859327276904), Vector(2.1295668004105384, -0.14804199586928779), Vector(-0.86439850968056298, 1.8812722867965266), Vector(0.14381702369450688, 1.4641692762803773), Vector(0.9523933301660652, 0.28971105717787538), Vector(0.061353246978071818, 0.44790913651879821), Vector(1.0217414565847744, 0.035018493369343401), Vector(2.4421288410150925, -0.10388124612185523))(row)(column)
    }

  val estimatedPhi: Vector[Double] = Vector(0.21261356550749974, -0.30211449746882546)

  val coefficients: DMat =
    Matrix.tabulate(2, 2) { (row, column) =>
      Vector(Vector(1.2501373058862255, -0.75460315502541875), Vector(-0.18272064871243765, 0.87659754571690929))(row)(column)
    }

  val residualVariance: Vector[Double] = Vector(0.29699523344665535, 0.15910428451507283)

  val normalizedCovariance: DMat =
    Matrix.tabulate(2, 2) { (row, column) =>
      Vector(Vector(0.063615935858804304, -0.010363251078950307), Vector(-0.010363251078950307, 0.043417448738681703))(row)(column)
    }

  val residualDegreesOfFreedom: Int = 22
  val fmriArRevision: String = "f563f2df20264ffa7db9be116f11d631551e9132"
  val fmriArVersion: String = "0.3.3"
