package scalafim.fmri.fit.fixtures

import gale.linalg.{DMat, Matrix}

// Generated by modules/fit/tools/generate_fmriar_estimated_gls_parity.R.
object FmriArEstimatedGlsFixture:
  val rows: Int = 24
  val runLengths: Vector[Int] = Vector(12, 12)
  val censoredTimepoints: Vector[Int] = Vector(3, 8, 13, 19)

  val design: DMat =
    Matrix.tabulate(rows, 2) { (row, column) =>
      Vector(Vector(-1.25, 1.0), Vector(-0.75, 1.0), Vector(-0.25, 1.0), Vector(0.25, 1.0), Vector(0.75, 1.0), Vector(1.25, 1.0), Vector(-1.25, 1.0), Vector(-0.75, 1.0), Vector(-0.25, 1.0), Vector(0.25, 1.0), Vector(0.75, 1.0), Vector(1.25, 1.0), Vector(-0.95, 1.0), Vector(-0.45, 1.0), Vector(0.05, 1.0), Vector(0.55, 1.0), Vector(1.05, 1.0), Vector(1.55, 1.0), Vector(-0.95, 1.0), Vector(-0.45, 1.0), Vector(0.05, 1.0), Vector(0.55, 1.0), Vector(1.05, 1.0), Vector(1.55, 1.0))(row)(column)
    }

  val response: DMat =
    Matrix.tabulate(rows, 2) { (row, column) =>
      Vector(Vector(-1.532330351603, 2.268240188711), Vector(-0.9946164380438, 1.511469019609), Vector(-0.6369155192589, 0.6766972728847), Vector(-0.5236270611745, 1.537925331116), Vector(0.9220275375434, 0.8094219165862), Vector(1.857174695424, 0.3411710432236), Vector(-1.595417136956, 2.049446760287), Vector(-1.111228370468, 0.9767451714713), Vector(-0.5669965268541, 0.6978498599509), Vector(-0.9901828948661, 0.6117854323681), Vector(0.203203711884, 0.4266562363414), Vector(1.178372502651, -0.3127872135143), Vector(-1.798624590735, 1.406110751856), Vector(-0.4029910909408, 0.9609925983188), Vector(-0.3706636680456, -0.03687802640628), Vector(0.09157122850133, 0.4968524312022), Vector(0.2578502449591, -0.04660985932728), Vector(2.129566800411, -0.1480419958693), Vector(-0.8643985096806, 1.881272286797), Vector(0.1438170236945, 1.46416927628), Vector(0.9523933301661, 0.2897110571779), Vector(0.06135324697807, 0.4479091365188), Vector(1.021741456585, 0.03501849336934), Vector(2.442128841015, -0.1038812461219))(row)(column)
    }

  val estimatedPhi: Vector[Double] = Vector(0.2126135655075, -0.3021144974688)

  val coefficients: DMat =
    Matrix.tabulate(2, 2) { (row, column) =>
      Vector(Vector(1.250137305886, -0.7546031550254), Vector(-0.1827206487124, 0.8765975457169))(row)(column)
    }

  val residualVariance: Vector[Double] = Vector(0.2969952334467, 0.1591042845151)

  val normalizedCovariance: DMat =
    Matrix.tabulate(2, 2) { (row, column) =>
      Vector(Vector(0.0636159358588, -0.01036325107895), Vector(-0.01036325107895, 0.04341744873868))(row)(column)
    }

  val residualDegreesOfFreedom: Int = 22
  val fmriArRevision: String = "f563f2df20264ffa7db9be116f11d631551e9132"
  val fmriArVersion: String = "0.3.3"
