package scalafim.fmri.fit.fixtures

// Generated by tools/r-parity/generate_mixed_tr_fixed_effects_receipt.R.
object MixedTrFixedEffectsRFixture:
  val design: Vector[Vector[Double]] = Vector(
    Vector(0.0, 0.0, 1),
    Vector(0.03608940829789, 0.0, 1),
    Vector(0.1562909453311, 0.0, 1),
    Vector(0.1604745984543, 0.03608940829789, 1),
    Vector(0.09009933169073, 0.1562909453311, 1),
    Vector(0.03204692986362, 0.1604745984543, 1),
    Vector(0.0006754520447549, 0.09009933169073, 1),
    Vector(-0.01276039994066, 0.03204692986362, 1),
    Vector(0.0, 0.0, 1),
    Vector(0.001226967624681, 0.0, 1),
    Vector(0.01764198690806, 0.0, 1),
    Vector(0.06019607350381, 0.0, 1),
    Vector(0.1139791871924, 0.0, 1),
    Vector(0.1562909453311, 0.0, 1),
    Vector(0.1747303314582, 0.001226967624681, 1),
    Vector(0.1696321945892, 0.01764198690806, 1),
    Vector(0.1484114695254, 0.06019607350381, 1),
    Vector(0.1196925242799, 0.1139791871924, 1),
    Vector(0.09009933169073, 0.1562909453311, 1),
    Vector(0.06346531393535, 0.1747303314582, 1)
  )
  val response: Vector[Vector[Double]] = Vector(
    Vector(0.42, -0.94),
    Vector(0.5833072899575, -1.114435763319),
    Vector(0.7975491343973, -1.022516378132),
    Vector(0.6209158731664, -0.9153183127434),
    Vector(0.5843446308302, -0.9810069764114),
    Vector(0.3221715567638, -0.794439093182),
    Vector(0.4767509434393, -0.9581907154653),
    Vector(0.555459362153, -1.049258296133),
    Vector(0.65, -0.84),
    Vector(0.5117177546746, -0.6907361805748),
    Vector(0.7546987816713, -0.8705851921448),
    Vector(0.6442745029053, -0.7561176441023),
    Vector(0.8395708620693, -0.9883875123154),
    Vector(0.7088073234635, -0.8637745671986),
    Vector(0.8635181931793, -0.8136112312502),
    Vector(0.9216072842076, -0.9541373298455),
    Vector(0.6935995911821, -0.7788508082114),
    Vector(0.7349882655187, -0.8578363273756),
    Vector(0.5554772135691, -0.5677686536834),
    Vector(0.6515941411971, -0.683348856903)
  )
  val contrast: Vector[Double] = Vector(1, -1, 0.0)
  val runCoefficients: Vector[Vector[Vector[Double]]] = Vector(
    Vector(
    Vector(1.374141578132, 0.127568585616),
    Vector(-0.8895132513364, 0.8700657070887),
    Vector(0.5183632720862, -1.030937671935)
  ),
    Vector(
    Vector(1.260995999172, -0.6652371497673),
    Vector(-0.649683408654, 1.080884917837),
    Vector(0.6219881745087, -0.7908021395171)
  )
  )
  val runResidualVariance: Vector[Vector[Double]] = Vector(Vector(0.009170914815416, 0.00807452138584), Vector(0.00813412084045, 0.008975132449395))
  val runNormalizedCovariance: Vector[Vector[Vector[Double]]] = Vector(
    Vector(
    Vector(29.62240072803, 2.574529244873, -1.866949455398),
    Vector(2.574529244872, 31.0660331345, -1.993524363234),
    Vector(-1.866949455398, -1.993524363234, 0.3513959702717)
  ),
    Vector(
    Vector(22.0335817304, -1.009038530683, -2.003892735839),
    Vector(-1.009038530683, 20.45517964893, -0.79953384902),
    Vector(-2.003892735839, -0.79953384902, 0.3045068815433)
  )
  )
  val runResidualDf: Vector[Int] = Vector(5, 9)
  val fixedCoefficients: Vector[Vector[Double]] = Vector(
    Vector(1.519017972996, 0.07888109415091),
    Vector(-0.8307038526351, 0.8038122261724),
    Vector(0.5689674517166, -0.9229122753448)
  )
  val fixedCovarianceByVoxel: Vector[Vector[Vector[Double]]] = Vector(
    Vector(
    Vector(0.1003693735519, 0.003451854037312, -0.008191517939694),
    Vector(0.003451854037312, 0.1032714579925, -0.005388511026579),
    Vector(-0.008191517939694, -0.005388511026579, 0.001347331450547)
  ),
    Vector(
    Vector(0.1003803320916, 0.004306270619951, -0.008048028314307),
    Vector(0.004306270619951, 0.1041876833651, -0.005582401677013),
    Vector(-0.008048028314307, -0.005582401677013, 0.001338564241437)
  )
  )
  val fixedStandardErrors: Vector[Vector[Double]] = Vector(
    Vector(0.3168112585624, 0.3168285531507),
    Vector(0.3213587683455, 0.3227811694711),
    Vector(0.0367060138199, 0.03658639421202)
  )
  val fixedResidualDf: Int = 14
  val contrastEstimate: Vector[Double] = Vector(2.349721825631, -0.7249311320215)
  val taskContrastEstimate: Vector[Double] = Vector(2.055564647395, -1.264906869992)
  val contrastStandardError: Vector[Double] = Vector(0.4435505872725, 0.4426685828211)
  val contrastStatistic: Vector[Double] = Vector(5.297528383584, -1.637638540783)
  val acceptedDifferences: Vector[String] = Vector("ScalaFIM preserves typed run and coefficient-axis provenance that is additional to the R numeric receipt.", "The fixed-effects receipt combines each voxel's full coefficient covariance; it does not use coefficientwise diagonal-only meta-analysis.", "Event onsets are exactly representable at 0 and 4 seconds so this receipt isolates mixed-TR and fixed-effects semantics from the separately tracked off-grid interpolation convention.")
