package scalafim.fmri.fit.fixtures

// Generated by tools/r-parity/generate_wls_receipt.R from base R stats::lm.wfit.
object WlsRFixture:
  val dvarsResponse: Vector[Vector[Double]] = Vector(
    Vector(0.0, 0.0, 0.0),
    Vector(1, 1, 1),
    Vector(2, 2, 2),
    Vector(12, -8, 10),
    Vector(13, -7, 11),
    Vector(14, -6, 12)
  )
  val dvars: Vector[Double] = Vector(1, 1, 1, 9.380831519647, 1, 1)
  val inverseSquaredWeights: Vector[Double] = Vector(1.194630872483, 1.194630872483, 1.194630872483, 0.02684563758389, 1.194630872483, 1.194630872483)
  val softThresholdWeights: Vector[Double] = Vector(1.191667631761, 1.191667631761, 1.191667631761, 0.04166184119609, 1.191667631761, 1.191667631761)
  val tukeyWeights: Vector[Double] = Vector(1.2, 1.2, 1.2, 0.0, 1.2, 1.2)
  val design: Vector[Vector[Double]] = Vector(
    Vector(-2, 0.0, 1),
    Vector(-1, 1, 1),
    Vector(0.0, 0.0, 1),
    Vector(1, 1, 1),
    Vector(2, 0.0, 1),
    Vector(-1.5, 1, 1),
    Vector(0.5, 1, 1),
    Vector(1.5, 0.0, 1),
    Vector(2.5, 1, 1)
  )
  val response: Vector[Vector[Double]] = Vector(
    Vector(-0.15, -1),
    Vector(-0.05, 0.65),
    Vector(1.55, -0.7),
    Vector(1.45, 1.15),
    Vector(2.95, -0.25),
    Vector(0.05, 0.35),
    Vector(0.95, 0.9),
    Vector(2.6, -0.5),
    Vector(2.6, 1.2)
  )
  val weights: Vector[Double] = Vector(1, 0.5, 0.0, 1.5, 2, 0.75, 1.25, 0.4, 1.6)
  val contrast: Vector[Double] = Vector(1, -1, 0.0)
  val retainedRows: Vector[Int] = Vector(0, 1, 3, 4, 5, 6, 7, 8)
  val coefficients: Vector[Vector[Double]] = Vector(
    Vector(0.7302056872272, 0.1908186795571),
    Vector(-0.6799029521296, 1.449280156362),
    Vector(1.438666239179, -0.6459201667201)
  )
  val residualVariance: Vector[Double] = Vector(0.03579759291686, 0.01549200619035)
  val normalizedCovariance: Vector[Vector[Double]] = Vector(
    Vector(0.04695785138235, -0.001825042543221, -0.03590894517474),
    Vector(-0.001825042543221, 0.4727600069056, -0.2927220262905),
    Vector(-0.03590894517474, -0.2927220262905, 0.321577428663)
  )
  val standardErrors: Vector[Vector[Double]] = Vector(
    Vector(0.04099973229224, 0.02697167633464),
    Vector(0.1300910076622, 0.0855803771523),
    Vector(0.1072925807432, 0.07058243064335)
  )
  val residualDf: Int = 5
  val rank: Int = 3
  val contrastEstimate: Vector[Double] = Vector(1.410108639357, -1.258461476805)
  val contrastStandardError: Vector[Double] = Vector(0.1368769980042, 0.09004454130365)
  val contrastStatistic: Vector[Double] = Vector(10.30201319372, -13.97598853395)
  val weightedDesign: Vector[Vector[Double]] = Vector(
    Vector(-2, 0.0, 1),
    Vector(-0.7071067811865, 0.7071067811865, 0.7071067811865),
    Vector(1.224744871392, 1.224744871392, 1.224744871392),
    Vector(2.828427124746, 0.0, 1.414213562373),
    Vector(-1.299038105677, 0.8660254037844, 0.8660254037844),
    Vector(0.5590169943749, 1.11803398875, 1.11803398875),
    Vector(0.9486832980505, 0.0, 0.6324555320337),
    Vector(3.162277660168, 1.264911064067, 1.264911064067)
  )
  val weightedResponse: Vector[Vector[Double]] = Vector(
    Vector(-0.15, -1),
    Vector(-0.03535533905933, 0.4596194077713),
    Vector(1.775880063518, 1.4084566021),
    Vector(4.171930009001, -0.3535533905933),
    Vector(0.04330127018922, 0.3031088913246),
    Vector(1.062132289312, 1.006230589875),
    Vector(1.644384383288, -0.3162277660168),
    Vector(3.288768766575, 1.517893276881)
  )
  val acceptedDifferences: Vector[String] = Vector("The receipt supplies explicit fixed weights to lm.wfit; ScalaFIM's typed source and alignment receipt is additional provenance.", "DVARS is estimated from the entire declared response block before voxel chunking; the fixture contains one run and no selection gap.")
