package scalafim.fmri.fit.fixtures

// Generated by tools/r-parity/generate_wls_receipt.R from base R stats::lm.wfit.
object WlsRFixture:
  val dvarsResponse: Vector[Vector[Double]] = Vector(
    Vector(0.0, 0.0, 0.0),
    Vector(1, 1, 1),
    Vector(2, 2, 2),
    Vector(12, -8, 10),
    Vector(13, -7, 11),
    Vector(14, -6, 12)
  )
  val dvars: Vector[Double] = Vector(1, 1, 1, 9.3808315196468595, 1, 1)
  val inverseSquaredWeights: Vector[Double] = Vector(1.1946308724832215, 1.1946308724832215, 1.1946308724832215, 0.02684563758389262, 1.1946308724832215, 1.1946308724832215)
  val softThresholdWeights: Vector[Double] = Vector(1.1916676317607824, 1.1916676317607824, 1.1916676317607824, 0.041661841196087582, 1.1916676317607824, 1.1916676317607824)
  val tukeyWeights: Vector[Double] = Vector(1.2, 1.2, 1.2, 0.0, 1.2, 1.2)
  val design: Vector[Vector[Double]] = Vector(
    Vector(-2, 0.0, 1),
    Vector(-1, 1, 1),
    Vector(0.0, 0.0, 1),
    Vector(1, 1, 1),
    Vector(2, 0.0, 1),
    Vector(-1.5, 1, 1),
    Vector(0.5, 1, 1),
    Vector(1.5, 0.0, 1),
    Vector(2.5, 1, 1)
  )
  val response: Vector[Vector[Double]] = Vector(
    Vector(-0.15000000000000008, -1),
    Vector(-0.050000000000000072, 0.65000000000000013),
    Vector(1.55, -0.69999999999999996),
    Vector(1.45, 1.1499999999999999),
    Vector(2.9500000000000002, -0.24999999999999997),
    Vector(0.049999999999999822, 0.35000000000000003),
    Vector(0.94999999999999996, 0.90000000000000013),
    Vector(2.6000000000000001, -0.49999999999999994),
    Vector(2.6000000000000001, 1.2000000000000002)
  )
  val weights: Vector[Double] = Vector(1, 0.5, 0.0, 1.5, 2, 0.75, 1.25, 0.40000000000000002, 1.6000000000000001)
  val contrast: Vector[Double] = Vector(1, -1, 0.0)
  val retainedRows: Vector[Int] = Vector(0, 1, 3, 4, 5, 6, 7, 8)
  val coefficients: Vector[Vector[Double]] = Vector(
    Vector(0.73020568722716861, 0.19081867955705711),
    Vector(-0.67990295212962748, 1.4492801563617532),
    Vector(1.438666239179224, -0.64592016672010244)
  )
  val residualVariance: Vector[Double] = Vector(0.035797592916861909, 0.015492006190346986)
  val normalizedCovariance: Vector[Vector[Double]] = Vector(
    Vector(0.046957851382346406, -0.0018250425432214331, -0.035908945174735481),
    Vector(-0.0018250425432214524, 0.47276000690556647, -0.29272202629047783),
    Vector(-0.035908945174735481, -0.29272202629047783, 0.32157742866303307)
  )
  val standardErrors: Vector[Vector[Double]] = Vector(
    Vector(0.04099973229224476, 0.026971676334642314),
    Vector(0.13009100766224502, 0.085580377152297701),
    Vector(0.10729258074317374, 0.070582430643351846)
  )
  val residualDf: Int = 5
  val rank: Int = 3
  val contrastEstimate: Vector[Double] = Vector(1.4101086393567961, -1.2584614768046962)
  val contrastStandardError: Vector[Double] = Vector(0.13687699800423159, 0.090044541303649778)
  val contrastStatistic: Vector[Double] = Vector(10.30201319372304, -13.975988533951108)
  val weightedDesign: Vector[Vector[Double]] = Vector(
    Vector(-2, 0.0, 1),
    Vector(-0.70710678118654757, 0.70710678118654757, 0.70710678118654757),
    Vector(1.2247448713915889, 1.2247448713915889, 1.2247448713915889),
    Vector(2.8284271247461903, 0.0, 1.4142135623730951),
    Vector(-1.299038105676658, 0.8660254037844386, 0.8660254037844386),
    Vector(0.55901699437494745, 1.1180339887498949, 1.1180339887498949),
    Vector(0.94868329805051377, 0.0, 0.63245553203367588),
    Vector(3.1622776601683795, 1.2649110640673518, 1.2649110640673518)
  )
  val weightedResponse: Vector[Vector[Double]] = Vector(
    Vector(-0.15000000000000008, -1),
    Vector(-0.035355339059327431, 0.45961940777125604),
    Vector(1.7758800635178038, 1.4084566021003271),
    Vector(4.171930009000631, -0.35355339059327373),
    Vector(0.043301270189221773, 0.30310889132455354),
    Vector(1.0621322893124001, 1.0062305898749055),
    Vector(1.6443843832875573, -0.31622776601683789),
    Vector(3.2887687665751146, 1.5178932768808224)
  )
  val acceptedDifferences: Vector[String] = Vector("The receipt supplies explicit fixed weights to lm.wfit; ScalaFIM's typed source and alignment receipt is additional provenance.", "DVARS is estimated from the entire declared response block before voxel chunking; the fixture contains one run and no selection gap.")
