package scalafim.fmri.laws

// Generated by tools/scenarios/corrected-gls/generate_bounds.R before outcomes.
private[laws] object CorrectedGlsBounds:
  val DefaultSeed: Int = 1149777122
  val T236: Double = 1.970066853102125
  val T224: Double = 1.970610961102363
  val F236: Double = 3.034083301008441
  val F224: Double = 3.036156222073991
  val PilotCounts: (Int, Int) = (0, 5)
  val PilotMeanCritical: Double = 1.753050355692573
  val ScreenCounts: (Int, Int) = (0, 11)
  val ScreenMeanCritical: Double = 1.669402221706813
  val ConfirmationCounts: (Int, Int) = (53, 143)
  val ConfirmationMeanCritical: Double = 1.645598357376227
