package scalafim.fmri.laws

// Generated by tools/scenarios/gls-factor-diagnosis/generate_bounds.R.
private[laws] object GlsFactorBounds:
  val DefaultSeed: Int = 973860617
  val T464: Double = 1.9650897735243418
  val T476: Double = 1.9649602285407075
  val F464: Double = 3.0151571973787448
  val F476: Double = 3.0146654345063157
