package scalafim.fmri.hrf

class SpmgCorrectnessSuite extends munit.FunSuite:
  // Independent SciPy 1.17.1 gamma PDF/CDF oracle, not generated by fmrihrf.
  private val times = Vector(0, 0.10000000000000001, 1, 3, 5, 7, 10, 16, 24, 32)
  private val canonical = Vector(0, 7.5403118169663394e-08, 0.0030656620097151326, 0.10081872239396784, 0.17544116219546385, 0.12716489793477317, 0.032046929863623397, -0.015552907908972445, -0.0024266218746080686, -6.0974770045128949e-05)
  private val dispersion = Vector(0, -1.484362481441066e-06, -0.016305895474487582, -0.06432936611054374, 0.073256518763545331, 0.055692264987672324, -0.015711452163995332, -0.0035667455091810667, -2.3796293575093621e-05, -5.8489679302478102e-08)
  private val dispersionIntegral = Vector(0, -2.6619928609693309e-08, -0.0037703935299894975, -0.1282249793354992, -0.10875751318041305, 0.043381555975829933, 0.080029898623190654, 0.006299199851533821, 3.2907908142920661e-05, 7.3542538725490658e-08)

  test("canonical and dispersion match independent gamma PDF oracles"):
    times.indices.foreach: i =>
      assertEqualsDouble(Hrfs.SPMG1(Lag(times(i))).data(0), canonical(i), 2e-13)
      assertEqualsDouble(Hrfs.SPMG3(Lag(times(i))).data(2), dispersion(i), 2e-12)
    assertEqualsDouble(Hrfs.SPMG3(Lag(-1.0)).data(2), 0.0, 0.0)

  test("dispersion time derivative follows the actual third column"):
    val grid = Vector(0.5, 1.0, 3.0, 5.0, 8.0, 16.0, 24.0)
    val actual = Deriv.doubles(Hrfs.SPMG3, grid)
    val eps = 1e-4
    grid.indices.foreach: i =>
      val plus = Hrfs.SPMG3(Lag(grid(i) + eps)).data
      val minus = Hrfs.SPMG3(Lag(grid(i) - eps)).data
      (0 until 3).foreach: j =>
        assertEqualsDouble(actual(i, j), (plus(j) - minus(j)) / (2.0 * eps), 2e-8)

  test("dispersion primitive matches independent gamma CDF oracle"):
    times.indices.foreach: i =>
      val actual = Primitive.definiteIntegral(Hrfs.SPMG3, Lag(0.0), Lag(times(i))).get
      assertEqualsDouble(actual(2), dispersionIntegral(i), 3e-12)
