#!/usr/bin/env python3
"""Independent PHRF-30 oracle: mpmath dense expm/diff and SciPy dense expm.

Requires mpmath 1.3.0, NumPy and SciPy. Writes a portable Scala fixture and
machine-readable provenance. No production finite-polynomial formulas used.
Run from the repository root with --out-dir <directory for provenance>.
"""
import argparse
import hashlib
import json
import math
import platform
from pathlib import Path

import mpmath as mp
import numpy as np
import scipy
from scipy.linalg import expm

mp.mp.dps = 80
ORDERS = [(0, 0, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1),
          (2, 0, 0), (1, 1, 0), (1, 0, 1), (0, 2, 0),
          (0, 1, 1), (0, 0, 2)]


def operators(a, b, rho):
    p = mp.exp(a)
    u = p / (1 + mp.exp(-b))
    generator = mp.zeros(7)
    for start, size, rate in ((0, 3, p), (3, 4, u)):
        for j in range(size):
            generator[start+j, start+j] = -rate
            if j:
                generator[start+j, start+j-1] = rate
    injection = mp.matrix([p, 0, 0, u, 0, 0, 0])
    observation = mp.matrix([[0, 0, 1, 0, 0, 0, -rho]])
    return generator, injection, observation


def kernel(a, b, rho, t):
    if t <= 0:
        return mp.mpf(0)
    p = mp.exp(a)
    u = p / (1 + mp.exp(-b))
    return (p**3*t**2*mp.exp(-p*t)/mp.factorial(2)
            - rho*u**4*t**3*mp.exp(-u*t)/mp.factorial(3))


def number(x):
    v = float(x)
    return repr(v) if v else '0.0'


def array(values):
    vals = [number(v) for v in values]
    return 'Array(\n' + ',\n'.join('      ' + ', '.join(vals[i:i+7])
                                 for i in range(0, len(vals), 7)) + '\n    )'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--out-dir', type=Path, required=True)
    args = parser.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    # Broad-chart probes deliberately include rho=1 and almost equal rates.
    specs = [(math.log(.4), 0., .35, t) for t in (0., 1e-18, .01, 1.3, 12., 85.)]
    specs += [(0., math.log(4.), 0., .37),
              (math.log(.6), math.log(.25), 1., .9),
              (math.log(.7), math.log((1-1e-12)/1e-12), .2, 40.),
              (0., 0., .3, 750.), (0., 0., .3, 1500.), (0., 0., .3, 1024.)]
    chunks = []
    scipy_error = 0.
    for index, spec in enumerate(specs):
        a, b, rho, t = map(mp.mpf, spec)  # exact binary64 inputs
        point = (a, b, rho)
        trans = lambda aa, bb, rr: mp.expm(operators(aa, bb, rr)[0] * t)
        tj = [mp.diff(trans, point, order) for order in ORDERS]
        ij = [mp.diff(lambda *x: operators(*x)[1], point, order) for order in ORDERS]
        oj = [mp.diff(lambda *x: operators(*x)[2], point, order) for order in ORDERS]
        hj = [mp.diff(lambda aa, bb, rr: kernel(aa, bb, rr, t), point, order)
              for order in ORDERS]
        dense = expm(np.array(operators(*point)[0].tolist(), dtype=float) * float(t))
        scipy_error = max(scipy_error, float(np.max(np.abs(
            dense - np.array(tj[0].tolist(), dtype=float)))))
        # One entry per lower diagonal per block; tests also check every
        # structural zero, so compression of fixtures does not hide ordering.
        # Component-major, seven unique coefficients per component.
        compact = [v for m in tj for v in
                   ([m[j, 0] for j in range(3)] + [m[3+j, 3] for j in range(4)])]
        chunks.append('    Sample(\n      ' + ', '.join(number(v) for v in spec)
                      + ',\n      ' + array(compact) + ',\n      '
                      + array([v for m in ij for v in m]) + ',\n      '
                      + array([v for m in oj for v in m]) + ',\n      '
                      + array(hj) + '\n    )')
        print(f'fixture {index+1}/{len(specs)}', flush=True)
    assert scipy_error < 2e-13, scipy_error
    observations = [0., .31, 1.3, 2.7, 10., 45.]
    events = [0., .2, 1.3, 1.3, 2.7, 8., 50.]
    weights = [.7, 1., 1., -1., .5, -.4, 2.]
    point = tuple(map(mp.mpf, (math.log(.4), 0., .35)))
    precision = mp.mpf(2.1)
    design = mp.matrix([[mp.mpf(w)*kernel(*point, mp.mpf(t)-mp.mpf(e))
                        for e, w in zip(events, weights)] for t in observations])
    covariance = mp.eye(len(observations)) + design * design.T / precision
    source = '''package scalafim.fmri.hrf.family

// Generated by tools/validation/cascade34_realization_reference.py.
// Independent dense matrix exponential, 80-digit differentiation, binary64 inputs.
private[family] object Cascade34RealizationFixtures:
  final case class Sample(a: Double, b: Double, rho: Double, delta: Double,
      transition: Array[Double], injection: Array[Double], observation: Array[Double],
      kernel: Array[Double])
  val samples: Vector[Sample] = Vector(
''' + ',\n'.join(chunks) + '\n  )\n'
    source += '  val observationTimes = ' + array(observations) + '\n'
    source += '  val eventTimes = ' + array(events) + '\n'
    source += '  val eventWeights = ' + array(weights) + '\n'
    source += '  val covariance = ' + array([covariance[i, j]
              for i in range(len(observations)) for j in range(len(observations))]) + '\n'
    target = Path('modules/hrf/shared/src/test/scala/scalafim/fmri/hrf/family/Cascade34RealizationFixtures.scala')
    target.write_text(source)
    report = dict(python=platform.python_version(), mpmath=mp.__version__,
                  numpy=np.__version__, scipy=scipy.__version__, decimal_digits=80,
                  samples=len(specs), scipy_vs_mpmath_max_abs=scipy_error,
                  generator_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
                  fixture_sha256=hashlib.sha256(target.read_bytes()).hexdigest(),
                  covariance='I + X X^T / 2.1; independent scalar Erlang kernel',
                  assumptions='point observations; independent trial amplitudes shared across both branches; zero state before run-start impulses')
    (args.out_dir / 'oracle.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    main()
