#!/usr/bin/env python3
"""Regenerate Cascade34Reference.scala using mpmath 1.3.0 at 80 digits.

Run with Python plus mpmath; stdout is the fixture, with no Scala dependency.
Derivatives use arbitrary-precision numerical differentiation of the literal
Erlang density. Integrals use quadrature; summaries solve the time derivative
directly in seconds, without the production dimensionless log-ratio equations.
"""
import mpmath as mp

mp.mp.dps = 80


def kernel(t, p, u, rho):
    if t <= 0:
        return mp.mpf(0)
    return p**3 * t**2 * mp.exp(-p * t) / 2 - rho * u**4 * t**3 * mp.exp(-u * t) / 6


def number(value):
    return repr(float(value))


def vector(values):
    return "Vector(" + ", ".join(map(number, values)) + ")"


def root(fn, lo, hi):
    return mp.findroot(fn, (lo, hi), solver="bisect", maxsteps=300)


print('''package scalafim.fmri.hrf.fixtures

// Generated by tools/validation/cascade34_reference.py, mpmath 1.3.0, 80 digits.
// Jet coordinates are rounded to Double before the oracle is evaluated.
object Cascade34Reference:
  final case class JetCase(point: Vector[Double], lag: Double, jet: Vector[Double])
  final case class IntegralCase(params: Vector[Double], lo: Double, hi: Double, value: Double)
  final case class SummaryCase(params: Vector[Double], peak: Double, height: Double, width: Double,
      trough: Option[(Double, Double)])

  val jets: Vector[JetCase] = Vector(''')

jets = []
for ps, us, rs in [("0.5", "0.2", "0.3"), ("0.26", "0.027", "0.75"),
                   ("0.95", "0.75", "1.0"), ("0.4", "0.15", "0.0")]:
    p, u, r = map(mp.mpf, (ps, us, rs))
    point = [mp.mpf(number(x)) for x in (mp.log(p), mp.log(u / (p - u)), r)]
    for ts in ("-1.0", "0.0", "0.001", "1.3", "4.7", "13.0", "48.0", "200.0"):
        t = mp.mpf(ts)

        def f(a, b, rho):
            pp = mp.exp(a)
            return kernel(t, pp, pp / (1 + mp.exp(-b)), rho)

        orders = [(0, 0, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1), (2, 0, 0),
                  (1, 1, 0), (1, 0, 1), (0, 2, 0), (0, 1, 1), (0, 0, 2)]
        values = [mp.diff(f, point, order) for order in orders]
        jets.append(f"    JetCase({vector(point)}, {ts}, {vector(values)})")
print(",\n".join(jets))
print("  )\n\n  val integrals: Vector[IntegralCase] = Vector(")
integrals = []
for params in (("0.5", "0.2", "0.3"), ("0.5", "0.2", "1.0")):
    p, u, r = map(mp.mpf, params)
    for lo, hi in (("-1", "-0.1"), ("0", "0.00001"), ("-1", "1.7"),
                   ("3", "8"), ("48", "52"), ("240", "240.1")):
        a, b = map(mp.mpf, (lo, hi))
        value = mp.quad(lambda t: kernel(t, p, u, r), [max(a, 0), max(b, 0)])
        integrals.append(f"    IntegralCase({vector((p,u,r))}, {number(a)}, {number(b)}, {number(value)})")
print(",\n".join(integrals))
print("  )\n\n  val summaries: Vector[SummaryCase] = Vector(")
summaries = []
for params in (("0.5", "0.2", "0"), ("0.5", "0.2", "0.3"),
               ("0.5", "0.2", "1"), ("0.26", "0.027", "0.75"),
               ("0.95", "0.75", "1.5"), ("0.5", "0.499", "0.01")):
    p, u, r = map(mp.mpf, params)
    f = lambda t: kernel(t, p, u, r)
    deriv = lambda t: mp.diff(f, t)
    peak = 2 / p if r == 0 else root(deriv, mp.mpf("1e-30"), 2 / p)
    height = f(peak)
    half = lambda t: f(t) - height / 2
    left = root(half, 0, peak)
    hi = peak * 2
    while half(hi) > 0:
        hi *= 2
    width = root(half, peak, hi) - left
    trough = "None"
    if r > 0:
        hi = 6 / u
        while deriv(hi) < 0:
            hi *= 2
        time = root(deriv, 3 / u, hi)
        trough = f"Some(({number(time)}, {number(f(time))}))"
    summaries.append(f"    SummaryCase({vector((p,u,r))}, {number(peak)}, {number(height)}, {number(width)}, {trough})")
print(",\n".join(summaries))
print("  )")
