# Run from the repository root:
# Rscript docs/verification/hrf-endpoint-anchored-bspline-20261005/generate_fixture.R [fmrihrf checkout]
# Evaluates only hrf_bspline from the exact upstream commit, not the installed
# package or checkout HEAD. No Scala implementation is used by this oracle.
source("tools/r-parity/receipt_serialization.R")
args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) args[[1L]] else path.expand("~/code/fmrihrf")
revision <- "18d418f26dd4547ca21ce11d12ea9e5e91a80b87"
blob <- "69a6c8476de9b87e01bca6183eae32d639935c2c"
actual_blob <- system2("git", c("-C", shQuote(root), "rev-parse",
                               paste0(revision, ":R/hrf-functions.R")), stdout = TRUE)
stopifnot(identical(actual_blob, blob))
src <- system2("git", c("-C", shQuote(root), "show",
                       paste0(revision, ":R/hrf-functions.R")), stdout = TRUE)
exprs <- parse(text = src)
definition <- Filter(function(e) is.call(e) && identical(e[[1L]], as.name("<-")) &&
                       identical(e[[2L]], as.name("hrf_bspline")), as.list(exprs))
stopifnot(length(definition) == 1L)
env <- new.env(parent = baseenv())
eval(definition[[1L]], env)
dir <- "docs/verification/hrf-endpoint-anchored-bspline-20261005"
writeLines(c(paste0("# fmrihrf ", revision, "; R/hrf-functions.R blob ", blob),
             "# Exact parsed function definition; generated, do not edit.",
             deparse(definition[[1L]], width.cutoff = 120L)),
           file.path(dir, "upstream_hrf_bspline.R"))

configs <- list(
  list(name = "linear1_span0_5", n = 1L, degree = 1L, span = 0.5),
  list(name = "quadratic1_span7_75", n = 1L, degree = 2L, span = 7.75),
  list(name = "cubic2_span24_5", n = 2L, degree = 3L, span = 24.5),
  list(name = "cubic5_span24", n = 5L, degree = 3L, span = 24),
  list(name = "cubic5_span24_5", n = 5L, degree = 3L, span = 24.5),
  list(name = "quadratic6_span17_3", n = 6L, degree = 2L, span = 17.3),
  list(name = "quartic10_span32_75", n = 10L, degree = 4L, span = 32.75),
  list(name = "degree8_minimum_span0_5", n = 7L, degree = 8L, span = 0.5),
  list(name = "degree12_interior_span24_5", n = 16L, degree = 12L, span = 24.5)
)
fixtures <- lapply(configs, function(cfg) {
  intervals <- cfg$n + 2L - cfg$degree
  times <- canonicalize_receipt_numbers(sort(unique(c(
    -0.1, cfg$span + 0.1, cfg$span * seq(0, 2L * intervals) / (2L * intervals),
    cfg$span * c(1e-6, 1 / pi, 1 / sqrt(2), 0.999999)
  ))))
  values <- env$hrf_bspline(times, span = cfg$span, N = cfg$n, degree = cfg$degree)
  stopifnot(ncol(values) == cfg$n, all(is.finite(values)),
            all(values[times <= 0 | times >= cfg$span, , drop = FALSE] == 0))
  c(cfg, list(times = times, values = as.vector(t(values))))
})
# Pin upstream's rejected domain as well as successful evaluations.
for (cfg in list(c(1L, 0L), c(1L, 3L), c(2L, 4L))) {
  rejected <- inherits(try(env$hrf_bspline(0, N = cfg[1L], degree = cfg[2L]),
                          silent = TRUE), "try-error")
  stopifnot(rejected)
}
fmt <- function(x) paste(receipt_format_number(x), collapse = ", ")
lines <- c(
  "package scalafim.fmri.hrf.fixtures", "",
  "// Generated by docs/verification/hrf-endpoint-anchored-bspline-20261005/generate_fixture.R.",
  paste0("// Oracle: fmrihrf ", revision, ", hrf_bspline; source blob ", blob, "."),
  paste0("// ", R.version.string, "; splines ", packageVersion("splines"), "."),
  paste0("// Numbers: ", receipt_serialization_convention(), "."),
  "object EndpointAnchoredBsplineRFixtures:",
  "  final case class Fixture(name: String, nBasis: Int, degree: Int, span: Double,",
  "      times: Vector[Double], values: Vector[Double]):",
  "    def at(row: Int, column: Int): Double = values(row * nBasis + column)",
  "", "  val all: Vector[Fixture] = Vector("
)
entries <- vapply(fixtures, function(f) sprintf(
  paste0("    Fixture(\"%s\", %d, %d, %s,\n",
         "      times = Vector(%s),\n      values = Vector(%s))"),
  f$name, f$n, f$degree, receipt_format_number(f$span), fmt(f$times), fmt(f$values)
), character(1))
out <- "modules/hrf/shared/src/test/scala/scalafim/fmri/hrf/fixtures/EndpointAnchoredBsplineRFixtures.scala"
writeLines(c(lines, paste(entries, collapse = ",\n"), "  )"), out)
cat(sprintf("Pinned fmrihrf %s; source blob %s\n", revision, blob))
cat(sprintf("%s; splines %s\n", R.version.string, packageVersion("splines")))
cat(sprintf("Generated %d configurations, %d rows, %d values; endpoint/support/domain checks passed.\n",
            length(fixtures), sum(vapply(fixtures, function(f) length(f$times), integer(1))),
            sum(vapply(fixtures, function(f) length(f$values), integer(1)))))
cat("Wrote", out, "\n")
