package scalafim.fmri.design.fixtures

// Generated by tools/fixtures/generate_contrast_diagnostics.py with NumPy 2.4.3.
// Do not edit by hand. Expected values are independent NumPy recomputations
// (pseudo-inverse covariances, QR row bases, eigh) from the frozen matrices in
// DurableContrastMatrixFixture and the small designs below.
object ContrastDiagnosticsFixture:
  /** Oracle values recomputed from the frozen m2b/m3/m4b audit matrices. */
  object DurableAudit:
    val gambleRank: Int = 23
    val gambleRankWithEightSpikes: Int = 31
    val blockFixedEffectsFWorstSe: Double = 0.03141900097827853
    val stopFixedEffectsFWorstSe: Double = 0.17320232254158915
    val denseFixedEffectsFWorstSe: Double = 0.25771995171414225
    val dmsFixedEffectsSe: Double = 0.16045351706916144
    val dmsResidualDf: Vector[Int] = Vector(183, 183)
    val dupStateRank: Vector[Int] = Vector(27, 27)
    val dupStateNullity: Vector[Int] = Vector(4, 5)
    val dup2StateNullity: Vector[Int] = Vector(5, 6)
    /** Run sigmas for the heterogeneous weighted combinations below. */
    val weightedSigmas: Vector[Double] = Vector(0.8, 1.7)
    val weightedDmsFixedEffectsVariance: Double = 0.027018383167237817
    val weightedBlockFixedEffectsFWorstSe: Double = 0.03278785607462625

  // [intercept, u, u, w], with u and w orthogonal and centred.
  val duplicateDesign: Array[Double] = Array(
    1.0, 0.5, 0.5, 0.5,
    1.0, -0.5, -0.5, -0.5,
    1.0, 0.5, 0.5, -0.5,
    1.0, -0.5, -0.5, 0.5,
    1.0, 0.0, 0.0, 0.0
  )

  // First run has task exactly equal to its nuisance column. The second has
  // one unit-norm task direction orthogonal to the intercept nuisance.
  val singularTaskRun: Array[Double] = Array(
    1.0, 1.0,
    0.0, 0.0,
    0.0, 0.0,
    0.0, 0.0
  )
  val informativeTaskRun: Array[Double] = Array(
    1.0, 0.0,
    0.0, 1.0,
    0.0, 0.0,
    0.0, 0.0
  )

  // Concatenated task F: two runs of [task1, task2, intercept, drift]; the F
  // rows over (task1, task2) are [[1.0, 0.0], [1.0, -1.0]].
  val concatenatedRunOne: Array[Double] = Array(
    1.0, 0.0, 1.0, -2.5,
    0.0, 1.0, 1.0, -1.5,
    1.0, 1.0, 1.0, -0.5,
    0.0, 0.0, 1.0, 0.5,
    2.0, 0.0, 1.0, 1.5,
    0.0, 3.0, 1.0, 2.5
  )
  val concatenatedRunTwo: Array[Double] = Array(
    0.5, 1.0, 1.0, -1.5,
    1.0, 0.0, 1.0, -0.5,
    0.0, 2.0, 1.0, 0.5,
    1.5, 0.5, 1.0, 1.5
  )
  val concatenatedFRows: Vector[Vector[Double]] = Vector(Vector(1.0, 0.0), Vector(1.0, -1.0))
  val concatenatedFWorstSe: Double = 0.7445613293916452
  /** Run sigmas (0.5, 2.0). */
  val concatenatedWeightedFWorstSe: Double = 0.380329496773246

  // High-pass pair: [task1, task2, intercept] and the same plus one cosine.
  // Variances are along the unique worst direction of the without-cosine F
  // covariance for rows task1 and task2.
  val highPassWithout: Array[Double] = Array(
    1.0, 0.0, 1.0,
    1.0, 0.5, 1.0,
    0.0, 1.0, 1.0,
    0.0, 1.0, 1.0,
    1.0, 0.0, 1.0,
    0.5, 0.0, 1.0,
    0.0, 1.0, 1.0,
    0.0, 0.0, 1.0
  )
  val highPassWith: Array[Double] = Array(
    1.0, 0.0, 1.0, 0.9807852804032304,
    1.0, 0.5, 1.0, 0.8314696123025452,
    0.0, 1.0, 1.0, 0.5555702330196023,
    0.0, 1.0, 1.0, 0.19509032201612833,
    1.0, 0.0, 1.0, -0.1950903220161282,
    0.5, 0.0, 1.0, -0.555570233019602,
    0.0, 1.0, 1.0, -0.8314696123025453,
    0.0, 0.0, 1.0, -0.9807852804032304
  )
  val highPassWithVariance: Double = 3.1226059247495908
  val highPassWithoutVariance: Double = 1.4545454545454541
