package scalafim.fmri.design.fixtures

// Generated by tools/fixtures/generate_design_diagnostics.py with NumPy 2.4.3.
object DesignDiagnosticsFixture:
  val fullRank: Array[Double] = Array(
    0.5,
    0.69999999999999996,
    0.5,
    -0.5,
    0.10000000000000003,
    -0.5,
    0.5,
    -0.10000000000000003,
    -0.5,
    -0.5,
    -0.69999999999999996,
    0.5
  )
  val deficient: Array[Double] = Array(
    1,
    0.5,
    0.5,
    0.5,
    1,
    -0.5,
    -0.5,
    -0.5,
    1,
    0.5,
    0.5,
    -0.5,
    1,
    -0.5,
    -0.5,
    0.5
  )
  val expectedVif: Vector[Double] = Vector(1.5624999999999998, 1.5624999999999998, 1.0000000000000002)
  val expectedBlockR2: Double = 0.35999999999999988
  val expectedJointCoefficient: Double = 0.59999999999999987

  // Independent NumPy projection fixture: u and almostU differ by one
  // orthogonal direction at 1e-9.  Their finite VIF is about 1e18, which
  // detects implementations that recover it as `1 / (1 - R²)`.
  val nearCollinear: Array[Double] = Array(
    -1.0, -0.999999999,
    -1.0, -1.000000001,
    1.0, 0.999999999,
    1.0, 1.000000001
  )
  val expectedNearCollinearVif: Double = 9.999999455415596e17
