package scalafim.fmri.design.fixtures

// Generated by tools/r-parity/generate_heterogeneous_hrf_receipt.R.
object HeterogeneousHrfRFixture:
  val scans: Vector[Double] = Vector(0.0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27)
  val conditions: Vector[String] = Vector("A", "B", "A", "B")
  val sampleOnsets: Vector[Double] = Vector(1, 7, 13, 19)
  val probeOnsets: Vector[Double] = Vector(3, 9, 15, 21)
  val columnKeys: Vector[String] = Vector("sample_A", "sample_B", "probe_A_canonical", "probe_B_canonical", "probe_B_temporal")
  val matrix: Vector[Vector[Double]] = Vector(
    Vector(0.0, 0.0, 0.0, 0.0, 0.0),
    Vector(1, 0.0, 0.0, 0.0, 0.0),
    Vector(0.3678794411714, 0.0, 0.0, 0.0, 0.0),
    Vector(0.1353352832366, 0.0, 1, 0.0, 0.0),
    Vector(0.04978706836786, 0.0, 0.6065306597126, 0.0, 0.0),
    Vector(0.01831563888873, 0.0, 0.3678794411714, 0.0, 0.0),
    Vector(0.0, 0.0, 0.2231301601484, 0.0, 0.0),
    Vector(0.0, 1, 0.1353352832366, 0.0, 0.0),
    Vector(0.0, 0.3678794411714, 0.0, 0.0, 0.0),
    Vector(0.0, 0.1353352832366, 0.0, 1, 0.0),
    Vector(0.0, 0.04978706836786, 0.0, 0.3678794411714, 0.3678794411714),
    Vector(0.0, 0.01831563888873, 0.0, 0.1353352832366, 0.2706705664732),
    Vector(0.0, 0.0, 0.0, 0.04978706836786, 0.1493612051036),
    Vector(1, 0.0, 0.0, 0.01831563888873, 0.07326255555494),
    Vector(0.3678794411714, 0.0, 0.0, 0.0, 0.0),
    Vector(0.1353352832366, 0.0, 1, 0.0, 0.0),
    Vector(0.04978706836786, 0.0, 0.6065306597126, 0.0, 0.0),
    Vector(0.01831563888873, 0.0, 0.3678794411714, 0.0, 0.0),
    Vector(0.0, 0.0, 0.2231301601484, 0.0, 0.0),
    Vector(0.0, 1, 0.1353352832366, 0.0, 0.0),
    Vector(0.0, 0.3678794411714, 0.0, 0.0, 0.0),
    Vector(0.0, 0.1353352832366, 0.0, 1, 0.0),
    Vector(0.0, 0.04978706836786, 0.0, 0.3678794411714, 0.3678794411714),
    Vector(0.0, 0.01831563888873, 0.0, 0.1353352832366, 0.2706705664732),
    Vector(0.0, 0.0, 0.0, 0.04978706836786, 0.1493612051036),
    Vector(0.0, 0.0, 0.0, 0.01831563888873, 0.07326255555494),
    Vector(0.0, 0.0, 0.0, 0.0, 0.0),
    Vector(0.0, 0.0, 0.0, 0.0, 0.0)
  )
  val acceptedDifferences: Vector[String] = Vector("The oracle uses explicitly stated custom kernels so no fmridesign or fmrihrf default basis convention is imported.", "Column alignment is declared structurally as phase, cell, and basis element rather than inferred from rendered labels.")
