package scalafim.fmri.design.fixtures

// Generated by tools/r-parity/generate_modulator_policy_receipt.R from base R QR.
object ModulatorPolicyRFixture:
  val wholeX: Vector[Double] = Vector(1, 2, 3, 4, 5, 6)
  val wholeY: Vector[Double] = Vector(1, 5, 6, 9, 9, 12)
  val wholeResidual: Vector[Double] = Vector(-0.99999999999999889, 0.99999999999999989, 0.0, 0.99999999999999967, -0.99999999999999944, -5.3650398844541865e-16)
  val cellX: Vector[Double] = Vector(1, 2, 1, 2)
  val cellY: Vector[Double] = Vector(1, 7, 5, 5)
  val cells: Vector[String] = Vector("A", "A", "B", "B")
  val cellResidual: Vector[Double] = Vector(-2.0000000000000004, 1.0000000000000002, 2, -1)
  val degenerateY: Vector[Double] = Vector(2, 4, 6, 8, 10, 12)
  val degenerateResidual: Vector[Double] = Vector(2.3623684408180685e-15, 0.0, 0.0, 0.0, 6.3365222281972744e-16, -5.1051965122308044e-16)
  val acceptedDifferences: Vector[String] = Vector("R fmridesign does not implicitly apply ScalaFIM ordered modulator policies; base-R QR supplies only the independent numerical reference.", "R model-frame na.action defaults are not used; ScalaFIM missing-value behavior is selected explicitly by MissingValuePolicy.")
