package scalafim.fmri.design.fixtures

// Generated by tools/generate_r_parity_fixtures.R from the live R scalafim.fmri.design source.
object RParityFixtures:
  final case class MatrixFixture(rows: Int, cols: Int, columnNames: Vector[String], values: Vector[Double])
  final case class EventFixture(
      termKeys: Vector[String],
      matrix: MatrixFixture,
      rColIndices1Based: Map[String, Vector[Int]],
      rTermSpans1Based: Vector[Int],
      attachedContrastKeys: Vector[String],
      attachedContrastWeights: Vector[Double],
      fContrastKeys: Vector[String],
      fContrastWeights: Vector[Double]
  )
  final case class BaselineFixture(termKeys: Vector[String], matrix: MatrixFixture)

  val eventInteraction: EventFixture =
    EventFixture(
      termKeys = Vector("task"),
      matrix = MatrixFixture(
        rows = 12,
        cols = 2,
        columnNames = Vector("task_cond.A_x", "task_cond.B_x"),
        values = Vector(
          0.000000000, 0.000000000,
          0.009036009, 0.000000000,
          0.220502443, 0.000000000,
          0.803283243, 0.000000000,
          1.424604415, 0.000000000,
          1.733699123, 0.004839806,
          1.676936723, 0.282286149,
          1.383353899, 1.337815500,
          1.020230455, 2.636587768,
          0.699674398, 3.415152762,
          0.976683909, 3.421246240,
          2.464393147, 2.903610386
        )
      ),
      rColIndices1Based = Map("task" -> Vector(1, 2)),
      rTermSpans1Based = Vector(2),
      attachedContrastKeys = Vector("task.diff"),
      attachedContrastWeights = Vector(1.000000000, -1.000000000),
      fContrastKeys = Vector("task#cond"),
      fContrastWeights = Vector(1.000000000, -1.000000000)
    )

  val baselineConstantRunwise: BaselineFixture =
    BaselineFixture(
      termKeys = Vector("drift"),
      matrix = MatrixFixture(
        rows = 5,
        cols = 2,
        columnNames = Vector("base_constant1_block_1", "base_constant1_block_2"),
        values = Vector(
          1.000000000, 0.000000000,
          1.000000000, 0.000000000,
          1.000000000, 0.000000000,
          0.000000000, 1.000000000,
          0.000000000, 1.000000000
        )
      )
    )
