package scalafim.fmri.ar.fixtures

// Generated by modules/ar/tools/generate_fmriar_parity.R.
object FmriArRFixture:
  val pacfPhi: Vector[Double] = Vector(0.295, -0.155, 0.2)
  val pacfBack: Vector[Double] = Vector(0.25, -0.1, 0.2)
  val stablePhi: Vector[Double] = Vector(-0.88, 0.208, 0.7)
  val expectedXRows: Vector[Vector[Double]] = Vector(Vector(1.0, 1.0, 0.0), Vector(0.45, 1.45, 1.0), Vector(1.0, 3.0, 0.0), Vector(0.45, 2.35, 1.0), Vector(1.0, 5.0, 1.0), Vector(0.45, 3.25, -0.55), Vector(0.66, 4.75, 1.21), Vector(1.0, 8.0, 0.0))
  val expectedYRows: Vector[Vector[Double]] = Vector(Vector(1.0, 0.0), Vector(1.45, 1.0), Vector(4.0, 1.0), Vector(4.8, 1.45), Vector(1.0, 1.0), Vector(2.45, 1.45), Vector(3.56, 2.11), Vector(8.0, 5.0))
  val acfNoneRows: Vector[Vector[Double]] = Vector(Vector(-0.009803921568627, -0.009803921568627), Vector(-0.6666666666667, -0.6666666666667), Vector(-0.02941176470588, -0.02941176470588))
  val acfNoneCi: Double = 0.8001666493092
  val acfMedian: Vector[Double] = Vector(-0.009803921568627, -0.6666666666667)
  val acfMedianCi: Double = 0.8001666493092
  val estimationSeries: Vector[Double] = Vector(0.4801696483974, 0.3928835619562, 0.1255844807411, -0.3861270611745, 0.4345275375434, 0.7446746954236, 0.4170828630439, 0.2762716295325, 0.1955034731459, -0.8526828948661, -0.284296288116, 0.06587250265113, -0.1611245907347, 0.6095089090592, 0.01683633195443, -0.1459287714987, -0.6046497550409, 0.6420668004105, 0.7731014903194, 1.156317023695, 1.339893330159, -0.1761467530259, 0.1592414565826, 0.9546288410139)
  val fitNoiseGamma: Vector[Double] = Vector(0.279195272801, 0.08799008862346, -0.01679475772294, -0.02475167252573, -0.06207274041301)
  val fitNoisePhiByOrder: Vector[Vector[Double]] = Vector(Vector(0.3151560831983), Vector(0.3709589183381, -0.1770641219216), Vector(0.3688205919358, -0.1725842123802, -0.01207656513938), Vector(0.3661042565723, -0.2114029157002, 0.07088083252292, -0.2249261550904))
  val fitNoiseAutoOrder: Int = 1
  val fitNoiseAutoPhi: Vector[Double] = Vector(0.3151560831983)
  val censoredRunPhi: Vector[Double] = Vector(0.6717373443298, -0.06840343902748)
  val censoredGlobalPhi: Vector[Double] = Vector(0.3016669526512)
  val fmriArRevision: String = "f563f2df20264ffa7db9be116f11d631551e9132"
  val fmriArVersion: String = "0.3.3"
