#!/usr/bin/env python3
"""Render verified row-encoding JSON evidence as portable typed Scala data."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from render_scala_fixture import (
    matrix_double,
    penalty_kind,
    scala_double,
    scala_string,
    scala_vector,
    vector_double,
)
from verify_encoding_fixtures import verify


def render(source: Path, target: Path) -> None:
    verify(source)
    fixture = json.loads(source.read_text(encoding="utf-8"))
    provenance = fixture["provenance"]
    rendered_cases = []
    for case in fixture["cases"]:
        penalty = case["penalty"]
        rendered_cases.append(
            f'''LowRankModelsEncodingOracleCase(
      id = {scala_string(case["id"])},
      loss = {scala_string(case["loss"])},
      rank = {case["rank"]},
      data = {vector_double(case["data"])},
      observed = {scala_vector(case["observed"], lambda value: str(value).lower())},
      decoder = {matrix_double(case["decoder"])},
      penalty = LowRankModelsOraclePenalty(
        {penalty_kind(penalty["kind"] if penalty["kind"] != "ridge" else "squared-frobenius")},
        {scala_double(penalty["scalaWeight"])},
        {scala_double(penalty["juliaScale"])}
      ),
      initial = {vector_double(case["initial"])},
      solution = {vector_double(case["solution"])},
      naturalParameters = {vector_double(case["naturalParameters"])},
      decoded = {vector_double(case["decoded"])},
      observedEntryLoss = {scala_double(case["objective"]["observedEntryLoss"])},
      rowPenalty = {scala_double(case["objective"]["rowPenalty"])},
      totalObjective = {scala_double(case["objective"]["total"])},
      proxGradientResidual = {scala_double(case["proxGradientResidual"])},
      residualStep = {scala_double(case["residualStep"])},
      iterations = {case["iterations"]},
      objectiveTrajectory = {vector_double(case["objectiveTrajectory"])}
    )'''
        )

    scala = f'''package scalafim.multivar

/** Generated by tools/oracles/lowrankmodels/render_scala_encoding_fixture.py.
  * Source: modules/multivar/shared/src/test/resources/lowrankmodels/encoding-v1.json
  */
final case class LowRankModelsEncodingOracleCase(
    id: String,
    loss: String,
    rank: Int,
    data: Vector[Double],
    observed: Vector[Boolean],
    decoder: Vector[Vector[Double]],
    penalty: LowRankModelsOraclePenalty,
    initial: Vector[Double],
    solution: Vector[Double],
    naturalParameters: Vector[Double],
    decoded: Vector[Double],
    observedEntryLoss: Double,
    rowPenalty: Double,
    totalObjective: Double,
    proxGradientResidual: Double,
    residualStep: Double,
    iterations: Int,
    objectiveTrajectory: Vector[Double]
)

object LowRankModelsEncodingOracleFixtureData:
  val schemaVersion: String = {scala_string(fixture["schemaVersion"])}
  val provenance: LowRankModelsOracleProvenance = LowRankModelsOracleProvenance(
    repository = {scala_string(provenance["repository"])},
    commit = {scala_string(provenance["commit"])},
    juliaVersion = {scala_string(provenance["juliaVersion"])},
    packageVersion = {scala_string(provenance["packageVersion"])}
  )
  val cases: Vector[LowRankModelsEncodingOracleCase] = Vector(
    {",\n    ".join(rendered_cases)}
  )
'''
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(target.suffix + ".tmp")
    temporary.write_text(scala, encoding="utf-8")
    temporary.replace(target)
    print(target)


def main() -> None:
    root = Path(__file__).resolve().parents[3]
    source = (
        Path(sys.argv[1]).resolve()
        if len(sys.argv) > 1
        else root / "modules/multivar/shared/src/test/resources/lowrankmodels/encoding-v1.json"
    )
    target = (
        Path(sys.argv[2]).resolve()
        if len(sys.argv) > 2
        else root
        / "modules/multivar/shared/src/test/scala/scalafim/multivar/LowRankModelsEncodingOracleFixtureData.scala"
    )
    render(source, target)


if __name__ == "__main__":
    main()
