#!/usr/bin/env python3
"""Render verified JSON oracle evidence as portable typed Scala test data."""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path
from typing import Any

from verify_fixtures import verify


def scala_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def scala_double(value: float | int) -> str:
    result = float(value)
    if not math.isfinite(result):
        raise AssertionError(f"non-finite fixture value {result}")
    rendered = repr(result)
    return rendered if any(character in rendered for character in ".eE") else rendered + ".0"


def scala_vector(values: list[Any], element) -> str:
    return "Vector(" + ", ".join(element(value) for value in values) + ")"


def vector_double(values: list[float]) -> str:
    return scala_vector(values, scala_double)


def matrix_double(values: list[list[float]]) -> str:
    return scala_vector(values, vector_double)


def matrix_bool(values: list[list[bool]]) -> str:
    return scala_vector(values, lambda row: scala_vector(row, lambda value: str(value).lower()))


def matrix_optional_double(values: list[list[float | None]]) -> str:
    def optional(value: float | None) -> str:
        return "None" if value is None else f"Some({scala_double(value)})"

    return scala_vector(values, lambda row: scala_vector(row, optional))


def penalty_kind(kind: str) -> str:
    return {
        "none": "LowRankModelsOraclePenaltyKind.NoPenalty",
        "l1": "LowRankModelsOraclePenaltyKind.L1",
        "squared-frobenius": "LowRankModelsOraclePenaltyKind.SquaredFrobenius",
    }[kind]


def render_penalty(value: dict[str, Any]) -> str:
    return (
        "LowRankModelsOraclePenalty("
        f"{penalty_kind(value['kind'])}, "
        f"{scala_double(value['scalaWeight'])}, "
        f"{scala_double(value['juliaScale'])})"
    )


def render_objective(value: dict[str, Any]) -> str:
    return (
        "LowRankModelsOracleObjective("
        f"{scala_double(value['observedEntryLoss'])}, "
        f"{scala_double(value['rowPenalty'])}, "
        f"{scala_double(value['decoderPenalty'])}, "
        f"{scala_double(value['total'])}, "
        f"{scala_double(value['responseConstant'])})"
    )


def render_scalar_case(value: dict[str, Any]) -> str:
    return f'''LowRankModelsScalarOracleCase(
      id = {scala_string(value["id"])},
      loss = {scala_string(value["loss"])},
      rank = {value["rank"]},
      data = {matrix_double(value["data"])},
      observed = {matrix_bool(value["observed"])},
      rowCodes = {matrix_double(value["rowCodes"])},
      decoder = {matrix_double(value["decoder"])},
      naturalParameters = {matrix_double(value["naturalParameters"])},
      naturalGradients = {matrix_optional_double(value["naturalGradients"])},
      decoded = {matrix_double(value["decoded"])},
      rowPenalty = {render_penalty(value["rowPenalty"])},
      decoderPenalty = {render_penalty(value["decoderPenalty"])},
      objective = {render_objective(value["objective"])}
    )'''


def render_categorical_case(value: dict[str, Any]) -> str:
    data = [int(row[0]) for row in value["data"]]
    observed = [bool(row[0]) for row in value["observed"]]
    natural = [row[0] for row in value["naturalParameters"]]
    gradients = [row[0] for row in value["naturalGradients"]]
    decoded = [row[0] for row in value["decoded"]]

    return f'''LowRankModelsCategoricalOracleCase(
      id = {scala_string(value["id"])},
      levels = {value["levels"]},
      rank = {value["rank"]},
      data = {scala_vector(data, str)},
      observed = {scala_vector(observed, lambda item: str(item).lower())},
      rowCodes = {matrix_double(value["rowCodes"])},
      decoder = {matrix_double(value["decoder"])},
      naturalParameters = {matrix_double(natural)},
      naturalGradients = {matrix_optional_double(gradients)},
      decoded = {matrix_double(decoded)},
      rowPenalty = {render_penalty(value["rowPenalty"])},
      decoderPenalty = {render_penalty(value["decoderPenalty"])},
      objective = {render_objective(value["objective"])}
    )'''


def render(source: Path, target: Path) -> None:
    verify(source)
    fixture = json.loads(source.read_text(encoding="utf-8"))
    provenance = fixture["provenance"]
    rendered_cases = []
    for case in fixture["cases"]:
        rendered_cases.append(
            render_categorical_case(case) if case["loss"] == "categorical" else render_scalar_case(case)
        )

    scala = f'''package scalafim.multivar

/** Generated by tools/oracles/lowrankmodels/render_scala_fixture.py.
  * Source: modules/multivar/shared/src/test/resources/lowrankmodels/objective-v1.json
  */
final case class LowRankModelsOracleProvenance(
    repository: String,
    commit: String,
    juliaVersion: String,
    packageVersion: String
)

enum LowRankModelsOraclePenaltyKind:
  case NoPenalty
  case L1
  case SquaredFrobenius

final case class LowRankModelsOraclePenalty(
    kind: LowRankModelsOraclePenaltyKind,
    scalaWeight: Double,
    juliaScale: Double
)

final case class LowRankModelsOracleObjective(
    observedEntryLoss: Double,
    rowPenalty: Double,
    decoderPenalty: Double,
    total: Double,
    responseConstant: Double
)

sealed trait LowRankModelsOracleCase:
  def id: String
  def rank: Int
  def rowCodes: Vector[Vector[Double]]
  def decoder: Vector[Vector[Double]]
  def rowPenalty: LowRankModelsOraclePenalty
  def decoderPenalty: LowRankModelsOraclePenalty
  def objective: LowRankModelsOracleObjective

final case class LowRankModelsScalarOracleCase(
    id: String,
    loss: String,
    rank: Int,
    data: Vector[Vector[Double]],
    observed: Vector[Vector[Boolean]],
    rowCodes: Vector[Vector[Double]],
    decoder: Vector[Vector[Double]],
    naturalParameters: Vector[Vector[Double]],
    naturalGradients: Vector[Vector[Option[Double]]],
    decoded: Vector[Vector[Double]],
    rowPenalty: LowRankModelsOraclePenalty,
    decoderPenalty: LowRankModelsOraclePenalty,
    objective: LowRankModelsOracleObjective
) extends LowRankModelsOracleCase

final case class LowRankModelsCategoricalOracleCase(
    id: String,
    levels: Int,
    rank: Int,
    data: Vector[Int],
    observed: Vector[Boolean],
    rowCodes: Vector[Vector[Double]],
    decoder: Vector[Vector[Double]],
    naturalParameters: Vector[Vector[Double]],
    naturalGradients: Vector[Vector[Option[Double]]],
    decoded: Vector[Vector[Double]],
    rowPenalty: LowRankModelsOraclePenalty,
    decoderPenalty: LowRankModelsOraclePenalty,
    objective: LowRankModelsOracleObjective
) extends LowRankModelsOracleCase

object LowRankModelsOracleFixtureData:
  val schemaVersion: String = {scala_string(fixture["schemaVersion"])}
  val provenance: LowRankModelsOracleProvenance = LowRankModelsOracleProvenance(
    repository = {scala_string(provenance["repository"])},
    commit = {scala_string(provenance["commit"])},
    juliaVersion = {scala_string(provenance["juliaVersion"])},
    packageVersion = {scala_string(provenance["packageVersion"])}
  )
  val cases: Vector[LowRankModelsOracleCase] = Vector(
    {",\n    ".join(rendered_cases)}
  )
'''
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(target.suffix + ".tmp")
    temporary.write_text(scala, encoding="utf-8")
    temporary.replace(target)
    print(target)


def main() -> None:
    root = Path(__file__).resolve().parents[3]
    source = (
        Path(sys.argv[1]).resolve()
        if len(sys.argv) > 1
        else root / "modules/multivar/shared/src/test/resources/lowrankmodels/objective-v1.json"
    )
    target = (
        Path(sys.argv[2]).resolve()
        if len(sys.argv) > 2
        else root
        / "modules/multivar/shared/src/test/scala/scalafim/multivar/LowRankModelsOracleFixtureData.scala"
    )
    render(source, target)


if __name__ == "__main__":
    main()
