#!/usr/bin/env python3
"""Render verified fitted-oracle JSON as portable typed Scala data."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from render_scala_fixture import (
    matrix_double,
    scala_double,
    scala_string,
    scala_vector,
    vector_double,
)
from verify_fitted_fixtures import verify


def render(source: Path, target: Path) -> None:
    verify(source)
    fixture = json.loads(source.read_text(encoding="utf-8"))
    provenance = fixture["provenance"]
    program = fixture["program"]
    rendered_starts = []
    for start in fixture["starts"]:
        checkpoints = ",\n        ".join(
            f"LowRankModelsFittedCheckpoint({point['iteration']}, {scala_double(point['fullObjective'])}, {scala_double(point['stationarity'])})"
            for point in start["objectiveCheckpoints"]
        )
        rendered_starts.append(
            f'''LowRankModelsFittedOracleStart(
      id = {scala_string(start["id"])},
      initialRowCodes = {vector_double(start["initial"]["rowCodes"])},
      initialDecoder = {vector_double(start["initial"]["decoder"])},
      fittedRowCodes = {vector_double(start["fittedFactors"]["rowCodes"])},
      fittedDecoder = {vector_double(start["fittedFactors"]["decoder"])},
      reconstruction = {matrix_double(start["reconstruction"])},
      decoded = {matrix_double(start["decoded"])},
      fullObjective = {scala_double(start["fullObjective"])},
      libraryObjective = {scala_double(start["libraryObjective"])},
      stationarity = {scala_double(start["stationarity"])},
      objectiveCheckpoints = Vector(
        {checkpoints}
      ),
      upstreamReportedHistory = {vector_double(start["upstreamReportedHistory"])},
      upstreamReportedFinal = {scala_double(start["upstreamReportedFinal"])},
      upstreamHistoryObjectiveDiscrepancy = {scala_double(start["upstreamHistoryObjectiveDiscrepancy"])}
    )'''
        )

    limitations = scala_vector(fixture["limitations"], scala_string)
    scala = f'''package scalafim.multivar

/** Generated by tools/oracles/lowrankmodels/render_scala_fitted_fixture.py.
  * Source: modules/multivar/shared/src/test/resources/lowrankmodels/fitted-v1.json
  */
final case class LowRankModelsFittedCheckpoint(
    iteration: Int,
    fullObjective: Double,
    stationarity: Double
)

final case class LowRankModelsFittedOracleStart(
    id: String,
    initialRowCodes: Vector[Double],
    initialDecoder: Vector[Double],
    fittedRowCodes: Vector[Double],
    fittedDecoder: Vector[Double],
    reconstruction: Vector[Vector[Double]],
    decoded: Vector[Vector[Double]],
    fullObjective: Double,
    libraryObjective: Double,
    stationarity: Double,
    objectiveCheckpoints: Vector[LowRankModelsFittedCheckpoint],
    upstreamReportedHistory: Vector[Double],
    upstreamReportedFinal: Double,
    upstreamHistoryObjectiveDiscrepancy: Double
)

object LowRankModelsFittedOracleFixtureData:
  val schemaVersion: String = {scala_string(fixture["schemaVersion"])}
  val provenance: LowRankModelsOracleProvenance = LowRankModelsOracleProvenance(
    repository = {scala_string(provenance["repository"])},
    commit = {scala_string(provenance["commit"])},
    juliaVersion = {scala_string(provenance["juliaVersion"])},
    packageVersion = {scala_string(provenance["packageVersion"])}
  )
  val data: Vector[Vector[Double]] = {matrix_double(program["data"])}
  val ridge: Double = {scala_double(program["rowPenalty"]["scalaWeight"])}
  val maximumIterations: Int = {fixture["algorithm"]["maximumIterations"]}
  val starts: Vector[LowRankModelsFittedOracleStart] = Vector(
    {",\n    ".join(rendered_starts)}
  )
  val limitations: Vector[String] = {limitations}
'''
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(target.suffix + ".tmp")
    temporary.write_text(scala, encoding="utf-8")
    temporary.replace(target)
    print(target)


def main() -> None:
    root = Path(__file__).resolve().parents[3]
    source = (
        Path(sys.argv[1]).resolve()
        if len(sys.argv) > 1
        else root / "modules/multivar/shared/src/test/resources/lowrankmodels/fitted-v1.json"
    )
    target = (
        Path(sys.argv[2]).resolve()
        if len(sys.argv) > 2
        else root
        / "modules/multivar/shared/src/test/scala/scalafim/multivar/LowRankModelsFittedOracleFixtureData.scala"
    )
    render(source, target)


if __name__ == "__main__":
    main()
