package scalafim.multivar
package family.canonical

import scalafim.multivar.core.*

import gale.linalg.DMat
import gale.linalg.DVec

/** Fixed base-R reference for the one-shot canonical-effect estimand.
  * Generated by tools/r-parity/generate_cca_one_shot_fixtures.R with
  * R 4.5.1; only base matrix operations are used.
  * X and Z are time-by-column; C is contrast-by-design.
  */
object CanonicalEffectReferenceFixtures:
  final case class RunReference(
      response: DMat,
      cross: DMat,
      total: DMat,
      effect: DMat,
      residual: DMat
  )

  final case class FoldReference(
      heldOutRun: Int,
      direction: DVec,
      trainingRoot: Double,
      ridge: Double,
      heldOutRoot: Double,
      heldOutCorrelation: Double
  )

  val analyticEffect: DMat = GaleNumerics.matrixFromRows(
    Vector(
      Vector(4.0, 2.0),
      Vector(2.0, 1.0)
    )
  )
  val analyticResidual: DMat = GaleNumerics.matrixFromRows(
    Vector(
      Vector(2.0, 0.0),
      Vector(0.0, 3.0)
    )
  )
  val analyticDirection: DVec =
    GaleNumerics.vectorFromArray(Array(0.6546536707079772, 0.2182178902359924))
  val analyticRoot: Double = 7.0 / 3.0
  val analyticCorrelation: Double = Math.sqrt(0.7)

  val contrast: DMat = GaleNumerics.matrixFromRows(
    Vector(
      Vector(0.0, 1.0, 0.0)
    )
  )
  val design: DMat = GaleNumerics.matrixFromRows(
    Vector(
      Vector(1.0, -1.0, -1.0),
      Vector(1.0, -1.0, -0.7142857142857143),
      Vector(1.0, 1.0, -0.4285714285714286),
      Vector(1.0, 1.0, -0.1428571428571429),
      Vector(1.0, -1.0, 0.1428571428571428),
      Vector(1.0, -1.0, 0.4285714285714284),
      Vector(1.0, 1.0, 0.7142857142857142),
      Vector(1.0, 1.0, 1.0)
    )
  )
  val expectedXtX: DMat = GaleNumerics.matrixFromRows(
    Vector(
      Vector(8.0, 0.0, -4.4408920985006262e-16),
      Vector(0.0, 8.0, 2.2857142857142856),
      Vector(-4.4408920985006262e-16, 2.2857142857142856, 3.4285714285714284)
    )
  )
  val ridgeFraction: Double = 0.02

  val runs: Vector[RunReference] =
    Vector(
      RunReference(
        response = GaleNumerics.matrixFromRows(
          Vector(
            Vector(-0.9000000000000001, 0.10000000000000006, -0.14999999999999997),
            Vector(-1.142857142857143, 0.5, -0.09285714285714283),
            Vector(0.9142857142857143, -0.8500000000000001, 0.21428571428571425),
            Vector(0.6714285714285715, -0.55, 0.4714285714285714),
            Vector(-1.0214285714285714, 0.75, -0.4714285714285714),
            Vector(-0.5642857142857143, 0.6499999999999999, -0.5642857142857143),
            Vector(0.9928571428571429, -0.2000000000000001, 0.4928571428571429),
            Vector(1.05, -0.4000000000000001, 0.09999999999999998)
          )
        ),
        cross = GaleNumerics.matrixFromRows(
          Vector(
            Vector(-2.2204460492503131e-16, 7.257142857142857, 2.6000000000000005),
            Vector(-2.7755575615628914e-16, -4.0, -0.1714285714285717),
            Vector(0.0, 2.5571428571428574, 0.2)
          )
        ),
        total = GaleNumerics.matrixFromRows(
          Vector(
            Vector(6.852857142857143, -3.5592857142857146, 2.1478571428571427),
            Vector(-3.5592857142857146, 2.4700000000000002, -1.3617857142857144),
            Vector(2.1478571428571427, -1.3617857142857144, 1.092857142857143)
          )
        ),
        effect = GaleNumerics.matrixFromRows(
          Vector(
            Vector(4.711484593837535, -3.3142857142857145, 2.0673669467787117),
            Vector(-3.314285714285714, 2.3314285714285714, -1.4542857142857144),
            Vector(2.0673669467787117, -1.4542857142857144, 0.9071463585434176)
          )
        ),
        residual = GaleNumerics.matrixFromRows(
          Vector(
            Vector(0.16970588235294137, -0.11500000000000021, -0.07117647058823584),
            Vector(-0.11500000000000021, 0.13000000000000034, 0.10250000000000004),
            Vector(-0.07117647058823584, 0.10250000000000004, 0.17404411764705863)
          )
        )
      ),
      RunReference(
        response = GaleNumerics.matrixFromRows(
          Vector(
            Vector(-0.9500000000000001, 0.3999999999999999, -0.4),
            Vector(-0.7071428571428571, 0.3285714285714285, -0.11428571428571427),
            Vector(0.5857142857142857, -0.6928571428571428, 0.3214285714285714),
            Vector(0.9285714285714286, -0.8642857142857142, 0.10714285714285712),
            Vector(-0.6285714285714286, 0.5642857142857143, -0.057142857142857106),
            Vector(-0.8857142857142857, 0.9928571428571428, -0.37142857142857144),
            Vector(0.9071428571428571, -0.5285714285714286, 0.1642857142857143),
            Vector(0.75, -0.19999999999999996, 0.35)
          )
        ),
        cross = GaleNumerics.matrixFromRows(
          Vector(
            Vector(3.3306690738754696e-16, 6.342857142857143, 2.0),
            Vector(-1.1102230246251565e-16, -4.571428571428571, -0.2857142857142857),
            Vector(5.5511151231257827e-17, 1.8857142857142857, 0.6285714285714287)
          )
        ),
        total = GaleNumerics.matrixFromRows(
          Vector(
            Vector(5.172857142857143, -3.6842857142857142, 1.525),
            Vector(-3.6842857142857142, 3.1185714285714283, -1.0707142857142857),
            Vector(1.525, -1.0707142857142857, 0.5785714285714285)
          )
        ),
        effect = GaleNumerics.matrixFromRows(
          Vector(
            Vector(3.8750140056022424, -3.3887955182072833, 1.1345098039215689),
            Vector(-3.3887955182072838, 2.9635854341736696, -0.9921568627450981),
            Vector(1.1345098039215689, -0.9921568627450982, 0.3321568627450981)
          )
        ),
        residual = GaleNumerics.matrixFromRows(
          Vector(
            Vector(0.13117647058823412, -0.12882352941176434, 0.023823529411764355),
            Vector(-0.1288235294117639, 0.131176470588235, -0.026176470588235246),
            Vector(0.023823529411764355, -0.026176470588235468, 0.13117647058823517)
          )
        )
      ),
      RunReference(
        response = GaleNumerics.matrixFromRows(
          Vector(
            Vector(-1.2, 2.7755575615628914e-17, 0.0),
            Vector(-1.4285714285714286, 0.33571428571428574, -0.3571428571428571),
            Vector(1.0928571428571427, -0.6285714285714287, 0.5857142857142857),
            Vector(0.9642857142857142, -0.29285714285714287, 0.2285714285714286),
            Vector(-0.9642857142857142, 0.5428571428571428, -0.4785714285714286),
            Vector(-1.042857142857143, 0.3785714285714285, -0.33571428571428574),
            Vector(1.4285714285714286, -0.08571428571428577, 0.10714285714285718),
            Vector(1.1500000000000001, -0.25, 0.25)
          )
        ),
        cross = GaleNumerics.matrixFromRows(
          Vector(
            Vector(0.0, 9.271428571428572, 3.2),
            Vector(-3.0531133177191805e-16, -2.5142857142857147, -1.1102230246251565e-16),
            Vector(8.3266726846886741e-17, 2.342857142857143, 0.08571428571428574)
          )
        ),
        total = GaleNumerics.matrixFromRows(
          Vector(
            Vector(10.985714285714286, -2.7771428571428576, 2.6228571428571428),
            Vector(-2.7771428571428576, 1.1014285714285714, -1.0135714285714286),
            Vector(2.6228571428571428, -1.0135714285714286, 0.9385714285714288)
          )
        ),
        effect = GaleNumerics.matrixFromRows(
          Vector(
            Vector(7.867650560224093, -2.771260504201682, 2.5193277310924378),
            Vector(-2.771260504201681, 0.9761344537815129, -0.8873949579831935),
            Vector(2.5193277310924378, -0.8873949579831936, 0.8067226890756304)
          )
        ),
        residual = GaleNumerics.matrixFromRows(
          Vector(
            Vector(0.13139705882352537, -0.0058823529411755615, 0.02352941176470491),
            Vector(-0.005882352941176006, 0.12529411764705856, -0.1261764705882351),
            Vector(0.023529411764705355, -0.1261764705882351, 0.12970588235294134)
          )
        )
      )
    )

  val folds: Vector[FoldReference] =
    Vector(
      FoldReference(
        heldOutRun = 0,
        direction = GaleNumerics.vectorFromArray(Array(1.9479516833805883, 0.20735275171652526, 0.3706013713731033)),
        trainingRoot = 44.89391998689901,
        ridge = 0.005199509803921531,
        heldOutRoot = 36.85005710469608,
        heldOutCorrelation = 0.9867015559934805
      ),
      FoldReference(
        heldOutRun = 1,
        direction = GaleNumerics.vectorFromArray(Array(1.7081017444730848, -0.05025719372655172, 0.8391983218545838)),
        trainingRoot = 52.3081953269612,
        ridge = 0.005734313725490171,
        heldOutRoot = 27.224609879838816,
        heldOutCorrelation = 0.9821252092225311
      ),
      FoldReference(
        heldOutRun = 2,
        direction = GaleNumerics.vectorFromArray(Array(1.4332483545445247, -0.36759957603601767, 0.8940090774604521)),
        trainingRoot = 36.22096296919086,
        ridge = 0.005781862745098031,
        heldOutRoot = 49.816358575475654,
        heldOutCorrelation = 0.990111760131141
      )
    )

  val meanHeldOutRoot: Double = 37.96367518667018
  val rootToCorrelationOfMean: Double = 0.9870841250383347
