#!/usr/bin/env Rscript
# Exact numerical fixtures for M5.04, not Monte Carlo calibration.
# Base R linear algebra, uniroot and distribution functions are independent
# of ScalaFIM's GroupGlm / Gale implementations. No study RNG stream is used.
args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1L) stop("usage: generate_group_oracle.R OUTPUT.scala")
fmt <- function(x) paste(sprintf("%.17g", x), collapse = ", ")
vec <- function(x) paste0("Vector(", fmt(x), ")")
rowmajor <- function(x) as.vector(t(x))

oracle <- function(x, y, v, policy) {
  df <- nrow(x) - ncol(x)
  at <- function(tau) {
    w <- 1 / (v + tau)
    inverse <- solve(crossprod(x, x * w))
    beta <- drop(inverse %*% crossprod(x, y * w))
    q <- sum(w * (y - drop(x %*% beta))^2)
    list(beta = beta, covariance = inverse, q = q)
  }
  fixed <- at(0)
  tau <- 0
  if (policy != "FE-z" && fixed$q > df) {
    if (startsWith(policy, "DL")) {
      w <- 1 / v
      # trace(P), P = W - WX (X'WX)^-1 X'W.
      denominator <- sum(w) - sum(diag(fixed$covariance %*% crossprod(x, x * w^2)))
      tau <- (fixed$q - df) / denominator
    } else {
      upper <- max(v, var(y), 1)
      while (at(upper)$q > df) upper <- upper * 2
      tau <- uniroot(function(t) at(t)$q - df, c(0, upper), tol = 1e-13)$root
    }
  }
  result <- at(tau)
  if (endsWith(policy, "mKH")) result$covariance <- result$covariance * max(1, result$q / df)
  se <- sqrt(diag(result$covariance))
  statistic <- result$beta / se
  p <- if (endsWith(policy, "mKH")) 2 * pt(-abs(statistic), df) else 2 * pnorm(-abs(statistic))
  critical <- if (endsWith(policy, "mKH")) qt(.975, df) else qnorm(.975)
  list(beta = result$beta, se = se, covariance = rowmajor(result$covariance), p = p,
       lower = result$beta - critical * se, upper = result$beta + critical * se,
       q = fixed$q, i2 = if (fixed$q <= 0) 0 else max(0, (fixed$q - df) / fixed$q), tau = tau)
}

fixture <- function(id, n, design, tau, first_df = NA_real_, shift = 0) {
  i <- seq_len(n) - 1
  x <- switch(design,
    intercept = matrix(1, n, 1),
    three = cbind(1, as.numeric(i < n/4), (i - (n-1)/2) / n))
  terms <- if (design == "intercept") 'Vector("mean")' else 'Vector("mean", "quarter", "trend")'
  variance <- if (design == "intercept") seq(.04, 1, length.out = n) else rev(seq(.04, 1, length.out = n))
  # Deterministic quantile fixtures exercise asymmetric leverage and precision;
  # they are not draws from a known-truth population or evidence of coverage.
  errors <- qnorm((((i * 3) %% n) + .5) / n)
  beta <- if (design == "intercept") shift else c(shift, .2, -.1)
  y <- drop(x %*% beta) + sqrt(variance + tau) * errors
  reported <- if (is.na(first_df)) variance else variance * qchisq((((i * 7 + 1) %% n) + .5) / n, first_df) / first_df
  results <- vapply(c("FE-z", "DL-z", "DL-mKH", "PM-mKH"), function(policy) {
    e <- oracle(x, y, reported, policy)
    stopifnot(identical(names(e)[1:6], c("beta", "se", "covariance", "p", "lower", "upper")))
    paste0('      Expected("', policy, '", ', paste(vapply(e[1:6], vec, character(1)), collapse = ", "),
           ", ", fmt(c(e$q, e$i2, e$tau)), ")")
  }, character(1))
  paste0('    Case("', id, '", ', n, ", ", terms, ", ", vec(rowmajor(x)), ",\n      ",
         vec(y), ",\n      ", vec(variance), ",\n      ", vec(reported), ", ",
         if (is.na(first_df)) "None" else paste0("Some(", first_df, ".0)"), ", Vector(\n",
         paste(results, collapse = ",\n"), "\n    ))")
}

cases <- c(
  fixture("GADV-DL-PM.quantile", 8, "intercept", .20),
  fixture("GADV-DF8.known-control.quantile", 80, "three", 0),
  fixture("GADV-DF8.estimated.quantile", 80, "three", 0, 8),
  fixture("estimated-df25.quantile", 80, "three", 0, 25),
  fixture("estimated-df50.quantile", 80, "three", 0, 50),
  fixture("quarter-n20.estimated-df8.quantile", 20, "three", .04, 8, .20),
  fixture("small-heterogeneous-effect.quantile", 8, "intercept", .20, 8, .50))
header <- c("package scalafim.fmri.group.fixtures", "",
  "/** Generated by tools/mvpa-inference/generate_group_oracle.R using base R.",
  "  * Deterministic adverse numerical fixtures only; no type-I/coverage admission. */",
  "object UnifiedMvpaGroupOracle:",
  "  final case class Expected(policy: String, beta: Vector[Double], se: Vector[Double],",
  "      covariance: Vector[Double], p: Vector[Double], lower: Vector[Double], upper: Vector[Double],",
  "      q: Double, i2: Double, tau: Double)",
  "  final case class Case(id: String, n: Int, terms: Vector[String], design: Vector[Double],",
  "      effects: Vector[Double], trueVariances: Vector[Double], reportedVariances: Vector[Double],",
  "      firstLevelDf: Option[Double], expected: Vector[Expected])",
  "  val cases: Vector[Case] = Vector(")
text <- c(header, paste(cases, collapse = ",\n"), "  )")
zs <- c(-38, -10, -3, -2, -sqrt(3), -1, -.1, -1e-10, 0, 1e-10, .1, 1,
        sqrt(3) - 1e-12, sqrt(3), sqrt(3) + 1e-12, 1.96, 2, 3, 5, 8, 10, 20, 30, 37, 38)
text <- c(text, "  // Base R pnorm tails, including the gamma-series boundary and subnormal tails.",
          "  val normal: Vector[(Double, Double, Double)] = Vector(",
          paste(vapply(zs, function(z) paste0("    (", fmt(c(z, exp(pnorm(z, lower.tail = FALSE, log.p = TRUE)),
                  2*exp(pnorm(-abs(z), log.p = TRUE)))), ")"), character(1)), collapse = ",\n"),
          "  )")
dir.create(dirname(args[[1L]]), recursive = TRUE, showWarnings = FALSE)
writeLines(text, args[[1L]])
cat("Wrote seven deterministic adverse cases, four policies each; no Monte Carlo admission.\n")
