#!/usr/bin/env Rscript
# Independent base-R QR/SVD oracle. No Scala, Gale or Multivar numeric helpers.
args <- commandArgs(trailingOnly=TRUE)
if (length(args) != 1L) stop('usage: generate_rank_score_oracle_v2.R OUTPUT.scala')
options(digits=17)
permutations <- function(x) {
  if (length(x) == 1L) return(matrix(x,1L))
  do.call(rbind,lapply(seq_along(x),function(i) cbind(x[[i]],permutations(x[-i]))))
}
orth <- function(x) qr.Q(qr(x))[,seq_len(ncol(x)),drop=FALSE]
wilks <- function(x,y) -sum(log1p(-svd(crossprod(orth(x),orth(y)),nu=0,nv=0)$d^2))
reference <- function(x,y,actions) {
  qx <- orth(x); qy <- orth(y); s <- svd(crossprod(qx,qy))
  complete <- function(w) {
    if (nrow(w)==ncol(w)) return(w)
    cbind(w,qr.Q(qr(w),complete=TRUE)[,(ncol(w)+1L):nrow(w),drop=FALSE])
  }
  u <- qx %*% complete(s$u); v <- qy %*% complete(s$v)
  k <- min(ncol(x),ncol(y))
  statistic <- function(action) vapply(seq_len(k),function(j)
    wilks(u[action,j:ncol(u),drop=FALSE],v[,j:ncol(v),drop=FALSE]),0.0)
  observed <- statistic(seq_len(nrow(x)))
  null <- t(apply(actions,1L,statistic))
  identity <- apply(actions,1L,function(p) identical(as.integer(p),seq_len(nrow(x))))
  # Identity's inclusive tie is algebraic, independent of numerical refitting.
  null[identity,] <- rep(observed,each=sum(identity))
  counts <- colSums(sweep(null[!identity,,drop=FALSE],2L,observed,`>=`))
  list(roots=s$d,observed=observed,statistics=null,counts=counts)
}
set.seed(728491)
make <- function(n,p,q) list(x=matrix(rnorm(n*p),n,p),y=matrix(rnorm(n*q),n,q))
a <- make(9,3,2)
b <- make(6,2,2)
cases <- list(list(name='unequal_left',x=a$x,y=a$y,exact=FALSE),
              list(name='unequal_right',x=a$y,y=a$x,exact=FALSE),
              list(name='complete_group',x=b$x,y=b$y,exact=TRUE))
number <- function(x) paste(format(x,digits=17,scientific=TRUE,trim=TRUE),collapse=', ')
vec <- function(x) paste0('Vector(',number(x),')')
mat <- function(x) paste0('matrix(',nrow(x),', ',ncol(x),', ',vec(as.vector(t(x))),')')
lines <- c('package scalafim.fmri.mvpa.inference','',
  'import gale.linalg.DMat','',
  '/** Generated by independent base R QR/SVD; regenerate with generate_rank_score_oracle_v2.R. */',
  'object RankScoreOracleFixtures:',
  '  private def matrix(rows: Int, cols: Int, values: Vector[Double]): DMat =',
  '    DMat.tabulate(rows, cols)((i, j) => values(i * cols + j))',
  '  private def actions(text: String): Vector[Vector[Int]] =',
  '    text.split(";").toVector.map(_.split(",").toVector.map(_.toInt))',
  '  private def statistics(text: String): Vector[Vector[Double]] =',
  '    text.split(";").toVector.map(_.split(",").toVector.map(_.toDouble))',
  '  final case class Fixture(name: String, x: DMat, y: DMat, actions: Vector[Vector[Int]],',
  '      roots: Vector[Double], observed: Vector[Double], statistics: Vector[Vector[Double]],',
  '      nonIdentityExceedances: Vector[Int], exact: Boolean)',
  '  val cases: Vector[Fixture] = Vector(')
for (i in seq_along(cases)) {
  d <- cases[[i]]; n <- nrow(d$x)
  actions <- if (d$exact) permutations(seq_len(n)) else
    rbind(seq_len(n),rev(seq_len(n)),c(2:n,1),c(2,1,3:n))
  r <- reference(d$x,d$y,actions)
  action_text <- paste(apply(actions-1L,1L,function(p) paste(p,collapse=',')),collapse=';')
  stat_text <- paste(apply(r$statistics,1L,number),collapse=';')
  lines <- c(lines,paste0('    Fixture("',d$name,'",'),
    paste0('      ',mat(d$x),','),paste0('      ',mat(d$y),','),
    paste0('      actions("',action_text,'"),'),paste0('      ',vec(r$roots),', ',vec(r$observed),','),
    paste0('      statistics("',stat_text,'"),'),paste0('      Vector(',paste(r$counts,collapse=', '),'), ',tolower(d$exact),')',if(i<length(cases)) ',' else ''))
}
lines <- c(lines,'  )')
# Independent nuisance projector (basis rotations/signs intentionally immaterial).
z <- cbind(1,seq(-1,1,length.out=9),c(1,-1,0,2,-2,1,0,-1,0))
projector <- diag(9)-z %*% solve(crossprod(z),t(z))
lines <- c(lines,paste0('  val nuisance: DMat = ',mat(z)),
           paste0('  val residualProjector: DMat = ',mat(projector)),
           paste0('  val nuisanceRoots: Vector[Double] = ',vec(svd(crossprod(orth(projector %*% a$x),orth(projector %*% a$y)),nu=0,nv=0)$d)))
writeLines(lines,args[[1]])
cat('Independent base R oracle: unequal dimensions in both directions, 720 complete-group actions, nuisance projector\n')
print(sessionInfo())
