package scalafim.inference

/** Generated by modules/inference/fixtures/generate.R from multifer.
  * Do not hand-edit: regenerate from the recorded reference checkout.
  */
object InferenceRReferenceFixtures:
  final case class MatrixData(rows: Int, cols: Int, values: Vector[Double]):
    require(rows > 0 && cols > 0)
    require(values.length == rows * cols)

    def apply(row: Int, col: Int): Double =
      values(row * cols + col)

  final case class FixedMonteCarloCase(
      name: String, alternative: String, observed: Double, nullValues: Vector[Double],
      exceedances: Int, pValue: Double, mcSe: Double
  )
  final case class SequentialMonteCarloCase(
      name: String, alternative: String, observed: Double, nullValues: Vector[Double],
      maxDraws: Int, alpha: Double, boundary: Int, batchSchedule: Vector[Int],
      exceedances: Int, drawn: Int, stopReason: String, pValue: Double, mcSe: Double
  )
  final case class UnitExpectation(
      id: String, kind: String, membersOneBased: Vector[Int], identifiable: Boolean, selected: Boolean
  )
  final case class UnitFormationCase(
      name: String, roots: Vector[Double], selectedInput: Vector[Boolean],
      groupNearTies: Boolean, tieThreshold: Double, units: Vector[UnitExpectation]
  )
  final case class AlignmentCase(
      name: String, reference: MatrixData, replicate: MatrixData,
      permutationOneBased: Vector[Int], aligned: MatrixData, matchScore: Double,
      matchMargin: Double, ambiguous: Boolean, method: String
  )
  final case class PrincipalAngleCase(
      name: String, a: MatrixData, b: MatrixData, anglesRadians: Vector[Double]
  )
  final case class LadderStep(
      stepOneBased: Int, observed: Double, pValue: Double, mcSe: Double,
      exceedances: Int, allocated: Int, drawn: Int, boundary: Int, stopReason: String,
      batchSchedule: Vector[Int], nullValues: Vector[Double], selected: Boolean
  )
  final case class LadderFixture(
      name: String, family: String, target: String, nullAction: String, seed: Long,
      x: MatrixData, y: Option[MatrixData], roots: Vector[Double],
      units: Vector[UnitExpectation], steps: Vector[LadderStep],
      rejectedThrough: Int, lastStepTested: Int
  )

  val schema: String = "scalafim-inference-r-v1"
  val multiferVersion: String = "1.0.0"
  val multiferCommit: String = "b42afa827ebe4f38fa5236423e758026c6a6c551"
  val multiferDirty: Boolean = true
  val multiferSourcesDirty: Boolean = false
  val rVersion: String = "R version 4.5.1 (2025-06-13)"
  val rngKind: String = "Mersenne-Twister/Inversion/Rejection"
  val sourceSha256: Map[String, String] =
    Map(
      "R/mc_pvalue.R" -> "60d8c91f306c011356f500fd1288906cfec3612c52a325551a630b996556f647",
      "R/mc_sequential.R" -> "34594e90fe695c11ea2a84c02a2046b6629a338a6b21c4f5a839970e21be642e",
      "R/unit_formation.R" -> "3e9e57aa8ac56ef316a3daba44ec5ba0b27b3bb5be714ea11863a9b4ecd3d028",
      "R/alignment.R" -> "479534f54b0339983a03d5899f702b1eb3e228f5d764e98d40e3b44f2de13c00",
      "R/infer_plan.R" -> "a6cf8625631ddbbeb400102bda0a43f7063e026297a990cc214b8bfcaf004b58",
      "R/engine_oneblock.R" -> "62b322f11b16987b450e0fbcdf947dcbab92b83bcb46d5fe3012812f9e9d8bd1",
      "R/engine_cross.R" -> "2b6bfe392177af07d598be4dff51d83216843958f56b34f0b5c56a479e9bb706"
    )

  val fixedMonteCarlo: Vector[FixedMonteCarloCase] =
    Vector(
      FixedMonteCarloCase("greater_with_ties", "greater", 2.0, Vector(0.0, 2.0, 3.0, -1.0, 2.0), 3, 0.66666666666666663, 0.21081851067789195),
      FixedMonteCarloCase("less_lower_tail", "less", -1.0, Vector(0.0, -2.0, 1.0, -1.0, 3.0), 2, 0.5, 0.22360679774997896),
      FixedMonteCarloCase("two_sided_magnitude", "two_sided", -2.0, Vector(-3.0, -2.0, -1.0, 0.0, 2.0, 4.0), 4, 0.7142857142857143, 0.18442777839082938)
    )

  val sequentialMonteCarlo: Vector[SequentialMonteCarloCase] =
    Vector(
      SequentialMonteCarloCase("early_non_rejection", "greater", 1.0, Vector(2.0, 1.5, 1.2, 0.0, 2.5, 1.1000000000000001), 20, 0.20000000000000001, 5, Vector(3, 3), 5, 6, "non_reject_early", 0.8571428571428571, 0.14285714285714288),
      SequentialMonteCarloCase("full_budget_rejection", "greater", 5.0, Vector(-2.0, -1.7894736842105263, -1.5789473684210527, -1.368421052631579, -1.1578947368421053, -0.94736842105263164, -0.73684210526315796, -0.52631578947368429, -0.31578947368421062, -0.10526315789473695, 0.10526315789473673, 0.31578947368421062, 0.52631578947368407, 0.73684210526315752, 0.94736842105263142, 1.1578947368421053, 1.3684210526315788, 1.5789473684210522, 1.7894736842105261, 2.0), 20, 0.20000000000000001, 5, Vector(6, 6, 6, 2), 0, 20, "exhausted", 0.047619047619047616, 0.047619047619047616)
    )

  val unitFormation: Vector[UnitFormationCase] =
    Vector(
      UnitFormationCase(
      "single_axes_default", Vector(5.0, 4.9900000000000002, 1.0), Vector(true, true, false), false, 0.01,
      Vector(
      UnitExpectation("u1", "component", Vector(1), true, true),
      UnitExpectation("u2", "component", Vector(2), true, true),
      UnitExpectation("u3", "component", Vector(3), true, false)
    )
    ),
      UnitFormationCase(
      "near_tie_partial_selection", Vector(5.0, 4.9900000000000002, 1.0), Vector(true, false, true), true, 0.01,
      Vector(
      UnitExpectation("u1", "subspace", Vector(1, 2), false, false),
      UnitExpectation("u2", "component", Vector(3), true, true)
    )
    ),
      UnitFormationCase(
      "consecutive_tie_chain", Vector(5.0, 4.96, 4.9199999999999999, 1.0), Vector(true, true, true, false), true, 0.01,
      Vector(
      UnitExpectation("u1", "subspace", Vector(1, 2, 3), false, true),
      UnitExpectation("u2", "component", Vector(4), true, false)
    )
    )
    )

  val alignment: Vector[AlignmentCase] =
    Vector(
      AlignmentCase(
      "permuted_sign_flips", MatrixData(4, 3, Vector(1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0)), MatrixData(4, 3, Vector(-0.0, 0.0, -1.0, -1.0, 0.0, -0.0, -0.0, 1.0, -0.0, -0.0, 0.0, -0.0)),
      Vector(3, 1, 2), MatrixData(4, 3, Vector(1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0)), 3.0, 1.0, false, "hungarian"
    ),
      AlignmentCase(
      "ambiguous_equal_scores", MatrixData(2, 2, Vector(1.0, 0.0, 0.0, 1.0)), MatrixData(2, 2, Vector(0.70710678118654746, 0.70710678118654746, 0.70710678118654746, 0.70710678118654746)),
      Vector(1, 2), MatrixData(2, 2, Vector(0.70710678118654746, 0.70710678118654746, 0.70710678118654746, 0.70710678118654746)), 1.4142135623730949, 0.0, true, "hungarian"
    )
    )

  val principalAngles: Vector[PrincipalAngleCase] =
    Vector(
      PrincipalAngleCase("axis_30_degrees", MatrixData(2, 1, Vector(1.0, 0.0)), MatrixData(2, 1, Vector(0.86602540378443871, 0.49999999999999994)), Vector(0.52359877559829882)),
      PrincipalAngleCase("orthogonal_axes", MatrixData(3, 1, Vector(1.0, 0.0, 0.0)), MatrixData(3, 1, Vector(0.0, 1.0, 0.0)), Vector(1.5707963267948966)),
      PrincipalAngleCase("planes_one_tilted_axis", MatrixData(3, 2, Vector(1.0, 0.0, 0.0, 1.0, 0.0, 0.0)), MatrixData(3, 2, Vector(1.0, 0.0, 0.0, 0.86602540378443871, 0.0, 0.49999999999999994)), Vector(0.0, 0.52359877559829882))
    )

  val ladders: Vector[LadderFixture] =
    Vector(
      LadderFixture(
      "pca_exact_rank_two", "pca",
      "Vitale P3 tail-ratio on squared variance roots",
      "independent within-column row permutations of the deflated residual", 1729L,
      MatrixData(8, 4, Vector(-6.5, 3.5, -0.80000000000000004, -0.69999999999999996, -3.5, 4.0, 0.80000000000000004, -0.80000000000000004, -2.5, 0.5, -0.80000000000000004, -0.099999999999999978, 0.5, 1.0, 0.80000000000000004, -0.20000000000000001, 0.5, 1.0, 0.80000000000000004, -0.20000000000000001, 1.5, -2.5, -0.80000000000000004, 0.5, 4.5, -2.0, 0.80000000000000004, 0.39999999999999997, 5.5, -5.5, -0.80000000000000004, 1.0999999999999999)), None,
      Vector(177.95225294540472, 15.007747054595331, 4.4675041057642109e-31, 2.5402411073243307e-32),
      Vector(
      UnitExpectation("u1", "component", Vector(1), true, true),
      UnitExpectation("u2", "component", Vector(2), true, true),
      UnitExpectation("u3", "subspace", Vector(3, 4), false, false)
    ),
      Vector(
        LadderStep(1, 0.92222353309185656, 0.025000000000000001, 0.025000000000000001, 0, 39, 39, 4, "exhausted", Vector(5, 5, 5, 5, 5, 5, 5, 4), Vector(0.83568234413401266, 0.65933474437934325, 0.59410849894932971, 0.75146324243398266, 0.84544547071164677, 0.6995443010173511, 0.81938690889114307, 0.70158674938256926, 0.60732499892685443, 0.59430473127353134, 0.74538825730347047, 0.60865416408323059, 0.65182635358708974, 0.66404408682090488, 0.61056980615490053, 0.83804920055964927, 0.6056505642075688, 0.65445129391879586, 0.77481960551533702, 0.79692868146897589, 0.66926326725503293, 0.63824536255806874, 0.74297348975608246, 0.61056617798089396, 0.69268494392208513, 0.60254040350916271, 0.63156029027028671, 0.62787037690532321, 0.78041864836993502, 0.59898980743631391, 0.78252492614927682, 0.74428163477228848, 0.74114769710859163, 0.67395855061860122, 0.62825176174108022, 0.6062501438849196, 0.59921844996383011, 0.61897904902796275, 0.61230828305849994), true),
        LadderStep(2, 0.99999999999999989, 0.025000000000000001, 0.025000000000000001, 0, 39, 39, 4, "exhausted", Vector(5, 5, 5, 5, 5, 5, 5, 4), Vector(0.56659062834348572, 0.74074439204384102, 0.95343324973269683, 0.80311730548272731, 0.65961385077597168, 0.69537093327311383, 0.56277889199425057, 0.71077011420950675, 0.78639612311092855, 0.6747083617359938, 0.56020974782698352, 0.75871306896141788, 0.95547059809602641, 0.78009434098163699, 0.71249532445774189, 0.81618598376361207, 0.72081030880609198, 0.94365296663492959, 0.67750321514433409, 0.80023375409869479, 0.71772168323607444, 0.5579214775053094, 0.75857235329561723, 0.97832301900284679, 0.75799505162411807, 0.58083002299571806, 0.55449849111656935, 0.78922200044430202, 0.79278022058319331, 0.71868339201794507, 0.56789605203637472, 0.78293988275263604, 0.70989626482701884, 0.9676090857355566, 0.76073640673546883, 0.69092038262754973, 0.75286551756603681, 0.77820618463892333, 0.73853148858315243), true),
        LadderStep(3, 0.0, 1.0, 0.0, 5, 39, 5, 4, "non_reject_early", Vector(5), Vector(0.0, 0.0, 0.0, 0.0, 0.0), false)
      ), 2, 3
    ),
      LadderFixture(
      "plsc_exact_rank_two", "plsc",
      "squared leading singular value of the deflated cross-product",
      "row permutation of Y relative to X", 2718L,
      MatrixData(8, 4, Vector(-6.5, 3.5, -0.80000000000000004, -0.69999999999999996, -3.5, 4.0, 0.80000000000000004, -0.80000000000000004, -2.5, 0.5, -0.80000000000000004, -0.099999999999999978, 0.5, 1.0, 0.80000000000000004, -0.20000000000000001, 0.5, 1.0, 0.80000000000000004, -0.20000000000000001, 1.5, -2.5, -0.80000000000000004, 0.5, 4.5, -2.0, 0.80000000000000004, 0.39999999999999997, 5.5, -5.5, -0.80000000000000004, 1.0999999999999999)), Some(MatrixData(8, 4, Vector(-4.2999999999999998, -0.5, -1.3000000000000003, 1.5, -3.2000000000000002, 3.0, -0.70000000000000007, 0.0, -1.3, -1.5, -0.5, 0.89999999999999991, -0.20000000000000001, 2.0, 0.10000000000000001, -0.59999999999999998, -0.20000000000000001, 2.0, 0.10000000000000001, -0.59999999999999998, 1.7, -2.5, 0.30000000000000004, 0.29999999999999999, 2.7999999999999998, 1.0, 0.90000000000000002, -1.2, 4.7000000000000002, -3.5, 1.1000000000000001, -0.29999999999999993))),
      Vector(14016.904087368721, 467.8095126312798, 8.2689610109870353e-31, 7.0575195004462889e-32),
      Vector(
      UnitExpectation("u1", "component", Vector(1), true, true),
      UnitExpectation("u2", "component", Vector(2), true, true),
      UnitExpectation("u3", "subspace", Vector(3, 4), false, false)
    ),
      Vector(
        LadderStep(1, 14016.904087368725, 0.025000000000000001, 0.025000000000000001, 0, 39, 39, 4, "exhausted", Vector(5, 5, 5, 5, 5, 5, 5, 4), Vector(4759.5270155403623, 8951.6563069623353, 3615.3216000000029, 5538.3839571425606, 489.53080346131037, 4708.1377201466175, 5154.420993420229, 3325.7108026491119, 1647.6167854711327, 417.63502462263727, 6392.9936218574867, 4134.4265877392072, 7641.2117633763801, 2325.8293999414359, 284.69744826173695, 8308.9695631573813, 445.56156982873364, 1276.024803354974, 9831.8000000000102, 7509.5617715179096, 1560.4297943117779, 3583.2682576804018, 206.95431494970489, 10181.064435989792, 6432.1400000000021, 404.45095445803537, 1752.5414104443257, 2627.785010365219, 2032.2563596782441, 1772.0478843910598, 3819.0770786341986, 1129.4505406792709, 7472.9581974828052, 7248.0239396428924, 945.4208000000009, 7403.8021336477368, 6539.3150926087083, 667.95608791780285, 489.53080346131037), true),
        LadderStep(2, 467.80951263128071, 0.025000000000000001, 0.025000000000000001, 0, 39, 39, 4, "exhausted", Vector(5, 5, 5, 5, 5, 5, 5, 4), Vector(1.1873075250400329, 15.635830109533623, 0.00058648378387986537, 65.334790320780556, 7.163689073833492, 107.8493724071318, 1.3377761510606674, 118.38719329664143, 198.88794360048652, 0.63844461243889317, 1.5433299658891775, 89.445696060326739, 3.9942689504854312, 142.88315576946371, 156.64758325111518, 119.84938146855073, 112.93800718782373, 0.69936093256351239, 106.46254638435929, 110.88847766473383, 1.4521637940773817, 3.803014308435241, 1.5433299658891753, 0.46731732816785065, 127.80686129326011, 0.032654699428988729, 87.413517587415299, 0.047505186494271684, 19.865889791399979, 95.389094303014332, 137.15220471962252, 0.23996938614355529, 84.717575258863391, 139.43050952874594, 62.063992521102847, 157.86234012226709, 165.7267105317454, 4.312837243267797, 79.986001693421898), true),
        LadderStep(3, 0.0, 1.0, 0.0, 5, 39, 5, 4, "non_reject_early", Vector(5), Vector(0.0, 0.0, 0.0, 0.0, 0.0), false)
      ), 2, 3
    )
    )
