package scalafim.inference

/** Generated by modules/inference/fixtures/generate_phase6.R using base R.
  * Do not hand-edit: regenerate from the documented analytic/reference script.
  */
object Phase6RReferenceFixtures:
  final case class MatrixData(rows: Int, cols: Int, values: Vector[Double]):
    def toRows: Vector[Vector[Double]] =
      Vector.tabulate(rows)(row => Vector.tabulate(cols)(col => values(row * cols + col)))
  val rVersion: String = "R version 4.5.1 (2025-06-13)"
  val ccaX: MatrixData = MatrixData(8, 2, Vector(1, 0.0, 2, 1, 3, 1, 4, 2, 5, 3, 6, 5, 7, 8, 8, 13))
  val ccaY: MatrixData = MatrixData(8, 2, Vector(0.0, 1, 1, 1, 1, 2, 2, 3, 3, 5, 5, 8, 8, 13, 13, 21))
  val ccaRidge: Double = 1e-08
  val ccaRoots: Vector[Double] = Vector(0.99999999948858487, 0.25855377417987047)
  val generalizedA: MatrixData = MatrixData(3, 3, Vector(9, 0.0, 0.0, 0.0, 4, 0.0, 0.0, 0.0, 1))
  val generalizedB: MatrixData = MatrixData(3, 3, Vector(1, 0.0, 0.0, 0.0, 2, 0.0, 0.0, 0.0, 4))
  val generalizedRoots: Vector[Double] = Vector(9, 2, 0.25)
  val rrrX: MatrixData = MatrixData(8, 1, Vector(-3, -2, -1, 0.0, 1, 2, 3, 4))
  val rrrY: MatrixData = MatrixData(8, 1, Vector(-5.7999999999999998, -4.2000000000000002, -1.8999999999999999, 0.20000000000000001, 2.1000000000000001, 3.8999999999999999, 6.2000000000000002, 8.0999999999999996))
  val rrrTrainingZeroBased: Vector[Int] = Vector(0, 1, 2, 3, 4, 5)
  val rrrTestZeroBased: Vector[Int] = Vector(6, 7)
  val rrrGain: Double = 0.99960111840263266
  val rrrModelSse: Double = 0.053061224489796451
  val rrrBaselineSse: Double = 133.02500000000003
  val cpcaData: MatrixData = MatrixData(6, 4, Vector(2, 0.0, 1, 0.0, 1, 1, 0.0, 1, 3, 1, 1, 0.0, 0.0, 2, 1, 1, 1, 3, 0.0, 2, 2, 4, 1, 3))
  val cpcaRowDesign: MatrixData = MatrixData(6, 2, Vector(1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1))
  val cpcaColumnDesign: MatrixData = MatrixData(4, 2, Vector(1, 0.0, 1, 0.0, 0.0, 1, 0.0, 1))
  val cpcaRoots: Vector[Double] = Vector(46.36361635502395, 0.46971697830939207)
  val multiblockData: MatrixData = MatrixData(6, 4, Vector(-2, -1, -1.8, -0.80000000000000004, -1, 0.0, -1.1000000000000001, 0.20000000000000001, 0.0, 1, 0.10000000000000001, 0.90000000000000002, 1, 0.0, 0.80000000000000004, 0.10000000000000001, 2, 1, 2.2000000000000002, 1.2, 3, 2, 2.8999999999999999, 2.1000000000000001))
  val multiblockRoots: Vector[Double] = Vector(1.9112461864688428, 0.084552066635701237, 0.003123125269023413, 0.0010786216264326532, 7.8482361594050469e-17, 0.0)
  val featureObserved: Vector[Double] = Vector(3, 2, 1, 0.5)
  val featureNull: MatrixData = MatrixData(9, 4, Vector(0.20000000000000001, 2.5, 0.80000000000000004, 0.69999999999999996, 1, 1.5, 1.2, 0.10000000000000001, 2, 2.1000000000000001, 0.5, 0.90000000000000002, 3.5, 0.5, 1.5, 0.40000000000000002, 0.10000000000000001, 3, 0.10000000000000001, 0.59999999999999998, 2.8999999999999999, 1.8999999999999999, 1.1000000000000001, 0.20000000000000001, 1.5, 2.2000000000000002, 0.90000000000000002, 0.80000000000000004, 0.69999999999999996, 0.40000000000000002, 1, 0.29999999999999999, 3.1000000000000001, 1.8, 0.69999999999999996, 1))
  val featureRawP: Vector[Double] = Vector(0.29999999999999999, 0.5, 0.5, 0.59999999999999998)
  val featureBhP: Vector[Double] = Vector(0.59999999999999998, 0.59999999999999998, 0.59999999999999998, 0.59999999999999998)
  val featureHolmP: Vector[Double] = Vector(1, 1, 1, 1)
